### ISSUE TITLE
Suggestion: Damage Block

### ISSUE THREAD

**Issue by Iyasho** [yasp-dota/yasp#1001]
Hey there!
First of all, I'd like to say I love Yasp. Thank you guys for your effort!

Is there a way to show the amount of damage blocked by items, like Crimson Guard or Pipe of Insight?
I was trying to analyse the amount of impact of those items in teamfights, but I found no way extract that data.

Thanks again!

**Comment by howardchung** [comment]
I don't think so.  The combat log only reports the amount of damage dealt after block.
