### ISSUE TITLE
Passive Gold Filtering

### ISSUE THREAD

**Issue by XYTYX** [yasp-dota/yasp#1007]
I think it would be a lot more useful if only gold gained from active sources (last hits, hero kills, destroyed buildings, etc) was displayed. Often I find myself making the decision between being active on the map (ganking, pushing) and staying where I am to gain gold and experience. Right now, with the gold graph, the change between passive gold and farming is barely noticable. It would be a lot more helpful and obvious if passive gold was taken out of the equation, and then you would see more clearly whether your decision to go gank was better than staying and farming.

**Comment by howardchung** [comment]
For purposes of the gold graph we read the gold data from the entities, and I'd rather not mess with that.

I suppose it might be possible to implement it as a client side transform on the data (subtract a set amount from each minute based on the time).

**Comment by XYTYX** [comment]
How would I go about implementing this? Any tips?

**Comment by howardchung** [comment]
Code for the chart generation is here.  You would need to modify it to trigger a redraw of the graph if a button is clicked (or some other toggle).
https://github.com/yasp-dota/yasp/blob/master/public/js/generateCharts.js

You add the button to the Jade template:
https://github.com/yasp-dota/yasp/blob/master/views/match/match_graphs.jade

**Comment by XYTYX** [comment]
Which Javascript library does Yasp use to chart it's graphs?

**Comment by howardchung** [comment]
c3.js

**Comment by howardchung** [comment]
Client side, please reopen in https://github.com/yasp-dota/ui
