### ISSUE TITLE
Winner Team Is Shown As Loser

### ISSUE THREAD

**Issue by LionHeartKBT** [yasp-dota/yasp#1010]
https://yasp.co/matches/2333415681/

Dire is shown victorious but Radiant won the game. As you see, tier 4 towers are still up for Radiant side and their ancient can't get hit but they are shown defeated.

**Comment by coreymaher** [comment]
Any idea how this match got added? Was it a replay upload? It doesn't show up on other sites so it probably doesn't show up in the API.

**Comment by howardchung** [comment]
I think it was a "no stats recorded" game.  It doesn't show up in the sequential API but can be requested via ID.
