### ISSUE TITLE
replay url API endpoint

### ISSUE THREAD

**Issue by Noxville** [yasp-dota/yasp#1013]
As a feature, it'd be cool if there was a way to make a HTTP GET request to http://api.yasp.co/matches/$matchid/parse/stream that returns a series of JSON-encoded Entry object, (potentially terminated by a {"state":"finished"} blob).

Each time this endpoint is hit, it should fire a reparse if the parser has changed (or if it's a cache-miss).

(just for clarity-sake, the GET request from the client should probably have an overridden higher timeout time just in case there is a > 30 second wait for a data stream).

TODO
- [x] finalize API
- [ ] enable support for S1 replays (need sample replays to test against, missing entity data)  https://github.com/yasp-dota/yasp/blob/23bd8a8a36814fe771a57d2eba770d4b14007b0d/java_parser/src/main/java/yasp/Main.java

**Comment by howardchung** [comment]
Questions:

* How often do you need to reparse matches?
* In order to reduce the egress cost, how much aggregation could be done immediately and provided as an API for consumers?
* Can you provide the list of replay URLs for pro matches?
* Input: Is it feasible to provide leagueids ahead of time?  If possible, that would allow the existing `scanner` service to automatically queue jobs for parse, which could reduce the time to return data from the API.

**Comment by Noxville** [comment]
* **Reparsing**: When a parser has updated functionality we'd need to reparse all the games that the updated functionality refers to. For example, if a new addition to the parser is only S2 compatible, only S2 replays need be parsed.
* **Aggregation**: Uncertain, hopefully as little as possible.
* **Replay URLS**: I have the replay URLs for all games up to ~2014
* **Leagueids**: I'm not sure on the maths behind this, but I assume any tournament marked as "professional" or "premier" is safe to pre-parse. All the premier, and ~65% of the professional tournaments are things we'd like to bring in, so it's not too wasteful to just pre-process all of them. It's possible that perhaps a smaller tournament would be brought in, but this is quite rare. I'm quite loathe to maintain a list of league_ids between sites in any way that's not via REST.

**Comment by howardchung** [comment]
OK based on discussion it's probably easiest to just have the input be a match_id and the output newline delimited JSON.

The consumer will be responsible for figuring out what matches they need parsing for.

**Comment by howardchung** [comment]
implemented.  The Java parser will need patching to support Source 1 entities.  There may be old code in the commit history that's applicable.

**Comment by howardchung** [comment]
After thinking about it some more:

We could actually preemptively log-parse every match with leagueid>0 and store the log as large text blobs in their own table.  We could also maintain separate tables with with basic API data for all of these matches.

We could build an API around this data (which is something people seem to be interested in) as well as supply the log to anyone who's interested.

The only question is how to handle reparses, but if it's not something that happens very often (like 1-2 times a year) then we could maybe handle that manually.

**Comment by howardchung** [comment]
Redid with new design.

**Comment by howardchung** [comment]
scope changed.  We'll just provide the replay url.  consumers can use the parser on the data themselves.
