### ISSUE TITLE
Some preliminary work on the YASP dataset, and requests for the next one?

### ISSUE THREAD

**Issue by dracovich** [yasp-dota/yasp#1025]
Sorry if this is the wrong place to post a few requests for the next data dump, but this is where you pointed people in the blogpost so i'm posting here :)

I've been playing around with the data a bit (preliminary stuff here: https://github.com/dracovich/dota2-match-prediction), unfortunately my attempts at predicting match results on the teams power curve hasn't been great so far (only slightly over 55% accuracy on the cross validation dataset), but have a few ideas to try and boost the results.

One of the things i would love to include would be not just the teams powercurve, but also how they've set up their lanes. Since YASp does seem to have this data (albeit not always 100% accurate of course), would it be possible to get each players laning phase role included in the player part of the next data dump ?

And another, a bit more out there question, is there any way to see the total hero damage done in a time interval? I'm currently using total number of kills in a time period to define the power curve, but a more accurate variable would probably be average total damage done in a given time period. I don't really have high hopes for this one since i'm assuming that's qutie a lot of extra data to tag on and most people wouldn't use it :) but figured i'd ask.

**Comment by howardchung** [comment]
We compute the lane based on the lane_pos data, which I believe was in the previous dump.  You can see how we do it (I think the code is in util/compute.js).

There is some data about damage at times in the teamfights.  If you want more detail, you'll need to parse replays yourself.  Every damage instance is in the combat log, so you could be as detailed as you like.
