### ISSUE TITLE
Game incorrectly listed as worst throw

### ISSUE THREAD

**Issue by morganfshirley** [yasp-dota/yasp#1028]
On my "counts" page (https://yasp.co/players/44267173/counts) the match that is listed as my worst throw is a game that my team won (https://yasp.co/matches/2348057796/).

**Comment by howardchung** [comment]
Thanks for finding this.

When stripping out the properties to pass to the parse job I forgot about the dependency on radiant_win.

Throw/comeback/stomp/loss are computed based on the parsed data (xp/gold adv) and whether the match was won, so not setting match.radiant_win messed up some of the values.

**Comment by howardchung** [comment]
Mitigation will be to request a reparse of the match when new code is deployed.

**Comment by howardchung** [comment]
I ended up having to perform cassandra surgery to purge the incorrect values :(

Anyway, looks like it's fixed.
