### ISSUE TITLE
missing stuff!!!!!!

### ISSUE THREAD

**Issue by nt47** [yasp-dota/yasp#1029]
dear yasp master:

i cant get player_win this interface!
i think u removed it ,plz recover it

**Comment by howardchung** [comment]
You can compute player_win based on match.radiant_win and the player_slot of the player.

**Comment by nt47** [comment]
thx a lot :)

**Comment by nt47** [comment]
i want to know player slot logic~
player_slot > 5 and radiant_win or player_slot > 5 and not radiant_win
why not using  0~9?

it  show 129 or 130 or 131 or 132 sometimes?

**Comment by howardchung** [comment]
you'd have to ask valve.  I'm not sure why they picked the numbers that way, but >128 is dire I believe

**Comment by nt47** [comment]
thx again 
mb i need to ask valve in dev forum...

**Comment by howardchung** [comment]
Also, I have no idea what you are using the data for, but please use the official Valve API when possible.  It has a much higher capacity and might be sufficient for what you need.

**Comment by nt47** [comment]
hard to get mmr  and need calulate by myself
but ur api is awesome and opensource
