### ISSUE TITLE
Can't update my MMR

### ISSUE THREAD

**Issue by DezZzO** [yasp-dota/yasp#1030]
So, im trying to update my mmr, my profile information (and mmr) is public, but yasp wont update it for some reason. What can be the problem? I waited for it like 2 days in a row now.

**Comment by howardchung** [comment]
have you played a ranked game since?

**Comment by DezZzO** [comment]
Oh, i need to play a game to update it?

**Comment by howardchung** [comment]
yes, that's what triggers an update.

**Comment by DezZzO** [comment]
Thanks!
