### ISSUE TITLE
lane_role filter does not work

### ISSUE THREAD

**Issue by GIider** [yasp-dota/yasp#1031]
As the title says. If you check these links you can see that it shows the same games (the most recent ones) instead of a filtered subset:

https://yasp.co/players/39088211/matches?lane_role=2
https://yasp.co/players/39088211/matches?lane_role=3

**Comment by howardchung** [comment]
I recently removed this filter for performance reasons, but it might be okay if the page is served by cache (which it generally should be, if you are filtering).

**Comment by GIider** [comment]
The only way to access the filter currently is by using the links on the "counts" page. If you do decide to remove the filter completly, then you should probably also remove the links there :wink:

**Comment by howardchung** [comment]
You don't see the apply a filter button?
