### ISSUE TITLE
Missing most of my matches

### ISSUE THREAD

**Issue by Juraashek** [yasp-dota/yasp#1032]
Hello, please have a look at my yasp (https://yasp.co/players/86748718) and dotabuff (http://www.dotabuff.com/players/86748718). 

You will notice many matches recorded at dotabuff are missing at yasp. Dunno why. All my friends who signed yasp have the same history at dotabuff and yasp.

I think Expose the data in dota2 option could been off at the time of signing yasp... If it is the case, is there any solution? For example delete me from yasp now at let me sign again?

I really want to have all my matches at yasp to get as much from the awesome stats as possible. 

Thank you for any advice.

Have a nice day, Juraashek.

**Comment by howardchung** [comment]
Yeah it looks like you had the setting off when we did the complete match history import.

Previously you could trigger a fullhistory scan by logging in but I recently decommissioned the fullhistory service but after work today I'll see if I can bring it back and run your account through it.

Perhaps we need to make it a self-service scenario, though.

**Comment by howardchung** [comment]
Ran the account_id through the fullhistory service.  I also committed a script to use for doing future one-off requests as well.
