### ISSUE TITLE
Bought / Placed wards are swaped

### ISSUE THREAD

**Issue by derdanielb** [yasp-dota/yasp#1033]
Hello guys,

i observed a miscalculation at the table "vision" in the following match https://yasp.co/matches/2352143557/vision
The table shows the Radiant bought 10 wards, but placed 12. I know there was an issue because i was playing as the lich. There were no wards dropped by dire. Also dire wards bought/placed is equal.

Table should display Lich bought 11 wards and placed 10 since i bought 2 wards at the start and gave one to Slark. Slark placed that ward and has "wards placed" = 1 which is correct.

I just wanted to let you know there was some miscalculating. I did not check if this is reproducible.

**Comment by howardchung** [comment]
Did you buy the wards on the courier?  I'm not sure if that can throw it off.

**Comment by derdanielb** [comment]
Okay, maybe the replay is corrupt in some way. I downloaded it to make sure i did not buy the wards on curier. 
The replay starts at -0:52 seconds (instead of -1:00, i guess). At that time i already gave one ward to slark. That may cause the inconsistency.
Probably not much you can do in casis like this?!

**Comment by howardchung** [comment]
Yeah, we can only work with what's in the replay.
