### ISSUE TITLE
match not showing up

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#1034]
hi,
I played a game of doom 2h ago, but it isn't showing up in my profile. Not even the minimal information from the api. Might be some caching issue again?
https://yasp.co/players/157506503/
Probably could request it, but that might make it more difficult to figure out what is causing this.

**Comment by howardchung** [comment]
Looks fine now.  We were behind a few hours most of today due to slow API responses (taking ~16 seconds to load a page).
