### ISSUE TITLE
Right align on ranking

### ISSUE THREAD

**Issue by AetherV** [yasp-dota/yasp#1039]
For Example: http://imgur.com/xtfOHld

Having the name not centered looks a bit weird in my opinion. 

Also, was the ranking algorithm changed? Can't find anything in the blog

**Comment by howardchung** [comment]
Think it looks even weirder if it's centered.

Blog post announcing the change is the second post

**Comment by AetherV** [comment]
Wait sorry, I am an idiot, wrote not there, that is how it looks. Should it not be right aligned? Currently it is center aligned.

**Comment by coreymaher** [comment]
Are you talking about the heading "Name"?
You could probably align that left to make it line up with the player names below.

**Comment by AetherV** [comment]
That moment you realize you are literally too tired to tell left from right. **sigh** sorry.

Got it twice wrong which is utterly embarrassing. I think it should be left aligned and not centered. Imma just go to bed now...
