### ISSUE TITLE
Matches not showing up

### ISSUE THREAD

**Issue by 3154** [yasp-dota/yasp#1042]
Often my matches won't automatically appear on yasp.

Profile: https://yasp.co/players/56728021

Here you can see all my matches: http://www.dotabuff.com/players/56728021

Missing for now: 

2369231586
2369366260
2369649689
2369798966

Usually I'd make a manual parse request, but this time I decided to submit a ticket. I understand the Steam API is inaccessible at times, but even after 24 hours the skipped matches don't appear. At some point new matches will start to appear, but the skipped won't.

**Comment by howardchung** [comment]
We are currently about 5 hours behind, and it looks like the ones you linked are all more recent than that.  Do you have an example of a match that was skipped (with matches after that appearing)?

**Comment by 3154** [comment]
I had last week, but I fed them manually. I'll give it a couple of days this time and post again when a "hole" happens.
