### ISSUE TITLE
Always get waiting state after upload a dem file

### ISSUE THREAD

**Issue by lpeter218065** [yasp-dota/yasp#1043]
Hi

I get into a trouble after I upload a demo file in my local env.   It always request url like http://192.168.163.130:5000/api/request_job?id=1, and then get waiting state. But I look at the online website,  it is ok to parse this file.

I just wonder what is the difference or am I doing something wrong?
below is what I did during debugging:
node --debug svc/web.js

can you please help on this? Thanks!

**Comment by howardchung** [comment]
You also need to run requests and parser workers.  Otherwise your job will never get processed.

**Comment by lpeter218065** [comment]
thanks a lot!   it works
