### ISSUE TITLE
Matches from Brazil and Singapore servers are not being recorded

### ISSUE THREAD

**Issue by WreckN** [yasp-dota/yasp#1044]
Actual match results aren't automatically recorded from Brazil and Singapore servers.  Replays are available and are able to be parsed when requested.  MMStats tab shows 0 games played from both servers in the past 24 hours.

**Comment by howardchung** [comment]
Sequence number is 14 hours behind right now (Valve API is being really slow).

MMStats has never had data for certain clusters (unrelated to the API delay).

**Comment by howardchung** [comment]
see #1045 for the new scanner design
