### ISSUE TITLE
Pages for some old matches are no longer present

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#1046]
https://yasp.co/matches/1661061955

https://yasp.co/matches/1599318845

https://yasp.co/matches/2271009777

These are just examples that I could find from my Counts page. I'm sure there must be others as well.

**Comment by howardchung** [comment]
doing postgres to cassandra migration.  might take another couple of weeks.

**Comment by howardchung** [comment]
All of these matches are now imported.  Migration is about 86% done
