### ISSUE TITLE
Generate a word cloud of the match

### ISSUE THREAD

**Issue by Vatyx** [yasp-dota/yasp#1048]
I have a script written in Node.js that utilizes http://wordcloud.com to generate a word cloud image given some text. If I implemented a way to incorporate this into the replay parsing, could it be merged or is this something you guys wouldn't really want?

**Comment by howardchung** [comment]
We are already doing it per-player.  My impression is that most matches don't have enough text to produce an interesting word cloud.

If we did do it though it's easier to do with the same library we are already using to generate the player wordclouds.

**Comment by Vatyx** [comment]
What library are you guys using for it?

**Comment by Vatyx** [comment]
Ah yeah, I forgot that there was a wordcloud tab

**Comment by howardchung** [comment]
https://github.com/timdream/wordcloud2.js/

**Comment by Vatyx** [comment]
Ah gotcha. I really am wanting to contribute to this project. Is there any
feature list or backlog you guys have somewhere?

**Comment by howardchung** [comment]
https://github.com/yasp-dota/yasp/issues

**Comment by Vatyx** [comment]
Thought you had something a little more formal but gotcha.

**Comment by howardchung** [comment]
You can filter the list by milestone.  Typically the stuff I plan to work on I'll move into a set one, otherwise they get put into Backlog.
