### ISSUE TITLE
Missing match

### ISSUE THREAD

**Issue by GIider** [yasp-dota/yasp#1050]
For some reason one of my match pages leads to a 404: https://yasp.co/matches/2186422325

Using this filter https://yasp.co/players/39088211/matches?limit=&with_hero_id=48 I can see match 2186422325 in the list, but clicking it is just a 404

**Comment by beatyt** [comment]
I have encountered the same error.

My steps for reproducing:

1. Given I am on [https://yasp.co/players/34987940/peers](https://yasp.co/players/34987940/peers)

1. When I click Vagrance(Matches) in the first row

1. When I click [1982722044](https://yasp.co/matches/1982722044) in the first row

1. Then I will encounter a 404 page

**Comment by howardchung** [comment]
see #1046
