### ISSUE TITLE
Request: Browser size, OS information to inform design

### ISSUE THREAD

**Issue by stevenla** [yasp-dota/yasp#1054]
Hey guys, I'm interested in doing some design/frontend work for you guys. It'd be really helpful if I had some data on what kind of browsers, sizes, languages, etc use YASP so I could try to make something that suits those needs.

Thanks!

**Comment by howardchung** [comment]
@albertcui can give you access to our Google Analytics page that has this data.

**Comment by howardchung** [comment]
Do you have any experience with React/Redux/React-Router?  That's what we're planning to use to build the new frontend.

**Comment by albertcui** [comment]
Should have access to Google Analytics; I used the email on your website.

**Comment by stevenla** [comment]
Yep, I'm using React/Redux at work.

Thanks for the data. I'll try something in the coming weeks.

**Comment by bmulcahy** [comment]
If you need help I am experienced in react as well
