### ISSUE TITLE
Regarding Json data dump

### ISSUE THREAD

**Issue by SomeSnm** [yasp-dota/yasp#1065]
Hello!

What fields "negative_vote" and "positive_votes" mean? Is this number of total reports/comments per game or something else?

I am looking through the dump and considering it for research project. If I will have other questions, should I post them here or do you prefer other mean of communication?

**Comment by howardchung** [comment]
I am actually not sure.  I think there's a upvote/downvote system in place.

You can continue asking questions here, although I'll close this issue for now.

**Comment by gu3st** [comment]
In client, you can vote up/down matches as they take place, as well as replays. It's a weird functionality, but it exists.

**Comment by SomeSnm** [comment]
What is the "lane_pos" in player consists of? 
For example:
'118': {'78': 2, '80': 1},
'120': {'80': 1, '82': 1, '84': 1, '86': 1}
Key 118 is a time or something else? And {'78': 2, '80': 1}, is positions during this minute of a player or something else?

**Comment by howardchung** [comment]
The format is {x:{y:seconds}}.  I believe the range for x and y is
something like 64-192 so scale the values appropriately.

**Comment by SomeSnm** [comment]
Hello. Thank you for all your answers. I have more of them :)

1.  I am working with the data dump that you published and I want to find out weather the data have all the games for specific user during specific period. Do you have some kind of log of all match_id's of all parsed games? Or maybe there is other way to check that?
2.  What approach do you use for sentiment analysis in chat section on the website? Can I read somewhere about it?
3. You previously mentioned that you are considering publishing new data dump of the games, when approximately  will it happen and what period are you considering?

Thank you for your time!

**Comment by howardchung** [comment]
1.  This dump doesn't have that information.
2.  See https://github.com/thisandagain/sentiment
3.  Hopefully it should be finish this week.  It should cover every game played from the beginning to March 2016.

**Comment by SomeSnm** [comment]
1. But maybe you have a list of parsed matches and for whom they were parsed in some other place?
2. This library doesn't have slang terms like "wp" or "ez" even though they used in sentiment analysis in yasp. Maybe you have an additional list of words that you add to the default library?

**Comment by howardchung** [comment]
1. No, the requests can be made anonymously so we don't track that information.
2. See util/compute.js, we augment the default list with a custom wordlist.
