### ISSUE TITLE
Minus stun time.

### ISSUE THREAD

**Issue by Voldemortas** [yasp-dota/yasp#1067]
https://yasp.co/matches/2410001571/performances Terrorblade has -0.93 stun time. I'm not sure if this is intended.

**Comment by howardchung** [comment]
Yeah, I've seen this a few times before.  This value is directly out of the replay and it's probably a replay bug.

**Comment by Marvizm** [comment]
made pr to fix #1068

**Comment by Marvizm** [comment]
It's not first time when I saw an issue with negative stun value, I can't fix it in replay, but I can fix it here.
