### ISSUE TITLE
Is yasp expriencing more aggresive rate limiting on WebAPI after the outage?

### ISSUE THREAD

**Issue by rossengeorgiev** [yasp-dota/yasp#1072]
If I remember correctly the rate limit is supposed to be 100,000 requests a day. I'm experiencing a much lower request count per day.

**Comment by howardchung** [comment]
honestly, I'm not sure.  Are you getting back 429 responses, or just not responding/empty JSON?

Are you sure it's API key limited (i.e., does it work with another API key/IP address?)

**Comment by rossengeorgiev** [comment]
429 status code. API key doesn't seem matter and I haven't tried a different IP. This is a new development, and the request count from that IP has been well within 100k.

**Comment by howardchung** [comment]
I think there's a separate rate limit on 5-6 req/sec for IP.  You should try all the combinations though:
key/IP
key/diff IP
diff key/IP
diff key/diff IP

**Comment by rossengeorgiev** [comment]
I remember that number from the blog post. However, at no point was I doing more than 1 per second. That's why I find this so bizarre. Just to clarify I mean specifically `GetMatchHistoryBySequenceNum`. I'm getting roughly ~7 requests a minute, before getting 429.

As you suggested, I tried different keys, old ones/new ones, couple of IPs. It takes a few requests more initially but I still hit 429.

**Comment by rossengeorgiev** [comment]
After further testing with different keys and different IPs based in different regions around the world, I can confirm that `GetMatchHistoryBySequenceNum` is heavily rate limited per IP. Roughly ~7 requests per minute, which roughly is `10,000 requests per day`. 

Could be a misconfigurations on Valve/Alkamai end due to a typo. The number stated in WebAPI ToS is `100,000 per day`.

**Comment by howardchung** [comment]
Also possible that it was overloading the servers and causing the API
issues so they dropped the limit for this endpoint.

You might want to add your findings to the learnings blog post so other
developers can benefit from your investigation
