### ISSUE TITLE
a few thousand matches disappeared

### ISSUE THREAD

**Issue by timkinisky** [yasp-dota/yasp#1075]
Hi, 

Here is my YASP profile:   https://yasp.co/players/118837094

I think a day or 2 ago a lot of matches disappeared. I have over 4000 matches. I didn't change my privacy or security settings. It shows my last match as this morning ... then previously a week ago. But I've played between then. And it only shows about 200 matches completed. 

I thought the issue would resolve itself ... and I had been getting a few issues when trying to get onto YASP saying that it wasn't available so I figure it has something to do with  that? 

Any way to get my matches back on? Anything you need from me to get it done?

**Comment by howardchung** [comment]
see https://github.com/yasp-dota/yaspissues/1071

**Comment by timkinisky** [comment]
Thanks. FYI: https://github.com/yasp-dota/yasp/issues/1071
missed a slash. 
Sorry, I only found 1032. 
thanks again.
