### ISSUE TITLE
Missing yasp history

### ISSUE THREAD

**Issue by castleking96** [yasp-dota/yasp#1076]
I have signed up for yasp about a week or more ago, but my history is still not updated. You can see compare the history from my yasp https://yasp.co/players/85543360 and my dotabuff profile http://www.dotabuff.com/players/85543360. Please do help in updating my stats, I would love to try out yasp's features, but the insufficient history is preventing me to do an  in depth analysis.

**Comment by howardchung** [comment]
please see https://github.com/yasp-dota/yasp/issues/1071
