### ISSUE TITLE
What happened to my 1000 matches on yasp ?

### ISSUE THREAD

**Issue by Idaret** [yasp-dota/yasp#1078]
https://yasp.co/players/198838397
http://www.dotabuff.com/players/198838397

**Comment by WTFKr0** [comment]
See #1071 

@howardchung : Maybe a message on yasp.co or blog for that ?

**Comment by howardchung** [comment]
@albertcui ?

I'm just hoping to get this resolved ASAP and not make a big deal out of it :(
