### ISSUE TITLE
about yasp game skill level

### ISSUE THREAD

**Issue by nt47** [yasp-dota/yasp#1082]
hi master,
Valve API cant get game skill level,but u get it.
can u help me get this info?

**Comment by nt47** [comment]
vh h n game
how can i check them ?

**Comment by coreymaher** [comment]
You can attempt to figure out the skill level by using the GetMatchHistory endpoint. You'll have to make a few requests with different combinations of hero ids and skill levels. See the documenation http://dev.dota2.com/showthread.php?t=47115

**Comment by nt47** [comment]
@coreymaher 
how about old matches ?
this way only can get latest match skill level, i want to get all

**Comment by coreymaher** [comment]
Unfortunately there is no way to get the skill level of old matches. You can't always get the skill level of new matches... Valve's APIs are weird
