### ISSUE TITLE
Adsense Compliance

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#1085]
> Hello,
> This is a warning message to alert you that there is action required to bring your AdSense account into compliance with our AdSense program policies. We’ve provided additional details below, along with the actions to be taken on your part.
> 
> Affected website: yasp.co
> 
> Example page where violation occurred: https://yasp.co/matches/2115574753
> 
> Action required: Please make changes immediately to your site to follow AdSense program policies.
> 
> Current account status: Active
> 
>  
> Violation explanation
> 
> 
> ​
> 
> Our program policies do not permit any alteration to AdSense code which artificially inflates ad performance or harms advertiser conversions. Your publisher account offers a number of options when generating the ad code, which we hope will allow you to create an ad layout that fits in with your site. It is also not allowed to place ads on mobile optimized sites so that they cover any part of the site content or implementing parts of a webpage to cover any portion of the ads. Please be aware that if you have a responsive website design that ads may shift into non compliant positions as the format of the screen changes.
> 
> In order to remain fully compliant please ensure that your site and ad layout remain compliant across all devices. For more information this policy can be found on our help center and this short video. 
> 
> 
> 
> How to resolve:
> If you received a notification in regard to page content, we request that you immediately remove Google ads from the violating pages. If you are unable to, or unsure of how to remove the ads from these pages, or would like to continue monetizing the page with Google ads, please modify or remove the violating content to meet our AdSense policies.
> If you received a notification in regards to the way ads are implemented on your site, please make the necessary changes to your implementation.
> You do not need to contact us if you make changes. Please be aware that if additional violations are accrued, ad serving may be disabled to the website listed above. You should immediately take time to review your pages with Google ads to ensure that they comply with our policies.
> 
> Additionally, please be aware that the URL above is just an example and that the same violations may exist on other pages of this website or other sites that you own. To reduce the likelihood of future warnings from us, we suggest that you review all your sites for compliance. Here are some useful resources you might be interested in.
> 
> AdSense policy FAQs
> Using site: search to find violations
> Recommended solutions for policing your content
> Content filtering
> For more information regarding our policy warning notifications, visit our Help Center.
> 
> We thank you in advance for your cooperation.
> 
> Sincerely,
> 
> The Google AdSense Team

Don't see any issues.... ?????

**Comment by howardchung** [comment]
No idea, you might want to contact Google and ask what the issue is.

**Comment by gu3st** [comment]
Could it be how the ads are being injected?

**Comment by dotacoach** [comment]
![yasp-ad-overlay](https://cloud.githubusercontent.com/assets/9014751/16737832/f819f978-4747-11e6-9b3e-4c8b458ef6ab.png)

Couldn't reproduce this every time, but might be a useful clue. Saw it twice when viewing match pages on "Mobile" device menu.

**Comment by howardchung** [comment]
is this still a problem?

**Comment by howardchung** [comment]
Haven't heard anything further about this.  Will reopen if still a problem (but we may drop adsense anyway)
