### ISSUE TITLE
Missing Large Number of Matches

### ISSUE THREAD

**Issue by matt46244** [yasp-dota/yasp#1089]
Hello,

Much like issue #1032 I seem to be missing a lot of my match history from Yasp. 

Dotabuff: http://www.dotabuff.com/players/52816
Yasp: https://yasp.co/players/52816

I haven't changed my privacy settings at any point but just noticed the discrepancy.

Is it possible to run it through the fullhistory script? Thank you!

**Comment by howardchung** [comment]
See #1071
