### ISSUE TITLE
Match Result Parsed Incorrectly

### ISSUE THREAD

**Issue by liboz** [yasp-dota/yasp#1094]
I think this one might be on the Dota API because dotabuff also screwed up, but https://yasp.co/matches/2452822169 shows that Dire won even though if you look up the game in the Dota 2 client, it was a Radiant Victory. Perhaps a reparse of certain data might be needed?

**Comment by Marvizm** [comment]
#1096 
https://www.reddit.com/r/DotA2/comments/4p6vjv/what_dotabuff/

**Comment by gu3st** [comment]
https://www.reddit.com/r/DotA2/comments/4p6vjv/what_dotabuff/d4ij2ro

I got a proper explanation from FletcherDunn as to what the change/error was.

**Comment by howardchung** [comment]
Requesting re-parse (which first gets API data) will fix it.  I'm also running a script to reload API data for the approximate affected range.
