### ISSUE TITLE
Win/Loss wrongly indicated

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [yasp-dota/yasp#1095]
**Match ID:** 2452908739
**Player ID:** 55723562

Match has been won by Dire. Player played on Dire side, but in the match list of the user, the match is marked as lost. The previous match of that player (2452833529) has actually been won by Radiant, but that might be due to the DotA patch that evening, so it's probably not related to this issue.

https://genes.pics/index.php/s/L7xIJdyFdRrIvTT#//list.PNG
https://genes.pics/index.php/s/L7xIJdyFdRrIvTT#//details.PNG

**Comment by Kaliumhexacyanoferrat** [comment]
Already been fixed, thanks for the great work :)

**Comment by howardchung** [comment]
I didn't actually do anything.  The Steam API was temporarily returning unexpected data, probably someone re-requested the match after it was fixed.
