### ISSUE TITLE
Stacks match tab

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#1099]
Originally proposed by @evaldobratti in https://github.com/yasp-dota/yasp/pull/1061

For a match, show players who have played multiple games with each other, estimating any stacks present in the game.

Caveats:
* Won't work for anonymous players (and roughly 60% of players are anonymous)
* This has the potential to be slow and we may want to make it a separate endpoint in order to avoid holding up match page loads.

**Comment by howardchung** [comment]
Possible approach:
* Looking at recent data only is probably sufficient, because this feature is generally only of interest in recent matches, and people playing with friends are likely to have done so recently.
* When a match is inserted, insert the pairs of each team (5c2 on each side, so 20 rows total).
* I believe stacked players are always contiguous?
* To compute the stacks in a match, for each player on a team, check the next player down and find the number of times that the pair appears in the pairs table.  If the number is more than some threshold, consider the players partied.
* Proceed down the list.
* Repeat with other team
* Occasionally truncate the pairs table to prevent unbounded growth

**Comment by Subzidion** [comment]
How does the "Peers" tab work? Just looking at your Steam friends? I feel like most stacks are, 9 times out of 10, the same people on your Peers list or "mutual peers" with someone on your peers list.

**Comment by howardchung** [comment]
The peers tab counts up everyone in your matches and returns anyone with more than 5 games together.  It typically takes a few hundred MS to run so might be slow to call it 10 times.

**Comment by howardchung** [comment]
merge with #1147 

Apparently this data is now available in replays, so we shouldn't have to guess.
