### ISSUE TITLE
Outdated external dependency in Dockerfile

### ISSUE THREAD

**Issue by Daerdemandt** [yasp-dota/yasp#1102]
Docker image fails to build:

    Step 3 : RUN ... wget "https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/andyshinn.rsa.pub" -O "/etc/apk/keys/andyshinn.rsa.pub" ...
    --2016-06-23 16:36:01--  https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/andyshinn.rsa.pub
    Resolving raw.githubusercontent.com... 151.101.36.133
    Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2016-06-23 16:36:02 ERROR 404: Not Found.

[Project](https://github.com/sgerrand/alpine-pkg-glibc) in question has [switched](https://github.com/sgerrand/alpine-pkg-glibc/commit/3db7b4c4729f8128df99c9007a56a8f0d1e65955) maintainer not so long ago, path to the key has changed too.

**Comment by howardchung** [comment]
I think I updated this already.  Pull latest?

**Comment by Daerdemandt** [comment]
Oops.
Yes, it works.
