### ISSUE TITLE
Requesting a little info

### ISSUE THREAD

**Issue by leovarmak** [yasp-dota/yasp#1105]
Hey Creators !

This is not an issue but I had a few doubts. If I initiate a private lobby and conduct a match between 2 teams just like in case of tournament, is there a possible way I can check out the winner of them using Yasp ?

Other thing was I can't directly contribute money so will it be ok if I can trade in-game items so maybe you can sell them ?

Regards,
Karthik.

**Comment by howardchung** [comment]
Not automatically.  You could upload the replay file, but that's manual and temporary.

**Comment by leovarmak** [comment]
Where can I get the reply file ?

**Comment by howardchung** [comment]
I'm not sure.  I think a player who participated in the lobby can download it.
