### ISSUE TITLE
public/build contents?

### ISSUE THREAD

**Issue by Vatyx** [yasp-dota/yasp#1113]
Hi, just trying to get yasp all set up locally. One thing I can't figure out is how to build all of the public files. I don't see any dependencies like gulp for the task management so what are you guys using to build those files?

Thanks

**Comment by howardchung** [comment]
public/build should be empty.  The index.html file in it is a leftover from when the React UI was still in this repo.  I've removed the file.

`npm run build` should take care of everything for you.

**Comment by Vatyx** [comment]
Because building public files is different from project to project, I would
list somewhere that the command is npm run build.

**Comment by howardchung** [comment]
If you are using Docker, the Quickstart should get you running.  If not, you can refer to the Dockerfile to see what it does and manually do it :)

**Comment by Vatyx** [comment]
I followed the Quickstart to the letter and when I tried to connect to my
own local instance, I was missing the CSS and JS because build was empty.
Once I ran npm run build it worked.

**Comment by howardchung** [comment]
Ahh, you're right.  I forgot that when you map your local directory into the container, it will cover the already built version in the Docker container.  Thanks, I'll add that step.

**Comment by howardchung** [comment]
I removed the step that locally builds the container as well.  Since it'll get covered by the local directory anyway, it's faster to just have Docker pull yasp/yasp:latest

**Comment by Vatyx** [comment]
Also I guess while I am able to ask you stuff. I am unable to pull in any
replays even though I have a steam account set up and the API key in the
.env file. Do you know what else it might be?

Also what is the scanner command you are referring to in the README?

**Comment by howardchung** [comment]
You may want to join us on Discord for live help (and more people there)

* Need more information.  Are you saying the retriever isn't working?
* Which scanner command?

**Comment by Vatyx** [comment]
Just joined!
