### ISSUE TITLE
Dire offlane camp counts as mid lane?

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#1115]
https://yasp.co/matches/2480407319/performances

I spent most of the laning stage stacking and farming the big camp and I was detected as being a mid (core).

**Comment by lomash** [comment]
https://yasp.co/matches/2479833804/performances

Same for radiant. A Mirana was cliff jungling this game.

**Comment by howardchung** [comment]
Adding these edge cases is kind of tricky.

Basically, the map is split into a 128x128 grid, and we have rules to detect which section a player is in the most.

https://github.com/yasp-dota/yasp/blob/master/constants.js#L113

So to add additional small sections we'd have to figure out the coordinates and add extra rules for them

**Comment by dracovich** [comment]
Are all laning positions hardcoded in? Or are they based off some kind of clustering?

I've been playing around with clustering off the position data, where i've used the mean position, and the average distance away from that mean position (that is, how close do they on average stay to their mean position). I haven't been able to come to any hard conclusions yet as to what the best method is, but i think i could come up with something if it's of interest.

Here you can see the data for the dire side:

http://i.imgur.com/GfkKVrX.gifv

where it's clustered into 4 gaussian clusters (the pink i just added on top manually, i was hoping to use the average distance from the mean to identify roamers).

This is from the old datadump though, so it doesn't have the "new" map changes that came later in December, but i'd imagine we could show that there as well. 

If nothing else, a simple k-means clustering could be done for the 4 positions, perhaps adding a fifth for the offlane camp? If we wanted we could add a hard rule on top that defines anyone above a certain avergae distance from their mean as a roamer (though it would be nice if i could figure out an actual clustering algorithm that could find this by itself).

**Comment by howardchung** [comment]
Each cell on the map (128x128) corresponds to one of five values: top, mid, bot, radiant jungle, and dire jungle.

We build a 128x128 array so we can quickly look up the corresponding region for any x/y coordinate pair.  In the per-match data, we store the number of seconds is at each position in the first 10 minutes.

We translate this data to the number of seconds the user was in each region, then take the mode and display that as the computed lane.

**Comment by howardchung** [comment]
Unless someone has a reliable way to keep "special" areas of the map updated I'm going to close this.  The map changes occasionally and the positions of small areas like neutral camps would likely shift as well.
