### ISSUE TITLE
Neutral stacking info

### ISSUE THREAD

**Issue by mintwzy** [yasp-dota/yasp#1117]
I notice in my Dota 2 personal profile, there is a value called `camps stacked`. Just wonder if there is a way to get this value for players in a match. Thanks.

**Comment by mintwzy** [comment]
I find there is a type named `DOTA_COMBATLOG_NEUTRAL_CAMP_STACK` in `DOTA_COMBATLOG_TYPES`, but it seems this type is never found when parsing the replay. Anyone has ideas on this?

**Comment by howardchung** [comment]
Yeah, I don't think this event type shows up in the replay.  Not much we can do unless Valve adds it.  I check periodically (after patches).

**Comment by howardchung** [comment]
merge with #712
