### ISSUE TITLE
cant use new API, my spider get error

### ISSUE THREAD

**Issue by nt47** [yasp-dota/yasp#1120]
dear master:
My spider will be  banned if i request too fast ?

like this:
{"error":"rate limit exceeded"}

**Comment by howardchung** [comment]
Yes there is a rate limit.  Run the code yourself if you need to make a high volume of requests.

**Comment by nt47** [comment]
oh  its a bad news.
but can u provide a pay service?
remove limited ?

**Comment by howardchung** [comment]
What kind of rate are you needing?

**Comment by nt47** [comment]
@howardchung 

i createthread*10 to  get playerinfo
everythread curl different uri(matches ?limit 5 and records etc.) once every 6 seconds

but i always get {"error":"rate limit exceeded"}

Concurrent event....

**Comment by howardchung** [comment]
We need a limit, otherwise a single user can negatively impact the experience for all other users.  Can you add a delay of 1 second between requests?

**Comment by nt47** [comment]
@howardchung 
i test if i get url  once every 1seconds
u still ban my ip

**Comment by howardchung** [comment]
Are you using only one thread?  Multiple threads will count multiple times.  The current implementation allows up to 5 requests, and resets after a "cooldown" of 1 second.

**Comment by nt47** [comment]
mutilple  threads----->my proxy server(it will be multiple as well?)----->ur server

**Comment by howardchung** [comment]
Do you need multiple threads?  What are you doing that requires a high rate of requests?

I may increase to around 8 or so in the future

**Comment by nt47** [comment]
in game stat panel.
need open panel get playerinfo with a high rate of requests
if u can make a cache, rate is not a problem
@howardchung

**Comment by howardchung** [comment]
I will increase it to 8

**Comment by nt47** [comment]
thx a lot
but, i think u can make a ip check cache
its more useful than rate limited
cuz i just repeatedly get the same 10 player at the moment
