### ISSUE TITLE
improve player search

### ISSUE THREAD

**Issue by leovarmak** [yasp-dota/yasp#1125]
Hey !

The search function is really bad. I don't mean to be rude tho. I respect you people. I tried to search my account in many ways and I always end up with **NOT FOUND** . Haha .
Well my game profile is "Amanda Rosset" . I did a series of queries to test it. Here are pics
![screen shot 2016-07-20 at 6 23 11 pm](https://cloud.githubusercontent.com/assets/14135553/16988869/8b13a760-4eaf-11e6-8dc1-3f967f685a27.png)

![screen shot 2016-07-20 at 6 23 21 pm](https://cloud.githubusercontent.com/assets/14135553/16988877/92077b64-4eaf-11e6-8a38-02d161962c66.png)

![screen shot 2016-07-20 at 6 23 32 pm](https://cloud.githubusercontent.com/assets/14135553/16988881/968c4da4-4eaf-11e6-8c5f-b5c90e648c38.png)

![screen shot 2016-07-20 at 6 23 46 pm](https://cloud.githubusercontent.com/assets/14135553/16988888/9a1eec24-4eaf-11e6-9098-daecf7d17dfe.png)

![screen shot 2016-07-20 at 6 23 53 pm](https://cloud.githubusercontent.com/assets/14135553/16988899/9fba52f4-4eaf-11e6-8245-32b174e5e597.png)

![screen shot 2016-07-20 at 6 24 09 pm](https://cloud.githubusercontent.com/assets/14135553/16988907/a4fc75bc-4eaf-11e6-9602-765a84754682.png)

But when I type in **rosset** my profile shows up

So whats wrong ?

**Comment by howardchung** [comment]
The search is a simple trigram match.  (pg_trgm)  Case doesn't matter.

https://www.postgresql.org/docs/9.1/static/pgtrgm.html

I am not sure how it handles spaces.  There might be ways to improve it, though.

**Comment by leovarmak** [comment]
@howardchung btw I was thinking of making an Windows Phone App for YASP. Will that be cool with you ? Or should I take some permissions ?

**Comment by howardchung** [comment]
Sure, you can talk to @Proyoyo who is working on react-native code for mobile apps.

I think windows phone is on the decline though

**Comment by Proyoyo** [comment]
@leovarmak Hey, you can check out the react-native project in YASP repo. Currently, I'm waiting for this: https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/

However, Windows phone support is not my main priority at the moment. Feel free to join us on Slack to discuss about this.

**Comment by howardchung** [comment]
Interestingly:
SELECT '%da ros%' ILIKE 'Amanda Rosset'

This apparently returns false.  I have no idea why.  @gortiz ?

**Comment by gortiz** [comment]
A small fix, you should change the order of the params ;)

SELECT '%da ros%' ILIKE 'Amanda Rosset' => SELECT 'Amanda Rosset' ILIKE
'%da ros%'

2016-07-21 4:54 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
Thanks!  Looks like it was correctly ordered in the query, just wrong in my test.

@leovarmak I found the problem, it looks like your name has two spaces in it:
```
        {
          "account_id": 334744963,
          "personaname": "Amanda  Rosset"
        },
```

In any case the new query does not rely on ILIKE so it should return the correct result regardless.  However you now need a minimum similarity of 0.3 to match, so search strings like "ama" or "ross" may not find you due to being too short.

**Comment by leovarmak** [comment]
I won't even find my profile up when I search **amanda rosset** ?

**Comment by howardchung** [comment]
You won't now because it doesn't match due to the extra space.  You should once the new code is deployed.

**Comment by leovarmak** [comment]
I till can't get my profile when I search **amanda rosset**. Do the spaces really matter ?

**Comment by howardchung** [comment]
It's not deployed yet

**Comment by howardchung** [comment]
https://yasp.co/search?q=amanda+rosset

deployed, works now

**Comment by leovarmak** [comment]
@howardchung Cool . Works fine !
