### ISSUE TITLE
explore long-running java parser process

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#1129]
Have a long-running java process (webserver) that reads replay as POST body and returns logs as response.

Might benefit from reduced JVM startups and hot path optimization.

http://stackoverflow.com/questions/3732109/simple-http-server-in-java-using-only-java-se-api

**Comment by spheenik** [comment]
interesting!

**Comment by howardchung** [comment]
Based on some quick testing this seems to cut parse time down by quite a bit.  I  tried adding a loop that parses the same replay 10 times and see 50% faster times from the second parse on.

**Comment by spheenik** [comment]
Yes, while "warming up", I see a lot of multi core activity (it's the JIT compiler at work, identifying hot methods and compiling them). When it's warm, this is not needed anymore.
