### ISSUE TITLE
hero win rate by mmr tier

### ISSUE THREAD

**Issue by jjYBdx4IL** [yasp-dota/yasp#1130]
is it possible to calculate that? would be nice to have so you can decide what heroes are actually good in *your* mmr tier, or, rather, to see if there are differences between the tiers.

**Comment by howardchung** [comment]
Dotabuff has a nice tool for this:

http://www.dotabuff.com/heroes/meta

It's also free (although they charge for some specific filters).  Let me know if it's missing some functionality you need
