### ISSUE TITLE
do you have android api to use?

### ISSUE THREAD

**Issue by doubliekill** [yasp-dota/yasp#1131]

**Comment by howardchung** [comment]
Not sure what you mean by android API

**Comment by howardchung** [comment]
I'm going to assume you mean an API that can be used by an android app.

In that case, yes, although it is not published yet and subject to change:
https://swagger.yasp.co/

You should also talk to @Proyoyo who is working on a react-native project to support automatically generated Android and iOS apps.

**Comment by doubliekill** [comment]
can't access now

**Comment by Proyoyo** [comment]
@doubliekill we moved all of our API docs to: http://docs.opendota.com/

**Comment by doubliekill** [comment]
thank you very much.
