### ISSUE TITLE
laning heatmap info

### ISSUE THREAD

**Issue by aeosynth** [yasp-dota/yasp#1140]
the laning heatmap, in the performances tab, sometimes shows solid red everywhere for some players. for example: https://yasp.co/matches/2533263509/performances

the veno, antimage, and spirit breaker are mostly solid red. what does this actually mean?

**Comment by howardchung** [comment]
The x/y coordinate with the highest number of hits is scaled to the brightest red.  If the number is the same for many cells (there were no "hot" spots), then all of them get scaled to the same color.

**Comment by aeosynth** [comment]
i think it would be more obvious if there were no scaling - a heatmap showing all blue makes it clear that nothing was hot

**Comment by howardchung** [comment]
I believe our original implementation did that, the problem is that it looks like nothing is showing since it's all very faint.

**Comment by aeosynth** [comment]
the colors and opacity can be configured: https://www.patrick-wied.at/static/heatmapjs/docs.html. setting opacity to 1 might fix the faintness

**Comment by howardchung** [comment]
We can try it, but settings that work well for one match might not work well for another.
