### ISSUE TITLE
show item timings in overview

### ISSUE THREAD

**Issue by aeosynth** [yasp-dota/yasp#1141]
feature parity w/ dotabuff

https://www.reddit.com/r/DotA2/comments/4uwxtr/dotabuff_now_includes_item_timings_for_all/

**Comment by howardchung** [comment]
This should be relatively easy if someone wants to submit a PR.

https://yasp.co/api/matches/2348057796

Each player has an array called first_purchase_time.  We just need to map the item ids to the names (constants.items) and then convert the value to minutes.

**Comment by aeosynth** [comment]
should the pr be to this repo or the ui repo?

**Comment by howardchung** [comment]
If you want it now, it can go here (jade template edit).

If you want it in the new UI (planned beta in September), then it needs to go there.

If you only want to do it once and can wait, do it only on the new UI.

**Comment by howardchung** [comment]
moved to new ui
