### ISSUE TITLE
Minutes dead in performance tab tooltip says seconds dead

### ISSUE THREAD

**Issue by WizardRubic** [yasp-dota/yasp#1143]
http://imgur.com/ZbNNlC7

Looks like the tooltip information is wrong.

Thanks for the site! 

Is it appropriate to report small typos like this here? If not, sorry!

**Comment by Subzidion** [comment]
Yep, this is the place. Thanks for the heads up.

**Comment by howardchung** [comment]
Fixed in dotaconstants
