### ISSUE TITLE
Last update resets benchmarks of all parsed matches

### ISSUE THREAD

**Issue by vik-borisov** [yasp-dota/yasp#1144]
For example, match id - 2534024616
![image](https://cloud.githubusercontent.com/assets/4207463/17285857/9fe35566-57ef-11e6-9142-33675aa8e0ee.png)

**Comment by howardchung** [comment]
This is due to the sequential match API from valve being broken.  New matches aren't being added, so the benchmark sets expire.

**Comment by howardchung** [comment]
set backupscanner to include the matches it finds in benchmarks.  This might take a few hours to recover, let me know if it's not fixed by tomorrow.
