### ISSUE TITLE
New Fantasy point categories

### ISSUE THREAD

**Issue by yuizy** [yasp-dota/yasp#1146]
It seems Valve updated the Fantasy Points system with new categories like Camps Stacked. For games before 20th of July some of the stats will always show up as 0.00 but for the last few days it seems to be working. You can see the fantasy points by hovering over a hero icon in "Fantasy Points" spectator tab. 

Can these be found in replay data / Dota API? If that's possible, you could find some additional stats by reverting the fantasy point formula for each category. Perhaps issue #1117  is worth checking again since something was clearly changed within the last week or so.

**Comment by yuizy** [comment]
By doing a bit of binary search I found that the extra categories work for games after 27th of July, which is when the Player Card / Fantasy League patch came.

**Comment by howardchung** [comment]
Checked the replays again, still don't see any new combat log types.
