### ISSUE TITLE
Party data

### ISSUE THREAD

**Issue by TrentBartlem** [yasp-dota/yasp#1147]
like [Dotabuff does](https://www.reddit.com/r/DotA2/comments/4vpfi0/dotabuff_now_shows_who_is_partied_with_who/)

**Comment by howardchung** [comment]
I suspect the data is available in the replay, but I haven't been able to find it yet :(

**Comment by eblis** [comment]
[Here](http://www.dotabuff.com/matches/2543709687)'s another match in case it might help

**Comment by KenBeanNet** [comment]
Howard, the data is in the SteamKit portion of the match.  You will find a PartyId.  Naturally, everyone is there own party, 0-9.  When two players play together, it will go Party 0, Party 0, Party 2.  (Mean that Player 1 and Player 2 are together).

**Comment by howardchung** [comment]
SteamKit portion?  Does that mean it's not in the replay (requires a GC request?)

**Comment by KenBeanNet** [comment]
You got it buddy.  PartyId is listed with the SteamKit.  If your requesting the ReplaySalt, then you can easily just store the party_id with it.

**Comment by howardchung** [comment]
Makes sense.  We need to make a GC request for any replay we parse anyway, so this should be relatively straightforward.  Thanks for the tip!  At least I learned a lot about entities after spending a few hours looking at them last night :)

**Comment by KenBeanNet** [comment]
I would suggest grabbing the Series_Id too, so you can implement tournaments easier in the future.  (DireTeamId, and RadiantTeamId as well).
