### ISSUE TITLE
Games longer than 60 minutes show inaccurately in the players' profile

### ISSUE THREAD

**Issue by riflex** [yasp-dota/yasp#1159]
As the title states, in my example the game lasted 1:50:58, which is parsed correctly by yasp on its' page [Match 2553341092](https://yasp.co/matches/2553341092), however on the players' match history it shows up as [110:58](https://yasp.co/players/114343436/matches).

**Comment by howardchung** [comment]
Not really a bug, but more of a preference thing.  110:58 is raw mm:ss, and is also what shows up in game.
