### ISSUE TITLE
skill build layout

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#1162]
The skill build layout currently looks terrible in my opinion. 

When none of the heroes reach higher levels, the numbers are all clumped out without any spacing. [Example](http://imgur.com/eqUEXLW)

Secondly, the scroll bar is annoying. The user should be able to see all the levels at a glance. The issue is that the buildings minimap is taking quite a lot of space. It should be moved either above or below this data, like on dotabuff

**Comment by howardchung** [comment]
I suggest opening this on the UI repo.

**Comment by lomash** [comment]
Done
