### ISSUE TITLE
Individual Match Data Dump Button

### ISSUE THREAD

**Issue by Danbardo** [yasp-dota/yasp#1163]
Hey guys,

I had no idea this existed until today, this completely trumps every other dota2 data website.

It's amazing...

The only thing that would help me and some other players is if we could extract individual match data? Rather than having to download those huge dumps.

Would it be possible to setup a button we could click that would spit out all the unprocessed data so we can save it as a CSV or whatever?

Thanks,

Daniel

**Comment by howardchung** [comment]
Just use the API:
https://yasp.co/api/matches/2348057796

Documentation:
https://swagger.yasp.co/

There used to be a button but we removed it because most users don't need it

**Comment by Danbardo** [comment]
awesome! thanks heaps!
