### ISSUE TITLE
Where does your Data come from?

### ISSUE THREAD

**Issue by peemoRoyal** [yasp-dota/yasp#1164]
Hi guys!

i really do love your site and I am working on a small clarity parser for a university project as well. So I know a bit about parsing replays now. I was just wondering how you guys do it with the replays and the data you display.
I know there is the match_histoy API where you can query things like the MMR and GPM values and all that neat stuff displayed in the client. 
But then you are able to provide something like the Ward-Heat-Map and the AllChat-Wordcloud (superfun, btw) which I know can only arise from a parsed replay data. 
So here is basically my question: Since I provided my Steam account and all that, do you download and parse every single match I played? Or does this Data come only from matches I actively parsed?
I hope the question is not inappropriate, but it would help me understand alot more for my thesis I am working on. 
Another question: Is there a way to help you guys out in some ways? I do some web dev and getting into all the parsing stuff for my university project and its alot of fun for me, so id be happy to if i could help you out in some ways...

Kind regards and thanks in advance
Peter

P.S: you can contact me here: gleixnerp@gmail.com

**Comment by howardchung** [comment]
* Tracking logic:
  * When a user logs in via Steam it returns an account ID that identifies the player.
  * When we find a match that has one of these players in it, we queue it for parse
  * To reduce load, if a player doesn't visit the site for 2 weeks, we remove them from the "active" list we consider when looking at new matches.

Contributions:
  * We love them!  This repo is more "data plane" (parsing replays, storing and querying data)
  * https://github.com/yasp-dota/ui is new React/Redux UI, which is currently being worked on

**Comment by peemoRoyal** [comment]
Awesome man! Thanks alot. Helps me out a bunch! Hope to be able to pay you back soon :)
