### ISSUE TITLE
MMR Glitch 

### ISSUE THREAD

**Issue by leovarmak** [yasp-dota/yasp#1170]
Hey !
My Solo MMR is actually 437 and Party MMR is 558. But on the site it is shown as N/A. Well as far as I remember it used to show up correctly before. 
So heres the details 

[Profile Page](https://yasp.co/players/170842607)

![screen shot 2016-08-08 at 3 44 38 pm](https://cloud.githubusercontent.com/assets/14135553/17654425/a1f7d288-62c0-11e6-8a77-0e35df402db6.png)

Btw I have another doubt too. For my other account the MMR prediction is 1835 and confidence level is 95% +/- 1554. So what would be my mmr be around ?

**Comment by howardchung** [comment]
Displaying MMR: Have you put your MMR in your profile and played a ranked game since?

Estimate: It appears that you're playing with friends who are significantly higher rated than you.  This can greatly affect the range of average MMR in your games, which makes the estimate less precise.

**Comment by leovarmak** [comment]
The MMR is not put on the profile. But it used to show MMR even before

**Comment by howardchung** [comment]
MMR is only available if you display it.  This has been true since last
September.
