### ISSUE TITLE
Historical salt and cluster data for ticketed matches.

### ISSUE THREAD

**Issue by lenpr** [yasp-dota/yasp#1177]
Currently, there is data for roughly 200 games (https://beta.yasp.co/explorer?id=1144). It would be amazing to be able to get more (match_id, cluster, salt). Solely for ticketed matches as they haven't expired.

**Comment by howardchung** [comment]
backfill in progress, going at about 1/sec so it'll take about 6 hours

**Comment by howardchung** [comment]
done!

**Comment by lenpr** [comment]
TY!!!
