### ISSUE TITLE
Parser optimization

### ISSUE THREAD

**Issue by spheenik** [yasp-dota/yasp#130]
Hi folks,

I promised on reddit that I'd have an idea to optimize the parser. So here goes:
Often times you do a repeated lookup of a property of an entity via it's name, for example

pr.getProperty("m_iLastHitCount" + "." + PLAYER_IDS[i])

Entities hold their state in an array. When you lookup via a string (name of the property), it has to find out the offset of the variable in that array. This, when done often, can be pretty time consuming, according to my tests. So what you can do (once) is:

int lastHitCountIdx = pr.getDtClass().getPropertyIndex("m_iLastHitCount" + "." + PLAYER_IDS[i]);

and in your loop, get the property value with

pr.getState()[lastHitCountIdx]

(I know this syntax sucks, gonna implement a getProperty(int) in V1.2)

Also, array properties like the last hit count always have adjacent indices (no holes in it), so, once you have the index for player 0, it's easy to get it for the next player by adding 1:

int lastHitCountBase = pr.getDtClass().getPropertyIndex("m_iLastHitCount.0000");

int countForFirstDirePlayer = (Integer)pr.getState()[lastHitCountBase + 5];

HTH, feel free to reply if there are questions,

Martin

**Comment by albertcui** [comment]
Awesome! Thanks for the help!

**Comment by howardc93** [comment]
Is this just a time optimization or will it help with memory as well?  We've noticed that when we run the parser without any -Xmx arguments to restrict heap size, the parser will use 400MB+.

**Comment by spheenik** [comment]
This only helps with runtime.

I've just tested, and I am able to run the parser with -Xmx20m for the combatlog example. So I suspect something JSON related in your parser is bloated or it's otherwise taking all the memory.

Also, when you do not restrict the JVM, it'll take a lot of memory, but it will not be required, it will just be garbage collected less agressive. So just restrict it, and it will garbage collect more often, to keep your requirements.

**Comment by howardc93** [comment]
We've changed to using the streaming interface.  Hopefully this reduces the memory requirement.  We'll get to the runtime improvement in the near future

**Comment by howardc93** [comment]
Made this change in dev branch.  Doesn't seem to improve runtime very much, but I think the code is a bit better now (we don't ahve to store an array of 0000, 0001...
