### ISSUE TITLE
Investigate issue with untracked message being incorrectly displayed

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#156]

**Comment by howardc93** [comment]
Rewrote code to determine when to display this.

Also might write a test for this case.

**Comment by howardc93** [comment]
As of now, the message just never displays.  We'll think about how we want to implement this, maybe as simple as a FAQ.

**Comment by howardc93** [comment]
We should really just have a FAQ/About section :)

**Comment by howardc93** [comment]
No longer using an untracked message.
