### ISSUE TITLE
Map on the match page doesn't update

### ISSUE THREAD

**Issue by ofsaleem** [yasp-dota/yasp#160]
Even after the replay being parsed, the map with the buildings on it at the bottom of the match page always shows all buildings standing.

**Comment by howardc93** [comment]
They should be grayscaled. Do you have an example?

**Comment by ofsaleem** [comment]
Sure

http://yasp.co/matches/1183830515

http://yasp.co/matches/1181581706

http://yasp.co/matches/1181357566

http://yasp.co/matches/1179281348

http://yasp.co/matches/1183870496

four personal matches and the last one is a random (parsed) one I picked from the matches list

**Comment by ofsaleem** [comment]
Oh wait, I see the issue. I checked in Chrome, and they are grayscaled. But I use Firefox, and they're in full color.

**Comment by howardc93** [comment]
Probably just need to add some more CSS styles, since they differ between browsers.

**Comment by howardc93** [comment]
Replaced opacity with grayscale.
