### ISSUE TITLE
implement method to allow users to request full history

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#176]
We can probably start doing this slowly.  Could be as simple as a button to press, and we set the full_history to 1.

Then we can run our full history task one user at a time, doing a few a day?

**Comment by howardc93** [comment]
We need to add a delay so only users who have been with us for a week are able to do this.  This should prevent heavy load from users who look at the site once and never come back.

**Comment by Geczy** [comment]
Was the delay added? I requested my history 3 days ago and nothing :cry:

**Comment by howardc93** [comment]
I found a bug with the full history code in production.  I've fixed it in dev branch, but @albertcui is out of town until Monday, so we'll merge and redeploy then and we can get started on the queue.  

Right now we have about 150 people and we can do about 12 a day, so it might take a while to get through everyone.
