### ISSUE TITLE
Replay upload always fails with "Recaptcha failed"

### ISSUE THREAD

**Issue by VonL** [yasp-dota/yasp#198]
As title says, replay upload always fails with Recaptcha failed. The recaptcha is correct, the request takes a long time to perform (file gets uploaded), but the request always returns with the error page.

**Comment by howardc93** [comment]
Thanks for reporting.  I'm taking a look at it now.

**Comment by howardc93** [comment]
Looks like this is just a UI issue, the replay appears to be uploaded and parsed even though the page doesn't report it correctly.  Can you confirm if replays you've uploaded have been parsed or not?
