### ISSUE TITLE
Add rune/ward spawn/placement and usage info

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#23]

**Comment by howardc93** [comment]
http://wiki.zynox.net/Network_Information

Wards:
DT_DOTA_Item_ObserverWard
DT_DOTA_Item_SentryWard
 DT_DOTA_NPC_Observer_Ward
DT_DOTA_NPC_Observer_Ward_TrueSight

Possibly the first two are inventory entities and the second two are actual placed entities?

**Comment by howardc93** [comment]
Rjackson's Python code for wards:

<pre>
<code>
wards_seen = []
r_ward_positions = []
d_ward_positions = []
for tick, string_tables, world in demo.stream(tick=5000):
  ward_dt = 'DT_DOTA_NPC_Observer_Ward'
  obs_ward = world.find_all_by_dt(ward_dt)

  if obs_ward:
    for ehandle, state in obs_ward.items():
      index, _ = _world.from_ehandle(ehandle)
      if index not in wards_seen:
          wards_seen.append(index)

          team = state[('DT_BaseEntity', 'm_iTeamNum')]
          cellX = state[('DT_DOTA_BaseNPC', 'm_cellX')] + state[('DT_DOTA_BaseNPC', 'm_vecOrigin')][0] / 128.0
          cellY = state[('DT_DOTA_BaseNPC', 'm_cellY')] + state[('DT_DOTA_BaseNPC', 'm_vecOrigin')][1] / 128.0

          pos = (cellX, cellY)

          if team == 2:
              r_ward_positions.append(pos)
          elif team == 3:
              d_ward_positions.append(pos)
</code>
</pre>

**Comment by howardc93** [comment]
Wards:
We can heatmap ward placements per team?
Should we do both sentries and observers or just observers?

Runes:
We can display how many runes of each type each player activated?
We can get data for how many runes of each type spawned, but not sure if it's worth the additional parse time.

**Comment by howardc93** [comment]
have the data now, just need to put in template:
runes activated/bottled
obs/sen placement heatmaps for each player
