### ISSUE TITLE
Get hero information over time

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#24]
This code snippet will get hero information at the current time in the match. As far as I can tell, if m_hReplicatingOtherHeroModel equals that constant, it's an illusion.
```java
        import com.google.common.base.Predicate;

        Predicate<Entity> isHeroDT = new Predicate<Entity>() {
            @Override public boolean apply(Entity e) {
                return e.getDtClass().getDtName().indexOf("DT_DOTA_Unit_Hero") == 0;
            }
        };

       Iterator<Entity> heroes = match.getEntities().getAllByPredicate(isHeroDT);

       while(heroes.hasNext()) {
            //Does this work for all matches?
            int num = heroes.next().getProperty("m_hReplicatingOtherHeroModel");
            //IS THIS A CONSTANT?
            if(num == 2097151){
                  count++;
            }
       }
```

Info returned from each entity:

-- Entity [index=1316, serial=224, dtClass=DT_DOTA_Unit_Hero_Broodmother]
m_vecOrigin = (22.0, 29.0)
m_angRotation[1] = 98.43751
m_cellX = 177
m_cellY = 107
m_iHealth = 651
m_vecOrigin[2] = 0.0
m_cellZ = 130
m_cellbits = 7
m_nNewSequenceParity = 1
m_nResetEventsParity = 1
m_nMuzzleFlashParity = 0
m_flMana = 161.01965
m_nUnitState = 50331648
m_iTaggedAsVisibleByTeam = 26
m_anglediff = 0
m_fFlags = 0
m_NetworkActivity = 422
m_NetworkSequenceIndex = 2
m_nTotalDamageTaken = 0
m_iCurrentXP = 2321
bcc_localdata.m_hMyWeapons.0016 = 2097151
bcc_localdata.m_hMyWeapons.0017 = 2097151
bcc_localdata.m_hMyWeapons.0018 = 2097151
bcc_localdata.m_hMyWeapons.0019 = 2097151
bcc_localdata.m_hMyWeapons.0020 = 2097151
bcc_localdata.m_hMyWeapons.0021 = 2097151
bcc_localdata.m_hMyWeapons.0022 = 2097151
bcc_localdata.m_hMyWeapons.0023 = 2097151
bcc_localdata.m_hMyWeapons.0024 = 2097151
bcc_localdata.m_hMyWeapons.0025 = 2097151
bcc_localdata.m_hMyWeapons.0026 = 2097151
bcc_localdata.m_hMyWeapons.0027 = 2097151
bcc_localdata.m_hMyWeapons.0028 = 2097151
bcc_localdata.m_hMyWeapons.0029 = 2097151
bcc_localdata.m_hMyWeapons.0030 = 2097151
bcc_localdata.m_hMyWeapons.0031 = 2097151
bcc_localdata.m_hMyWeapons.0032 = 2097151
bcc_localdata.m_hMyWeapons.0033 = 2097151
bcc_localdata.m_hMyWeapons.0034 = 2097151
bcc_localdata.m_hMyWeapons.0035 = 2097151
bcc_localdata.m_hMyWeapons.0036 = 2097151
bcc_localdata.m_hMyWeapons.0037 = 2097151
bcc_localdata.m_hMyWeapons.0038 = 2097151
bcc_localdata.m_hMyWeapons.0039 = 2097151
bcc_localdata.m_hMyWeapons.0040 = 2097151
bcc_localdata.m_hMyWeapons.0041 = 2097151
bcc_localdata.m_hMyWeapons.0042 = 2097151
bcc_localdata.m_hMyWeapons.0043 = 2097151
bcc_localdata.m_hMyWeapons.0044 = 2097151
bcc_localdata.m_hMyWeapons.0045 = 2097151
bcc_localdata.m_hMyWeapons.0046 = 2097151
bcc_localdata.m_hMyWeapons.0047 = 2097151
bcc_localdata.m_flNextAttack = 0.0
m_hAbilities.0000 = 1795362
m_hAbilities.0001 = 845089
m_hAbilities.0002 = 445728
m_hAbilities.0003 = 1965343
m_hAbilities.0004 = 1543454
m_hAbilities.0005 = 2097151
m_hAbilities.0006 = 2097151
m_hAbilities.0007 = 2097151
m_hAbilities.0008 = 2097151
m_hAbilities.0009 = 2097151
m_hAbilities.0010 = 2097151
m_hAbilities.0011 = 2097151
m_hAbilities.0012 = 2097151
m_hAbilities.0013 = 2097151
m_hAbilities.0014 = 2097151
m_hAbilities.0015 = 2097151
m_ModifierManager.m_hModifierParent = 460068
m_Inventory.m_hItems.0000 = 121821
m_Inventory.m_hItems.0001 = 1025149
m_Inventory.m_hItems.0002 = 2097151
m_Inventory.m_hItems.0003 = 1049602
m_Inventory.m_hItems.0004 = 2097151
m_Inventory.m_hItems.0005 = 2097151
m_Inventory.m_hItems.0006 = 2097151
m_Inventory.m_hItems.0007 = 2097151
m_Inventory.m_hItems.0008 = 2097151
m_Inventory.m_hItems.0009 = 2097151
m_Inventory.m_hItems.0010 = 2097151
m_Inventory.m_hItems.0011 = 2097151
m_Inventory.m_hItems.0012 = 2097151
m_Inventory.m_hItems.0013 = 2097151
m_Inventory.m_iParity = 12
m_Inventory.m_hInventoryParent = 460068
m_Inventory.m_bStashEnabled = 1
m_Inventory.m_hTransientCastItem = 2097151
m_hMyWearables.lengthproxy.lengthprop20 = 4
m_hMyWearables.0000 = 1826074
m_hMyWearables.0001 = 1260827
m_hMyWearables.0002 = 703772
m_hMyWearables.0003 = 658717
m_hMyWearables.0004 = 0
m_hMyWearables.0005 = 0
m_hMyWearables.0006 = 0
m_hMyWearables.0007 = 0
m_hMyWearables.0008 = 0
m_hMyWearables.0009 = 0
m_hMyWearables.0010 = 0
m_hMyWearables.0011 = 0
m_hMyWearables.0012 = 0
m_hMyWearables.0013 = 0
m_hMyWearables.0014 = 0
m_hMyWearables.0015 = 0
m_hMyWearables.0016 = 0
m_hMyWearables.0017 = 0
m_hMyWearables.0018 = 0
m_hMyWearables.0019 = 0
m_flCreateTime = 0.0
m_ubInterpolationFrame = 1
bcc_localdata.m_hMyWeapons.0003 = 2097151
m_nModelIndex = 312
m_nRenderFX = 0
m_nRenderMode = 0
m_fEffects = 16
m_clrRender = -1
m_iTeamNum = 3
m_CollisionGroup = 9
m_flElasticity = 1.0
m_flShadowCastDistance = 0.0
m_hOwnerEntity = 1599490
m_hEffectEntity = 2097151
moveparent = 2097151
m_iParentAttachment = 0
m_iName = 
movetype = 0
movecollide = 0
m_iTextureFrameIndex = 0
m_bSimulatedEveryTick = 1
m_bAnimatedEveryTick = 0
m_bAlternateSorting = 0
m_fadeMinDist = 0.0
m_fadeMaxDist = 0.0
m_flFadeScale = 1.0
m_nMinCPULevel = 0
m_nMaxCPULevel = 0
m_nMinGPULevel = 0
m_nMaxGPULevel = 0
m_nSkin = 0
m_nBody = 0
m_flModelScale = 0.93
m_flPlaybackRate = 1.4404297
m_bClientSideAnimation = 1
m_bClientSideFrameReset = 0
m_bClientSideRagdoll = 0
bcc_localdata.m_hMyWeapons.0004 = 2097151
bcc_localdata.m_hMyWeapons.0005 = 2097151
bcc_localdata.m_hMyWeapons.0006 = 2097151
m_hLightingOrigin = 2097151
m_flFrozen = 0.0
m_hActiveWeapon = 2097151
m_iCurrentLevel = 6
m_iCustomXPValue = 0
m_iIsControllableByPlayer = 128
m_bIsPhantom = 0
m_bIsAncient = 0
m_bStolenScepter = 0
m_bIsNeutralUnitType = 0
m_bIsSummoned = 0
m_bCanBeDominated = 1
m_bHasUpgradeableAbilities = 0
bcc_localdata.m_hMyWeapons.0000 = 2097151
m_flHealthThinkRegen = 8.253967
m_iMaxHealth = 701
m_iAttackCapabilities = 1
m_iDayTimeVisionRange = 1800
m_iNightTimeVisionRange = 800
bcc_localdata.m_hMyWeapons.0007 = 2097151
m_flMaxMana = 364.04443
m_flManaThinkRegen = 2.3809547
m_iUnitNameIndex = 61
m_iDamageMin = 55
m_iDamageMax = 61
m_iDamageBonus = 6
m_lifeState = 0
bcc_localdata.m_hMyWeapons.0008 = 2097151
bcc_localdata.m_hMyWeapons.0009 = 2097151
m_iCurShop = 6
bcc_localdata.m_hMyWeapons.0010 = 2097151
bcc_localdata.m_hMyWeapons.0011 = 2097151
m_Collision.m_nSolidType = 2
bcc_localdata.m_hMyWeapons.0001 = 2097151
m_Collision.m_nSurroundType = 0
m_Collision.m_triggerBloat = 0
bcc_localdata.m_hMyWeapons.0002 = 2097151
m_angRotation[0] = 0.70588684
m_Collision.m_usSolidFlags = 16
bcc_localdata.m_hMyWeapons.0012 = 2097151
bcc_localdata.m_hMyWeapons.0013 = 2097151
m_iBotDebugData = 0
m_bShouldDoFlyHeightVisual = 1
bcc_localdata.m_hMyWeapons.0014 = 2097151
bcc_localdata.m_hMyWeapons.0015 = 2097151
m_flRespawnTime = 0.0
m_flRespawnTimePenalty = 0.0
m_iAbilityPoints = 0
m_flStrength = 29.5
m_flAgility = 29.000004
m_flIntellect = 28.0
m_flStrengthTotal = 29.5
m_flAgilityTotal = 29.000004
m_flIntellectTotal = 28.0
m_iRecentDamage = 0
m_iPlayerID = 7
m_bReincarnating = 0
m_flSpawnedAt = 140.23433
m_hReplicatingOtherHeroModel = 2097151
m_hEconConsumableAbility = 2097151
m_bCustomKillEffect = 0

**Comment by howardc93** [comment]
Closing this issue, open a new one if we have more specific data we want to extract from hero entities.  Doesn't seem like there's much else besides position that we're interested in.
