### ISSUE TITLE
MMR-graphs appear to be improperly drawn

### ISSUE THREAD

**Issue by VonL** [yasp-dota/yasp#241]
The curves appear to be off (twisting in every which way), see picture: https://i.imgur.com/LcPhhBJ.png

Using Firefox 35.0.1 on Windows 7

**Comment by howardc93** [comment]
Thanks for the report, I've been using a small made-up set of test data that doesn't exhibit this problem.

I've implemented a possible fix (specifying line type per data series instead of per chart), let me know if it fixes the problem (once it's in production).

If it doesn't I'll just switch to using straight lines.

**Comment by howardc93** [comment]
deployed to production.  let me know if the issue is resolved or still persisting.

**Comment by VonL** [comment]
It appears to be persisting with the same dataset, I'll get back when I've played a game to alter the dataset.

**Comment by VonL** [comment]
Three games and four hours later the graph has not updated, this may or may not be an unrelated problem.

**Comment by howardc93** [comment]
I've deployed a change that uses straight lines instead of curved.  Is the
line problem fixed now?

Regarding not updating, there appears to be a limit on the number of
profiles a single account can request per day.  We may have to manually
unfriend some people from the tracker account.

**Comment by VonL** [comment]
Yes, this solves the problem completely. The graph now looks sane.

Regarding the request limit, seeing as I have not received updates in ~24h, do I remove the tracker from friends and re-apply the tracker or is action necessary on your part?

**Comment by howardc93** [comment]
That's probably best.  I changed the tracker selection algorithm to shuffle
those with 150+ friends to the back, so when you remove and re-add you
should get a new one.  It'd help us balance the load a bit.

**Comment by VonL** [comment]
Allright, the graph updates properly now. The dates under the data points are still overlapping, however.

**Comment by howardc93** [comment]
I've implemented evenly spaced x-ticks in the dev branch.
