### ISSUE TITLE
Order ToolTip on graphs based on graph values

### ISSUE THREAD

**Issue by Brian-McG** [yasp-dota/yasp#255]
I would like to implement a change so that the tooltip is sorted based on the graph values so instead of this:
![Proposed Change](http://i.imgur.com/8ME38SA.jpg)
we then order it so that the hero ordering matches the graph (I.E. in this example sniper would be first in tooltip)

I don't mind having a look at it if you can point me to where you do it currently.

**Comment by howardc93** [comment]
This would probably have to be done in c3:
https://github.com/masayuki0812/c3

The developer is super responsive, and might be able to help you out.

**Comment by howardc93** [comment]
The charts are generated here:
https://github.com/yasp-dota/yasp/blob/master/public/js/charts.js

You could maybe override the c3 type to modify the tooltip generating function.

**Comment by howardc93** [comment]
Figured it out!
```
            tooltip: {
                contents: function(d, defaultTitleFormat, defaultValueFormat, color) {
                    d.sort(function(a,b){return b.value-a.value});
                    return this.getTooltipContent(d, defaultTitleFormat, defaultValueFormat,color);
                }
            }
```

We'll push this out with our v1.5 release, but that make take a while since we made some huge changes.

**Comment by Brian-McG** [comment]
Nice :thumbsup:
