### ISSUE TITLE
Name updates not getting through

### ISSUE THREAD

**Issue by VonL** [yasp-dota/yasp#268]
As title says: I updated my name 18 days ago (which was picked up correctly by yasp), and then reupdated it 17 days ago, which has not been picked up since.

**Comment by howardc93** [comment]
At the moment we update 100 names every 7 minutes, and have about 800,000 users, so a name will get updated every 38 days on average.  Probably we should be giving priority to YASP users, but this isn't a high-priority issue.  If you'd like to fix it you can submit a PR, or I will probably eventually fix it.

**Comment by howardc93** [comment]
The priority needs to go something like:
1) People without names (users in new matches added)
2) YASP users
3) everyone else

This should further be sorted by recency of last name update.

I don't think this is possible without some kind of custom comparator.  At the moment, we're just using a mongo sort option, which leverages the index we have on full_history_time.  Closing issue, but PR that fixes it (and isn't too hacky) is welcome.

**Comment by VonL** [comment]
A month later and a name update still has not occurred. There must be a bug somewhere here.

**Comment by howardc93** [comment]
The number of players has grown, so the delay has increased appropriately.  I've increased the check interval to every 30 seconds in dev branch, and also added the ability to force an update by relogging.  That deployment should be going out in . . . two weeks or so?

Until then, is there an urgent reason you need your name updated?

**Comment by VonL** [comment]
Mostly just the embarrasment of having (muted) displayed after my name when checking stats. It's not urgent, I mostly just try to help out as much as I can.

**Comment by howardc93** [comment]
I checked the number of players without names a couple days ago and it was about 970,000 named players out of 1.5 million or so, so there are still 600,000 players without names that need to be added first before we cycle back to updating others.
