### ISSUE TITLE
New font harder to read?

### ISSUE THREAD

**Issue by Brian-McG** [yasp-dota/yasp#282]
(Just my opinion) I find the serif font harder to read than the sans serif font.
What about Serif font for headings and sans serif for body?

**Comment by howardc93** [comment]
Albert is in charge of design

**Comment by howardc93** [comment]
Albert thinks the current design is fine, if you'd like to point out specific examples of legibility issues we'll take a further look.

**Comment by howardc93** [comment]
Got another complaint on reddit, reopening for albert

**Comment by howardc93** [comment]
using sans-serif for body

**Comment by Brian-McG** [comment]
Much better :+1:
