### ISSUE TITLE
Carries of the Month

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#284]
Use redis. Use sorted set with member as user id.

EXPIREAT m().startOf('month').add(1, 'month').unix()

cheese_goal should also use EXPIREAT

How should we detect when to add expire on key? ZINCRBY will create the key, but unlike with INCRBY, we can't easily detect if it the key was just added by looking at the return.

**Comment by howardc93** [comment]
Is this just part of the sandbox issue (i.e., the only reason you're doing this is to track sandbox-eligible players?)

**Comment by howardc93** [comment]
It's possible to expire members of a set using http://redis.io/commands/ZREMRANGEBYSCORE.

It's much simpler though to just use one key per user.

**Comment by howardchung** [comment]
Closing this since we're not doing anything with it.  Reopen if we decide we need it for something (although we'd probably just start a new issue ).
