### ISSUE TITLE
Create sandbox server for testing and for Cheese buyers

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#289]
This server will run develop.

Cheese buyers each month will have access to it.

I'm thinking dedicated retriever too.

I think we either save the replays so we can give these users access to the new stats when the code is merged into master.

**Comment by albertcui** [comment]
Apparently you can just pipe to two streams, so one can pipe to parser, one can pipe to file:

```
var fs  = require('fs');

var rs1 = fs.createReadStream ('input1.txt');                      
var ws1 = fs.createWriteStream('output1.txt');     
var ws2 = fs.createWriteStream('output2.txt');

rs1.pipe(ws1);
rs1.pipe(ws2);
```
http://stackoverflow.com/questions/17957525/multiple-consumption-of-single-stream

**Comment by albertcui** [comment]
So this will be if env = "sandbox"

**Comment by howardc93** [comment]
My opinion:

The test server should strictly be for testing.  Users shouldn't expect to keep those stats.  Honestly, we dont even need to restrict it to cheese buyers.  The idea is just that we have a decently sized user base, but not as big as production.  I agree dedicated retriever, and preferably we keep it to less than 500 per day so we can run the retriever locally.  Basically we'd just spin up dev on that box and watch it for a while before deploying to production.

**Comment by howardc93** [comment]
This means we really don't need to add any code, just assign some accounts for the sandbox, pick some users to add to it (maybe we can do all cheese buyers automatically or something), disable untracking, and spin up dev.

**Comment by howardchung** [comment]
I really don't think this is neccessary.  We tend to develop new features and then have them pushed out to production within a week or so.

If we grow to the point where we want to make sure we test things out in a limited environment first, we can just fire up a second server that's running another copy of the code, and just let anyone use it who wants to.  Restricting it to donators just makes it less likely for us to find bugs.
