### ISSUE TITLE
Incorrect gold information in buyback graph

### ISSUE THREAD

**Issue by alexeykovp** [yasp-dota/yasp#292]
All details are here:

![screenshot-yasp co 2015-03-03 22-14-06](https://cloud.githubusercontent.com/assets/11300577/6470231/24b01674-c1f3-11e4-802b-3183017d0c3c.png)
http://yasp.co/matches/1291069956/details

**Comment by howardc93** [comment]
This appears to just be a erroneous value from the combat log.

Here are the relevant entries:
```
{"time":1174,"type":"gold_reasons","unit":"npc_dota_hero_earth_spirit","key":"2","value":-7}
{"time":1174,"type":"buyback_log","slot":2}
```
