### ISSUE TITLE
Display tower falls timing

### ISSUE THREAD

**Issue by gibc2003** [yasp-dota/yasp#297]
Hi, in some games I would like to know when some structure was taken, however I can't find this information anywhere. Maybe display the destruction time on the minimap when hovering a fallen structure ?

**Comment by howardc93** [comment]
Theoretically possible I guess.  We can map a string to a time when the combat log reports it was killed.

Since towers cant have illusions and can't come back, we can just check this map for a particular tower's death time, like "npc_dota_badguys_tower1_mid".

Alternatively we could just log all these events, but then we'd have to build a hash to lookup when a particular tower was killed.

**Comment by howardc93** [comment]
I think I like the logging approach better.  We are already logging some kill events (hero on hero), this would just be a matter of adding another case where the kill is logged

**Comment by howardc93** [comment]
Would it be sufficient to just display tower kills in the timelines?  I think this is easier.

**Comment by howardc93** [comment]
We do need to find dire/radiant tower images, though.  Also preferably rax, roshan, and ancient.

**Comment by howardc93** [comment]
npc_dota_goodguys_fort
npc_dota_goodguys_melee_rax_bot
npc_dota_goodguys_melee_rax_mid
npc_dota_goodguys_melee_rax_top
npc_dota_goodguys_range_rax_bot
npc_dota_goodguys_range_rax_mid
npc_dota_goodguys_range_rax_top
npc_dota_goodguys_tower1_bot
npc_dota_goodguys_tower1_mid
npc_dota_goodguys_tower1_top
npc_dota_goodguys_tower2_bot
npc_dota_goodguys_tower2_mid
npc_dota_goodguys_tower2_top
npc_dota_goodguys_tower3_bot
npc_dota_goodguys_tower3_mid
npc_dota_goodguys_tower3_top
npc_dota_goodguys_tower4
npc_dota_badguys_fort
npc_dota_badguys_melee_rax_bot
npc_dota_badguys_melee_rax_mid
npc_dota_badguys_melee_rax_top
npc_dota_badguys_range_rax_bot
npc_dota_badguys_range_rax_mid
npc_dota_badguys_range_rax_top
npc_dota_badguys_tower1_bot
npc_dota_badguys_tower1_mid
npc_dota_badguys_tower1_top
npc_dota_badguys_tower2_bot
npc_dota_badguys_tower2_mid
npc_dota_badguys_tower2_top
npc_dota_badguys_tower3_bot
npc_dota_badguys_tower3_mid
npc_dota_badguys_tower3_top
npc_dota_badguys_tower4

**Comment by Brian-McG** [comment]
Do you plan on putting it as a timeline or as a similar image as the "positions" tab where hovering over each region reveals the info?

**Comment by howardc93** [comment]
At this point, I'm just trying to add them to the kill log in timelines, but for that we need a good tower picture.

**Comment by gibc2003** [comment]
I guess you could use a rook/king chess piece for towers/ancient, and a sword/bow icon for melee/ranged rax.

**Comment by howardc93** [comment]
If you can find some images provide us a link and we can integrate them if they look okay.  I'd prefer to be able to get something that stylistically resembles the Dota hero portraits.

**Comment by howardc93** [comment]
Clearing assignment until someone can find pictures. . . albert suggested trying the icons we're using the on the minimap, but I don't really like that.

**Comment by howardc93** [comment]
In v3.0.0 (v7 parsed data), I am putting tower, barracks, roshan, and ancient kills into a separate array.  Even if we don't get images we can still display text, and enhance it later.
