### ISSUE TITLE
skill brackets

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#299]
Probably not gonna be done, but I'll just document here:

Steam API only allows querying for skill on one API:
https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001/?key=XXXXX&start_at_match_id=1299599890&skill=3

The values for skill are 
skill=<skill>                  # 0 for any, 1 for normal, 2 for high, 3 for very high skill (default is 0)

The matches are in descending order by match_id.

However, only the first 500 results can be returned.  Since the output is sorted by match_id but matches don't show up in the API until completion, the sample is unfairly weighted toward shorter matches.

Implementation:
Essentially, we'd have to run a background job that queries the 500 available matches for each skill level 1, 2, 3.  For each match, we have to check our DB to see if we can fill in skill data.  It's not a very fun implementation.

**Comment by howardc93** [comment]
We will likely need to "guess" the skill bracket for a significant portion of matches using factors such as MMR/GPM.

**Comment by howardc93** [comment]
@albertcui has a friend interested in machine learning who might want to take a look at this?

**Comment by howardc93** [comment]
I will implement a basic skill-checker.  It could run as part of worker or as a standalone script.  I suppose we can test what percentage of matches we can end up getting skill data for.

**Comment by albertcui** [comment]
Yes, we'd need this data anyway to build a classifier.

**Comment by howardc93** [comment]
so for now I think I will just gather skill data for every match I can.  We can compare it to the full match volume to see what % of matches we can get skill data for.
