### ISSUE TITLE
parallelize sequential api

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#300]
This might help us avoid falling behind so much when the Steam API slows down.  I don't know if it's necessary, but I'm outlining an implementation here.

OLD design:
* ~~Code that is polling the sequential API should be refactored into a separate worker file (scanner.js) which can be distributed.~~ Done
* ~~When a match to add is detected, we queue a new job type called "insert", which YASP core's worker.js is processing.~~
* When we make a API request, we save in redis the sequence number we started at.  We can assume that the next 100 numbers will be processed.  What if we're at the leading edge and there are <100 matches though?  We could keep retrying the same seq_num until we get 100 matches.
* On each sequential api request, we take the current progress in redis and add 100 (the minimum number of sequence numbers so we are guaranteed not to miss any matches) to get the number we want to start at, then make the API request.  Once a request is made, we need to update redis to tell subsequent requests to start at a higher number.  We may need two vars, one to track what matches we've actually added, and one to track the number we should start at.
* ~~The API scan code currently uses local variables trackedPlayers and ratingPlayers to determine matches we need to request MMR/get replay on.  We would need to access redis for these variables to allow shared state between multiple hosts.~~ (fixed)
* It is possible for us to get matches in duplicate (and quite likely).  In this case, since we only have a single thread inserting, we should detect that we already have a replay url and not re-retrieve it.  We will still insert/update the db data, however.

NEW design:
- [x] start at match_seq_num, make multiple calls to steam API at sequence number n, n+100, n+200...
- [x] duplicates already handled  by storing recently seen match_ids in redis
- [x] if less than 100 matches, redo the page
- [x] for any single call, the next_seq_num should be current num + num_workers*100 + 1
- [ ] the trailing worker (ID 0) should update match_seq_num in redis

**Comment by howardc93** [comment]
With our proxying I don't think we need to do this anymore.

**Comment by howardchung** [comment]
Steam API has been really bad lately (15+ sec for a response).

Might need to look into implementing this.
