### ISSUE TITLE
Juggs doesn't get credit for healing with Healing Ward

### ISSUE THREAD

**Issue by evaryont** [yasp-dota/yasp#304]
Dunno where exactly to file an issue, hope you don't mind.

In [match 1318351122](http://yasp.co/matches/1318351122), Juggernaut has no hero healing though he did use Healing Ward. I expect that it's because the ward itself is mentioned as the source of the healing as it's a separate entity.

And for future reference, where should I mention these various edge cases with the parsing?

**Comment by evaryont** [comment]
Dotabuff also has a similar bug. [Here's the same match.](http://www.dotabuff.com/matches/1318351122)

**Comment by howardc93** [comment]
Data on the "Basic" tab comes straight from the WebAPI, so this isn't a bug with the parsing as much as it is with how Valve gets its numbers.

We can attempt to refine these values and break them down (by healing target) through replay parsing, but if we did we'd want to do it on another tab (the first tab is for WebAPI data only).

You can continue reporting bugs here.
