### ISSUE TITLE
cookies expiring on session end

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#313]
this is causing people to get logged out when they close their browsers, for some reason the cookie expiration date doesnt seem to be set properly.

**Comment by howardc93** [comment]
fixed this, maxAge needed to be set inside a cookie key, so cookie:{maxAge:somevalue}

**Comment by Brian-McG** [comment]
Can this fix be pushed live as soon as possible. I don't always want to resign in every time, I often go into inactive state as a result.

**Comment by howardc93** [comment]
Should be out in the next couple days.
