### ISSUE TITLE
use modifier applications to count hits

### ISSUE THREAD

**Issue by somesmart** [yasp-dota/yasp#329]
Because Dark Pact hits both slark and the enemy with 10 independent pulses the accuracy calculation is way to high:

http://yasp.co/players/31676059/trends?hero_id=93

The easiest way to fix it might just be to divide by 20, but I'm not sure how the successful hits are currently being calculated. It may also be worth updating the damage and hit calculation code to either separate out self hit/damage and enemy hit/damage. 

It's cool to know how much you damage yourself as slark or others, but it does inflate the numbers in some scenarios.

**Comment by howardc93** [comment]
I'm not really planning to maintain this kind of specific data for each ability.  It's just too difficult to keep it accurate for every ability in the game.

It might be a little easier to try to track modifier name application counts for certain abilities (this would also fix the problem of not counting non-damaging abilities), but it would still require a lot of manual work to find all the names.

**Comment by evaryont** [comment]
Would this kind of information be better suited to being calculated by the parer, Clarity?

**Comment by howardc93** [comment]
No, the parser is only responsible for extracting raw data from the replay.

**Comment by McHearty** [comment]
One of us can go through and do all of these by hand @howardc93 probably going the latter route to track hits for non-damaging abilities if I were going to do it

**Comment by howardc93** [comment]
Yeah, you'll want to map each skill name to the modifier name it applies.  If you want, you could get started with a few, and we can add more gradually.

Skill names are in sources.json.

Modifier names may be trickier, you may be able to find them somewhere online, in the Dota 2 constants files (on your computer), or you may need to build the parser, run it on a few replays, and inspect the modifier_applied events.  I updated it to emit modifier_applied events in 2.0-dev branch.

I would just add code to the processParse function to use these mappings if they're available, and otherwise fal back on damage instances.

**Comment by howardc93** [comment]
NB these changes would only affect future replay parsing, so the current averages would still be thrown off.

**Comment by howardc93** [comment]
Actually it could probably work retroactively.  If we just count modifier_applied, we can use constants to determine whether hero_hits or modifier_applied should be divided by ability_uses to get a percentage.  modifier_applied isn't tracked in all previous parsed matches, though, so there might still be weird numbers if we keep the old parsed matches.

**Comment by Turmfalke2** [comment]
I feel like skill accuracy for skills or not skill shoot just makes no sense. It is nice to have a percentage number for how many elune's arrows have hit a player or roshan, but for single target spells I just don't see the point.
Right now if I look at my skill accuracy table I have leech seed at the top with 317.58% hits. Obviously that is again a case of a skill that hits multiple times, but if I use leech seed to push out a lane how does it affect my accuracy?
The next skill on the list for me is eyes in the forest, apparently I have a 49.01% chance to hit a tree?

My suggestion would be to reduce the accuracy table to only list skills shoots with a meaningful accuracy.

**Comment by howardc93** [comment]
Yeah, we thought about doing this, and I listed some (but not complete) skill shots here:

**Comment by howardc93** [comment]
likely not doing due to difficulty maintaining accurate mapping of modifier name to ability name.
