### ISSUE TITLE
income graph, courier gold

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#330]
hi,
In the match 1354334165 I killed a courier. The income graph displays 175 courier gold for everyone in my team, but 0 for me.

**Comment by howardc93** [comment]
I've seen this a couple times.  Not sure what's causing it, but I'm fairly certain it's not a bug in the parser, just in the combat log entries.  It's possible that when you kill a courier yourself your gold is put in some other category since you last hit it.
