### ISSUE TITLE
Roshan/Aegis/Cheese tracker

### ISSUE THREAD

**Issue by evaryont** [yasp-dota/yasp#332]
Watching [Rusts cast the longest game ever](https://www.youtube.com/watch?v=UPe4uHjlOyA) made me realize is it would be nice to be able to track a few things Roshan related:

- What times did Roshan die?
- (If it's not too much harder) How long did it take to kill Roshan?
- Who picked up the aegis? The cheese?
- When were the cheese(s) & aegis used? Were any of those times simply the aegis being reclaimed?

I think this could be a separate tab, it's all Roshan-related and I don't see anywhere it could be added to the current display.

**Comment by howardc93** [comment]
Roshan deaths:
We can track these.

How long:
Would need to start timing when roshan is damaged, and stop when roshan is killed.  Probably doable.

Aegis/Cheese:
This is harder, and I don't know of a good way to track picking up of aegis and cheese.  It's possible they're entities, but I don't know how to figure out who picked them up.

Using Cheese and Aegis:
Active cheese uses are logged in the player item uses.  Aegis usage is harder to detect.

**Comment by evaryont** [comment]
The aegis usage might be a bit easy, since the item is removed from the player's inventory. Is there no way to track when an item is removed from inventory? (Which could be noisy, but oh well, whenever a player drops an item on the ground,)

**Comment by howardc93** [comment]
I actually don't know how to get the items in a player's inventory.  It might be in the PlayerResource entity (which stores stuff like LH, gold, level, kills, etc).  Or it might be in the entity of the unit the player is controlling.

Do you mean the structure YASP puts its parsed matches in?  
You can find that here: https://github.com/yasp-dota/yasp/blob/master/utility.js#L217

I don't think that will be useful to you though, as that's just the form we choose to hold our data in.  It doesn't reflect how the data is stored in the replay (which is not JSON).

**Comment by howardc93** [comment]
The replay data is in "messages".  Clarity allows us to use Java to extract the contents of these messages.  We have our parser output a stream of log events (all as JSON objects), and then read these events in JS to aggregate data for a match.  We store this aggregated JSON blob in our DB (~100kb a match).

**Comment by eblis** [comment]
This is available now with the Objectives page ? (except the Cheese).

**Comment by howardc93** [comment]
Only Roshan death times and aegis pickups are (using the chat event messages from replay)

Timing Roshan fights, aegis expired/used isn't, but I suppose those aren't super important.
