### ISSUE TITLE
Show a small colored box for the player's color

### ISSUE THREAD

**Issue by evaryont** [yasp-dota/yasp#334]
Players will sometimes refer to another based on the color (teal, pink, brown, etc. [The chat for match 1357893108 for example](http://yasp.co/matches/1357893108/chat)) and not their name. While I think the ordering is almost always the same so I could memorize it, it would be convenient to show the player's color. Perhaps a thin border to the left of the player?

**Comment by howardc93** [comment]
Would need to define mapping of slot number to hex color.  If you could do that for us, actually adding it would be pretty trivial.

**Comment by howardc93** [comment]
We have to be careful of 1v1 games, though, so the mappings should probably be with player slot, which go 1,2,3,4,5,128,129,130,131,132.

The only annoying part is getting the correct hex values.  Anyone feel like tackling that?

**Comment by McHearty** [comment]
Blue - #2E6AE6
Teal - #5DE6AD
Purple - #AD00AD
Yellow - #DCD90A
Orange - #E66200
Pink - #E67AB0
Pus Yellow - #92A440
Light Blue - #5CC5E0
Green - #00771F
Brown - #956000

These are all the colours used ingame

**Comment by howardc93** [comment]
Thanks!  @albertcui can you get this in tonight?  Could possibly push directly to master, since it's UI only.

**Comment by howardc93** [comment]
@McHearty if you'd like to get a contrib in, you could add these to sources.json for us, just
```
"player_colors":{
"1":"#2E6AE6",
...
"128":"#E67AB0",
...
}
```

**Comment by McHearty** [comment]
@howardc93 added a pull request

**Comment by albertcui** [comment]
Thanks! Will try to get this in tonight.

**Comment by howardc93** [comment]
Cool, just need to update the Jade templates to use the colors now.  If we're feeling ambitious we could probably get c3 to use these colors as well. . .

**Comment by albertcui** [comment]
This is on production right now, [here](http://yasp.co/matches/1360191875/chat) for example.
