### ISSUE TITLE
Incorrect gold from selling items

### ISSUE THREAD

**Issue by dillyia** [yasp-dota/yasp#343]
It includes gold from the 10-sec refund. So if I buy Force Staff then sell it then buy it and sell again, I can fake a high gold gain. It messes up with the "Income Sources" graph.

But I guess fixing it is gonna be troublesome.

**Comment by howardc93** [comment]
Yep, there's no good way to detect this.  The sell event only has the gold gain and the reason, so we'd have to be guessing about the item that was being sold.
