### ISSUE TITLE
head-to-head comparisons

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#351]
idea by @nickhh 

Allow head-to-head comparisons with some player by account_id, or tournament games.

We can get tournament games by finding matches where leagueid>0, and then creating a "performance" for each player in the game.

**Comment by howardc93** [comment]
Also would need to decide what metrics to compare against.  Nick suggests "wards per min"

**Comment by Brian-McG** [comment]
So when players set up their official names etc they can select if they are a core or a support (can you get this info from the api?)
It might be nice to base the head to head metrics on this.
So for cores it focuses on kills, gpm, xpm. last hits etc. 
Supports on wards, smokes, assists etc.
![Image of core/support](http://i.imgur.com/tfjWkb3.jpg)

**Comment by howardc93** [comment]
As far as I know, there is no API for that information.  Players end up playing different roles anyway

**Comment by howardc93** [comment]
possibly use two c3 rotated charts:
http://c3js.org/samples/axes_rotated.html

Line them up left/right, and compare across categories that way.

**Comment by howardc93** [comment]
Or if we want to compare more than 2 players, we can use standard grouped bar chart

**Comment by howardc93** [comment]
An extension of this would be the ability to compute percentiles for each stat.
