### ISSUE TITLE
Complete history

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#359]
We could potentially add the entire Dota 2 match history.

Back of envelope math says:

UPDATED (2016-1-13):

Time:
~2 billion seqnums, probably ~700 million matches
An API request will get 100 at a time
If we make one request a second, it will take about 57 days to import.
We can parallelize by starting multiple importer threads (start at 0, 100 million, etc)

Storage:
If we remove the ability_upgrades data from each match:
Each player_match has about 25 fields, mostly 4 byte ints.  Each match has about another 20 fields, 4 byte ints, so ~1080 bytes/match.
700 million matches*1KB=700GB.

Scanner:
We would want to insert all matches, but only parse those with an active user (same as now).
There are ~1 million matches played per day (more on weekends and after patches).
Dropping the ability_upgrades data (store it in Redis with TTL):
Redis:
1 million * 1000 bytes per match * 7 days = 7GB.
DB:
1 million * 1kb =1GB of growth per day.
Parsing:
50k * 200KB = 10GB of growth per day.

11GB is sustainable.  It seems like the bulk of our insertion storage will come from parsing rather than the basic match data for all matches.

Possible impacts:
* Index growth.  Our indexes will likely get quite a bit bigger due to the 7x increase in number of rows in matches and player_matches.

If we do this, we'll probably need to resize our drive to 800GB or larger. (Currently 2TB).

- [x] enable add all matches
- [x] track all matches start seq num, 1876742099
- [x] run script to backfill matches
- [x] update FAQ
- [x] update player profile tooltips
- [x] ~~delete fullhistory from sign-in flow~~

**Comment by McHearty** [comment]
Is there a benefit to tracking the entirety other than more localized stats for items/heroes, or is this a movement towards more leaderboard type features?

**Comment by howardc93** [comment]
From my point of view the main benefit would be the ability to have all of a new user's matches when they sign in.  Currently a lot of people sign in, see only a few matches, and start complaining about "only has 6 of my games, site doesn't work".

Of course, with the full data set we COULD also do more analysis and aggregation, but I don't really have anything concrete planned.   We maybe could try to rank players on heroes using the strict metrics of games played and MMR, but I'm a little hesitant to start trying to make up rankings and present them as canonical.

**Comment by McHearty** [comment]
Well it would open up the ability to sort some cool things for heroes based on patches, kinda like getting current metas for builds.

Common Skill Builds (Top 3,4,5)
Common item Timings per patch, or even buy popularity

I think a lot of the people who want instant gratification are the types of people who aren't going to be active anyways, where the current model supports actively viewing your stats to maintain in the salt pool. I'm for it either way because a lot of cool stuff can be done with full match history

**Comment by howardc93** [comment]
Skill builds are already done by other sites.  Also, we would not be importing ability upgrade data of old matches to save space.

Item timings require us to parse a match.  We can't parse the 500 million historical matches.

Popularity of endgame items is already done by others.

**Comment by howardc93** [comment]
Leaving the issue open, but not putting on roadmap.  At this point I don't think it's worth the space investment.

**Comment by howardc93** [comment]
I don't think this is practical because of the massive index size that would result.  Our index is currently ~14GB with 20 million matches, scaling up to 500 million would require RAM in the hundreds of GB, unless we shard the database.

**Comment by howardc93** [comment]
Now that are storing our data compressed, this is once again an option.  Our compression ratio seems to be about 33%.

I estimate about 600 million matches now.  API data for each is about 10kb, so this is 6TB uncompressed, 2 TB compressed.  We could cut this down significantly by not storing ability upgrade data (down to about 200GB).

About 1.2 million matches are added per day.  If we store full data for each, this is about 12GB per day compressed, 4GB compressed.  We are currently parsing about 15000 matches per day, each one about 200kb, 66kb compressed, ~990MB.  Thus we can expect daily growth of about 5GB.

**Comment by Aehrraid** [comment]
This is not about parsed matches, right? Only match details?

**Comment by howardc93** [comment]
Yes, only data from the API.

**Comment by albertcui** [comment]
I really don't see the need, especially since it would increase our index
space. Mongo is slow enough as it is.

**Comment by howardc93** [comment]
I don't think it's Mongo being slow, but our HDD :P

**Comment by howardc93** [comment]
Closing again, I guess.  It annoys me that a lot of people try YASP, don't bother to read the FAQs and complain "it doesn't have most of my matches, site doesn't work".

**Comment by howardchung** [comment]
It's time to consider this again since we have a plan to expire ability_upgrades data.  600 million matches to add * 1 kb each is about 600GB of disk.

**Comment by howardchung** [comment]
updated math in OP

**Comment by howardchung** [comment]
Progress: Looks like we're maybe 70% done.

Reference note: We started adding all matches as of sequence number `1876742099`

**Comment by howardchung** [comment]
Update:
Batch status:
```
root@core-1:/data# redis-cli keys "complete_history:*" | xargs redis-cli mget
 1) "1474712684"
 2) "681638885"
 3) "1000000007"
 4) "1765993799"
 5) "384454983"
 6) "787431759"
 7) "1862705528"
 8) "1575456784"
 9) "581349426"
10) "1188658325"
11) "1677900717"
12) "901400249"
13) "100000173"
14) "1372800159"
15) "1081266389"
16) "1280113853"
17) "479299003"
18) "290944944"
19) "200000130"
```

Rate appears to be approximately 400 seqnum/sec.

Projection forward: (15 * 19 million)/(400 * 86400) = ~8.24 days left.

**Comment by howardchung** [comment]
(9+10+14+6+22+15+30+13+20+15+7+18+23+16+18) * 1 million / (400 * 86400) = ~6.82 days left

**Comment by howardchung** [comment]
Update:
```
 1) "1000000007"
 2) "800000064"
 3) "1875919091"
 4) "901400249"
 5) "100000173"
 6) "1100000164"
 7) "300000143"
 8) "200000130"
 9) "1492075497"
10) "696059827"
11) "1781182348"
12) "397229817"
13) "1593963849"
14) "595418121"
15) "1200000099"
16) "1693796282"
17) "1389245763"
18) "1298159643"
19) "492212222"
```

(8+4+19+3+6+5+6+11+2+8) * 1 million / (400 * 86400) = 2.083 days

**Comment by howardchung** [comment]
We're done!  Elapsed time: ~68 days.  DB size: 3.992TB
