### ISSUE TITLE
Broken sorting

### ISSUE THREAD

**Issue by alexeykovp** [yasp-dota/yasp#361]
![screenshot-yasp co 2015-04-14 19-39-01](https://cloud.githubusercontent.com/assets/11300577/7142048/27c8f34c-e2de-11e4-9aa5-5fddd8323a1f.png)

**Comment by howardc93** [comment]
This should be fixed in dev branch.

**Comment by howardc93** [comment]
Can you leave your account ID so we can check it when new code is deployed?

**Comment by alexeykovp** [comment]
Sure, 230827073

**Comment by albertcui** [comment]
Should be fixed.
