### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#362]
A long-term thing, but eventually we should probably refactor all our strings into constants and supply language files.

We'd need volunteer translators to help out.

- [ ] externalize all strings
- [x] set up crowdin project
- [ ] figure out subdomaining
- [ ] figure out how to use valve data in other languages

**Comment by howardc93** [comment]
https://github.com/mashpie/i18n-node

**Comment by howardc93** [comment]
Don't think this is worth doing. . . site can just be run through google translate.

**Comment by howardchung** [comment]
reopening.

We probably need to pass something to constants.js (based on subdomain?) to specify the set of constants to be used.

Many strings are in tooltips.json.

Valve has translations of item and ability data at: (ex) http://www.dota2.com/jsfeed/itemdata?l=tchinese

**Comment by howardchung** [comment]
This is a UI issue:
https://github.com/yasp-dota/ui/issues/37
