### ISSUE TITLE
Improve activity (cal-heatmap)

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#368]
- [ ] Show win rate by color. 
- [x] Show more than one year.
- [ ] too wide on mobile

**Comment by howardc93** [comment]
also invert the domain display order:
https://github.com/yasp-dota/yasp/issues/462
kamisama/cal-heatmap#111

**Comment by nickhh** [comment]
summarize the activity heat maps in a line graph
(example: http://yasp.co/players/75392401/activity)
trends are too hard to see right now

**Comment by howardchung** [comment]
If we are going to use the color to denote win rate we need something else to denote magnitude (# games played)

**Comment by Derek-Li** [comment]
I think it would be nice to have an indication that color is winrate & number is matches played.

**Comment by howardchung** [comment]
Color is not winrate yet right now.

**Comment by likered** [comment]
How about:
color = total # of matches played 
percentage = winrate win/loss

The percentage can go within the boxes. One concern is that the calendar might need to be slightly bigger to accommodate the percentages (45%)

**Comment by howardchung** [comment]
Yeah you can play with it and see what works best.  The cal-heatmap is already too wide for narrow screens.

**Comment by howardchung** [comment]
If we're going to do this, it'll be on the new UI.  I am not even sure if we are going to port the cal-heatmap.
