### ISSUE TITLE
AJAX error when loading player page

### ISSUE THREAD

**Issue by mjdesrosiers** [yasp-dota/yasp#373]
When I open my player page ( http://yasp.co/players/136754293 ) in Chrome Version 42.0.2311.90 m, I receive this error:

DataTables warning: table id=matches - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Chrome console shows:

Failed to load resource: the server responded with a status of 413 (Request entity too large: request URL path too large)
follow_button.7c0d5c8fc0456a01b74fed2e38018608.en.html:1 

Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
jquery.qtip.min.js.map:1 GET http://cdn.jsdelivr.net/qtip2/latest/jquery.qtip.min.js.map 404 (Not Found)

Resource interpreted as Image but transferred with MIME type application/javascript: "https://pix04.revsci.net/D08734/a1/0/3/0.js?DM_LOC=%3Dhttp%3A%2F%2Fna.com%3…Initiated%3Dtrue%26nada%3D%26naid%3D2015041820144929153183723104%26namp%3D".

**Comment by howardc93** [comment]
This is likely just the API not responding.  We're aware it's running a little slowly right now, so when it times out, DataTables throws the error.

**Comment by howardc93** [comment]
If it persists in happening please reopen the issue.
