### ISSUE TITLE
Purge MMR from users with private setting

### ISSUE THREAD

**Issue by dpi** [yasp-dota/yasp#379]
It seems the option for private/public has been removed since #357. Users with private MMR now have their scores displayed publicly. The ratings data of users with the private option should have their scores purged, and defriended by the bots until they understand they no longer have a choice.

**Comment by howardc93** [comment]
We are manually processing takedown requests:

http://yasp.co/post/mmr-visibility

**Comment by howardc93** [comment]
Deletion of data of currently-private users would be easy, automatic defriending less so.  We don't want to delete data of users immediately since we wouldn't be able to get it back.

It's also possible that we just stop doing rating-relating things at some point.  It's kind of auxiliary.
