### ISSUE TITLE
Requests for matches already in database causes unavailable status if replay is not found

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#380]
Reported on Reddit:
>I had a replay parsed with v6, and I was hoping to get it parsed with v7. I requested it and it's been >15 days so I think yasp overwrote the v6 analysis and just left it as unavailable... http://yasp.co/matches/1379919621

Expected outcome I think should be no change on the parse status.

**Comment by howardc93** [comment]
I thought I was handling this case already. . . need to confirm it first

**Comment by howardc93** [comment]
Appears to just be a overwriting of the status, the data is still there.  The tabs disappear since we're using match.parse_status to determine if they should appear.  I've changed it to check for parsed_data.version.

**Comment by howardc93** [comment]
should be fixed
