### ISSUE TITLE
benefits for donators

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#384]
This issue is for ideas for benefits that can be offered to donators.

Benefits should be strictly "thank-yous", and not come with any SLA or contractual agreement.  
All functionality of YASP should remain available to all users.
Donations are not meant to "buy" services, but just help us offset server costs.

Things we can offer:
* Sandbox access.  Give donators access to bleeding-edge versions of YASP.
* Permanent parsing.  Make donators immune to the 7-day untracking.
* Remove ads

More ideas?

**Comment by eblis** [comment]
How about allow cheese donors to hide their MMR like one could a while back ?

**Comment by howardc93** [comment]
I don't want to hold on to "private" data at all.  It's why we switched to
making all data public.

**Comment by eblis** [comment]
I see, makes sense.

**Comment by howardc93** [comment]
Implementing permanent parsing with the next deployment.  Will reopen if we have more ideas.
