### ISSUE TITLE
Issue with skill build parsing?

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#386]
http://yasp.co/matches/1426199190

It shows that Void leveled up Chronosophere at levels 10 and 15.

Same game on Dotabuff
http://www.dotabuff.com/matches/1426199190/builds

**Comment by albertcui** [comment]
Not a bug. This data is from the API, and shows the order in which the skills were leveled.

You can see [here](http://yasp.co/matches/1426199190/graphs) that the void leveled from 9 to 11 between minutes 19 and 20, so he just leveled Chronosphere first. [Here](http://yasp.co/matches/1426199190/teamfights) we can see the teamfight at 19:02 that got him that much XP.
