### ISSUE TITLE
Cheese Subscriptions

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#388]
Cause who doesn't want more cheese?

**Comment by howardc93** [comment]
Does this need to be done at this time?

**Comment by albertcui** [comment]
Yes.

**Comment by howardc93** [comment]
okay then

**Comment by howardc93** [comment]
Can we offer subscribers anything else, to give them an incentive?

**Comment by howardchung** [comment]
@albertcui are we still going to do this :P
