### ISSUE TITLE
Add first blood to objectives page

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#390]
I'm guessing this was requested but it's hard to implement ?
If not, I'd like to request adding First Blood event to the Objectives page, maybe with the players involved (who died, who killed, who assisted)

**Comment by howardc93** [comment]
It's not that hard, first blood is a chat event.  IIRC the first blood event is emitted separately from the kill event, so getting the player involved might be harder.

**Comment by howardc93** [comment]
According to this:
http://dev.dota2.com/showthread.php?t=32968

```
CHAT_MESSAGE_HERO_KILL
The are a couple of different scenarios for this. The first one is when one hero kills another, there will be two player IDs listed. playerid_1 refers to the hero that was killed, while playerid_2 refers to the killer. If this kill was first blood, there will immediately be another chat event CHAT_MESSAGE_FIRSTBLOOD where playerid_1 is the hero obtained the first blood, while playerid_2 is always -1. The "value" for both CHAT_MESSAGE_HERO_KILL and CHAT_MESSAGE_FIRSTBLOOD is the gold that was received. In the case of a firstblood, the values for firstblood and the kill are identical. If there are assists, it appears the playerid_1 is the death, playerid_2 is the last hit, and all subsequent playerid_# are the assists.
```

So we can probably get the hero who obtained the first blood (which fits best with the current layout anyway, since we only have room to display one hero as the "achiever")
