### ISSUE TITLE
Use in-game player colors for graph colors

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#391]
It would be nice to use the same colors the players had in game for all the graphs.
I'm guessing the colors are static (same player # has the same color every time) and you'd only need the player order to have all the required information.
Are the colors used in-game hard to see in the graphs ?

**Comment by howardc93** [comment]
c3 lets us define a custom color palette, so this probably isn't too hard to do.  We are using the default c3 colors at the moment.
