### ISSUE TITLE
Denied towers should be listed in the Objectives page

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#393]
I noticed that denied towers do not make it to the Objectives page, I think it would be nice if they were listed as well.

**Comment by howardc93** [comment]
I am not sure if TOWER_DENIED is emitted as a separate event or if it's emitted in addition to CHAT_MESSAGE_TOWER_KILL.  I can just add the event--I guess it's not terrible to have it show up as both a kill and a deny. . .
