### ISSUE TITLE
6.84

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#397]
Breaking changes:

- [ ] Observers (but not sentries?) now come in stacks of 1, update match details template to no longer multiply by 2

- [ ] Gold efficiency needs adjustment due to new creep bounty

- [x] ~~Add new consumables to details (mango, moon shard?)~~ Actually we're not doing this for tangoes/clarities/salves, so let's just have them show up on the usage section but not details

- [x] ~~How does observer/sentry merging into one slot affect API endgame items/replay inventory check?~~  This shouldn't require any changes, valve may use a new item id, or default to observer, but either way they should update ther itemdata and we can just pull that.

- [ ] If no new hero, wait for patch to hit and then deploy new code+6.84 fixes.  If new hero, will need to manually patch hero constants in production before patch hits.  Does Valve update the GetHeroes API before patch?

**Comment by howardc93** [comment]
Re: stack size change and gold eff change:

I'm fine with not distinguishing between pre and post 6.84 matches.  It means these numbers will look weird (wards bought showing up as "half" the expected amount), but I think recent matches matter more anyway.  We are currently not doing any aggregations on either of these fields.

**Comment by albertcui** [comment]
On the other hand, it wouldn't be hard to distinguish between them.

**Comment by albertcui** [comment]
There is no new hero.
