### ISSUE TITLE
matches table is empty/no there

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#400]
hi,
It looks like something is wrong with the matches table on the player page. No matter how I change the filter settings, there is just nothing between the headline "MATCHES" and the advertising above the "HEROES" headline.

The only way to get the my last match is to directly request it using yasp.co/requests.

**Comment by albertcui** [comment]
Hey,

Can you give us your profile page?

Thanks,

Albert

**Comment by howardc93** [comment]
Yep, there currently seems to be a problem with the CDN we're using to serve our JavaScript.  We're planning to deploy new code after 6.84 hits (probably tomorrow) which should fix the problem.

It appears that users who have the JavaScript file cached already aren't affected by this problem.

**Comment by howardc93** [comment]
I was able to repro this on my own profile using IE last night, will close if it's fixed after deploy

**Comment by howardc93** [comment]
should be fixed
