### ISSUE TITLE
Sentry wards

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#406]
hi,
Sentry wards are still purchased as packs of 2. So what does it mean if it says a hero bought one sentry ward in the details tab?

http://yasp.co/matches/1448215102/details

**Comment by albertcui** [comment]
Fixed! https://github.com/yasp-dota/yasp/blob/master/views/match/match_details.jade#L45

**Comment by albertcui** [comment]
We'll deploy this later. The number listed just needs to be multiplied by two.

**Comment by howardc93** [comment]
I removed all multipliers.  Dust and sentries are still sold in stacks of
two, and I updated the tooltips to reflect that.
