### ISSUE TITLE
"Results" dropdown list doesn't work

### ISSUE THREAD

**Issue by alexeykovp** [yasp-dota/yasp#412]
![screenshot-yasp co 2015-05-07 17-53-20](https://cloud.githubusercontent.com/assets/11300577/7518205/493f3976-f4e2-11e4-9a3c-471e119c7b2c.png)
Either its choosen "losses" or "wins" it always returns all matches. It seems like this option in filter code just skipped. Its even don't save the state of dropdown list after submitting form.

**Comment by alexeykovp** [comment]
Same with "Lobby Type" and "Faction".

**Comment by howardc93** [comment]
Thanks for the report.  I will investigate

**Comment by howardc93** [comment]
Had incorrect type comparison on wins/faction, and just plain forgot to implement the server-side filter for lobby_type.

**Comment by howardc93** [comment]
Will deploy soon (when CI passes)
