### ISSUE TITLE
Using the YASP Replay Parser as a Standalone

### ISSUE THREAD

**Issue by tankqc** [yasp-dota/yasp#413]
Hey guys,

I'm trying to run the yasp parser as a standalone to analyze practice/private lobbies. I'm running the parser with the following command:

> java -jar stats-0.1.0.one-jar.jar < replay.dem

But it outputs the following error:

> oops. no provider found for required usage point interface yasp.OnYASPCombatLogEntry

I'm building the yasp parser with the command in Eclipse (maven build)

> -P yasp package

Anything I'm missing? I have Java JRE 1.7.

Cheers,
Tankqc

**Comment by howardc93** [comment]
Have you tried running it the same way on non-private lobbies?

**Comment by howardc93** [comment]
If it works with a nonprivate replay, it's probably a clarity issue.

https://github.com/skadistats/clarity/issues/36

**Comment by howardc93** [comment]
You can also try running the clarity-examples on your replay--if those don't work, it probably means your replay isn't parseable.

https://github.com/skadistats/clarity-examples

**Comment by tankqc** [comment]
I tried using the 6.84 replay in the YASP test files and its the same result. Not sure why I can't run it locally from my end.

For some reason, it can't find the YaspCombatLogEntry class. Not sure why (shouldn't the annotation Runtime make it accessible from the VM/Class).

**Comment by howardc93** [comment]
What code do you have?  Latest master?

**Comment by howardc93** [comment]
YASPCombatLogEntry and OnYASPCombatLogEntry should be in the same package as the other code. . . so there shouldn't be any issues finding it.

**Comment by tankqc** [comment]
It is, I'll investigate further.

Thanks for the help and quick replies! Very appreciated. You guys rock.

**Comment by howardc93** [comment]
updates?  can the issue be closed?

**Comment by tankqc** [comment]
I'll close it. Haven't gotten it to work but I've put it on hold for now. I'll post the solution if I ever get it to work.

Thanks again.
