### ISSUE TITLE
/matches API route crashes site?

### ISSUE THREAD

**Issue by gu3st** [yasp-dota/yasp#414]
I was doing some prodding on the live yasp site, and found that going to the /matches route appeared to crash the site (returned 502 for main site, until a presumed restart).

Probably throwing an exception?

**Comment by howardc93** [comment]
I just tried it and get 404.  Admittedly it's the cloudflare version rather than our custom one, but I don't see a crash.

**Comment by howardc93** [comment]
or do you mean /api/matches?

**Comment by howardc93** [comment]
Looks like you're right, investigating now

**Comment by gu3st** [comment]
Feel free to hide this/delete it so it's not shown publicly to be abused.

**Comment by howardc93** [comment]
Should be okay, I can probably push out a fix in the next 30 min to an hour

**Comment by howardc93** [comment]
I wasn't able to repro it directly but I found the error and added an if statement to handle match.players not existing (don't know why a match wouldn't have players, but apparently it can happen)

**Comment by howardc93** [comment]
looks like it's fixed.  Thanks for the report!
