### ISSUE TITLE
objectives lists first blood twice

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#427]
hi,
In this game http://yasp.co/matches/1481023555/objectives the first blood shows up twice.

**Comment by howardc93** [comment]
This may be related to #426 

I suspect a replay issue rather than a parser bug.

**Comment by howardc93** [comment]
The PR will likely fix this for future matches, but matches from the last couple days may have double-event bugs.  Unless there's a pressing need to, we will probably not reparse matches (so some data for this date range will be inaccurate)
