### ISSUE TITLE
clarify objectives page with specific tower lost

### ISSUE THREAD

**Issue by nickhh** [yasp-dota/yasp#435]
as seen here
http://yasp.co/matches/1489573067/objectives
saying "Tower" is not helpful
but saying "Radiant Top Ranged" is helpful
so try and do the latter everywhere

**Comment by howardc93** [comment]
done for barracks, towers are more challenging and requires analyzing auxiliary events

**Comment by howardc93** [comment]
reopen if you want to try to tackle it
