### ISSUE TITLE
nick fixes

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#436]
-[ ] put towers on position tab
-[ ] fix how ugly the heatmap coloras are
-[x] add tooltips to details kill deaths to explain the / notation
-[ ] confirm that teamfights death icon works

**Comment by howardc93** [comment]
on 3), also received a complaint about the color contrast (red/green text on red/green background)

**Comment by howardc93** [comment]
did one for you.

Semi-disagree on the first.
Second just requires some JS tweaking if you want to do it.  I can guide you through.
Last. . . what's the plan for testing this?  The unicode def shows up differently on my ubuntu machine than on windows, so it may be OS dependent. . .

**Comment by howardc93** [comment]
the issue will close, did yo want to tackle the other stuff or not important?

**Comment by nickhh** [comment]
1) this is stupid, i no longer want to do this :P
2) fixed this in PR (yayyy!)
3) howard did this (ty howard :) )
4) i don't care enough to concern myself with cross platform issues :P
