### ISSUE TITLE
Roshan is always listed as being killed by the Dire

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#439]
Roshan is always listed as being killed by the Dire, even when he's killed by Radiant.
I remember this working at some point so I think it's something new, maybe in the latest release ?

**Comment by howardc93** [comment]
Can you link a specific match example?

**Comment by eblis** [comment]
Sure, here's one example http://yasp.co/matches/1498326028

**Comment by howardc93** [comment]
It appears that new replays have radiant/dire as team 0/1 rather than team 2/3.  I suppose I can add both cases to the if check that determines the string to display

**Comment by howardc93** [comment]
Will deploy this shortly.

**Comment by howardc93** [comment]
Appears to be fixed:
http://yasp.co/matches/1498326028/objectives
