### ISSUE TITLE
telemetry

### ISSUE THREAD

**Issue by nickhh** [yasp-dota/yasp#451]
write an automatic speed-test benchmarking framework for the production server, which will be run automatically and periodically, so we'll have performance data/facts to back up decisions about the effect of changes (hardware or software) on site cause speed up. (maybe we can do this with the site's existing infrastructure?)

TODO:
- [x] response time - http://stackoverflow.com/questions/8719626/adding-a-hook-to-globally-log-all-node-http-responses-in-node-js-express
- [x] time to parse
- [x] failed parses
- [x] web errors (500 calls)
- [ ] steam API status
- [x] retriever status (replay service)
- [x] parser status

**Comment by howardc93** [comment]
GCE's monitoring tools kind of already do this. . . do we need anything more?

**Comment by howardc93** [comment]
I think merge with #263

**Comment by howardc93** [comment]
Can we extend this to automatically detect service downtime as well?

**Comment by howardc93** [comment]
This would be useful to detect Steam API downtime/replay unavailability so we can display an automatic message to users (and save me some debugging time when I try to figure out an issue only to realize it's Steam API being down :P)

**Comment by nickhh** [comment]
We could prob parse "https://steamstat.us/" or find a similar service with
an API.

**Comment by howardchung** [comment]
We could track metrics such as response time, time to parse, failed parses, web errors (500 calls) and display cool histograms, etc.
