### ISSUE TITLE
tool-tip clarity/consistency

### ISSUE THREAD

**Issue by nickhh** [yasp-dota/yasp#454]
update tool-tips across the site for clarity and consistent style

TODO:
- [x] externalize tooltip strings
- [x] tooltips for categories in player pages (histograms, records, trends, compare)
- [x] tooltip for "status" column in player match tables

**Comment by howardc93** [comment]
Any specific examples?

**Comment by nickhh** [comment]
I feel like every column header should have a tool tip. For example, on player>overview>recent, K D A are well-known but I think they should still have a "Number of players killed" tool tip. What about "Played"? Is that the start time or end time of the game? I'm actually not sure. On player>overview>heroes there are three diffirent "win%" so what am I supposed to do with that knowledge?? I was basically going to read through every table and write a description for **every** word that I didn't think was 100% clear.

**Comment by howardc93** [comment]
Sounds like a good idea.  

Merging the other tooltip issue into this one.

**Comment by TrentBartlem** [comment]
*Match > Overview*

    LV	K	D	A	LH	DN	GOLD	GPM	XPM	HD	TD	HH

all need titles or tooltips.

*match > Combat*

    KILL_TIMES

underscore? Did text replacement miss this token?

*match > graphs*

    CLICK ON AN SERIES IN THE LEGEND TO TOGGLE 

'a series'

**Comment by howardc93** [comment]
tooltips will be added in #572 

I fixed the other two, thanks for the report!

**Comment by howardchung** [comment]
@nickhh I want to do this soon.

I think we should externalize all tooltip strings to sources.json (so we can reuse them if they're needed in multiple places and to make future translation possible).

**Comment by howardchung** [comment]
Reassigned to myself since I want it done soon but would love some help since there's going to be a lot of copy-pasting :(
