### ISSUE TITLE
site style / table centering

### ISSUE THREAD

**Issue by nickhh** [yasp-dota/yasp#455]
some tables seem like they would look better with the text centered in cells
@howardc93 @albertcui @mvthen thoughts on overall site style?

**Comment by howardc93** [comment]
example?

**Comment by nickhh** [comment]
it's just my personal preference, but for example, all of them on the details page

**Comment by Brian-McG** [comment]
I agree with nick provided that the headings are centred too.You could always change one of the sections and post some before / after pics to compare before doing all of them.

**Comment by howardc93** [comment]
sure nick i guess you can test some of them and post some comparison pics?

**Comment by nickhh** [comment]
How about we wait till after the UI branch merge, then I can do a sweep of the entire site for consistency in style (which would cover this issue and #454 as well)?

**Comment by howardc93** [comment]
Live demo here: http://colab-sbx-244.oit.duke.edu:5000/matches/1641395216/

**Comment by Brian-McG** [comment]
If you toggle table on 'Basic' it puts 'Skill Builds' on the same line

**Comment by howardc93** [comment]
Thanks, fixed.
