### ISSUE TITLE
Teammate table sorts win rates incorrectly

### ISSUE THREAD

**Issue by LewisJackson1** [yasp-dota/yasp#458]
![](http://puu.sh/ierLk/42460a1092.png)
Sorting team mates by win rate results in a strange order, as seen above. All players have a 0% win rate, but it goes in the order - 0, 1, 1, 6, 3, 0.
![](http://puu.sh/ierMA/b90a55f082.png)
Whereas, when we do the same with opponents, we get the expected order.

**Comment by howardc93** [comment]
Not sure anything can be done about this--the sort itself is correct, and no secondary sort order was defined.

I'm not sure why the problem doesn't occur with teammates as well as opponents data, but it's possible that's it's a stable sort (won't change the order of tied elements) and you sorted by opponent descending immediately before sorting by winrate.

**Comment by howardc93** [comment]
I believe datatables handles secondary sorts with alt or shift click, but would have to check the documentation.
