### ISSUE TITLE
Histograms page is very inefficient

### ISSUE THREAD

**Issue by nagisa** [yasp-dota/yasp#460]
Opening a [user’s histogram](http://yasp.co/players/176445789/histograms) page in firefox will reproducibly result in a dialog such as this:
![screenshot from 2015-06-07 20-18-53](https://cloud.githubusercontent.com/assets/679122/8025136/88abde6e-0d53-11e5-8b78-baaba370d933.png)

Firefox’s developer tools show the code asks browser to do a bunch of layout, and spends most of the time in `f.updateSizes` (about 21 second).

**Comment by howardc93** [comment]
We develop on Chrome, so I haven't seen this before.  It's likely due to differences in the JS engine that make FF run the code slower.  The histograms page DOES have a lot of data to process.  We could either do some of it server-side, or not display every histogram at once.

**Comment by howardc93** [comment]
I was able to reproduce this in FF but am not 100% sure of the cause.  We could try dumping the data but only generating the histograms when the user clicks a button.  Not sure if this would have a negative effect on UX.
