### ISSUE TITLE
Invert activity ordering

### ISSUE THREAD

**Issue by Brian-McG** [yasp-dota/yasp#462]
Activity (on profile page) currently orders from oldest to newest. Makes more sense if ordering is inverted.

**Comment by howardc93** [comment]
@albertcui opinion?

**Comment by albertcui** [comment]
Agreed.

**Comment by howardc93** [comment]
should I assign to you?

**Comment by albertcui** [comment]
Sure.

**Comment by howardc93** [comment]
apparently this feature has been requested but not implemented:

https://github.com/kamisama/cal-heatmap/issues/111

**Comment by howardc93** [comment]
merge with https://github.com/yasp-dota/yasp/issues/368
