### ISSUE TITLE
Provide information related to Alchemist Aghanim's Scepter(s)

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#464]
Alchemist can now "cast" Aghanim's Scepter on a team mate (or even himself, but doesn't do anything on himself) and this gives the item to the team mate that Alchemist casted it on.
Unfortunately this "item" isn't listed anywhere in the page as it's available as an aura, not in an item slot.

It would be nice if YASP showed information related to these Aghanim Scepters, maybe when Alchemist casted it and on whom and maybe list the "items as auras" on the players as well.

Example match http://yasp.co/matches/1538087439/

**Comment by eblis** [comment]
Probably similar for Moon Shard, when consumed ?

**Comment by howardc93** [comment]
You can see how many scepters/moonshards were consumed in the details page (for parsed matches).  We currently don't track when or who they're used on, though.
