### ISSUE TITLE
source 2 parsing

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#469]
- [x] need new protobufs
- [x] add test case that run parses on source 2 replays
- [x] figure out how to get entities in source 2 (clarity, or switch to manta)
- [x] modify java/go application that utilizes clarity/manta
- [x] may need to modify retriever to support new client? (node-dota2)
- [x] verify that fields in parsed_data are properly populated (remove them if the parser cannot extract the data)
- [x] enable queuing source 2 matches in scanner

**Comment by ashleyhindle** [comment]
Will/Can this use Manta that dotabuff uses? https://github.com/dotabuff/manta

**Comment by howardc93** [comment]
Not sure yet.  I would like to continue using clarity, but if a version supporting Source 2 is not released in a timely manner we will probably switch to Manta.  I've also played with writing a parser in JavaScript, but it's not very far along.

**Comment by howardchung** [comment]
The nice thing about clarity is that it has hybrid support for both s1 and s2 replays.  Therefore as soon as entities are parseable we can simply update the code and drop it in even if there are still matches on both versions.  If we wait until Source 2 is out of beta (so there are no longer any Source 1 matches), we can avoid that potential problem.

Manta's two disadvantages are not supporting source 1 replays, and not being able to stream replays (it requires the entire replay to be loaded ino memory before it can begin parsing).

**Comment by howardchung** [comment]
Status:
waiting for clarity to support entities.  We rely on the gameRulesProxy entity in order to supply time data for every event that isn't a combat log action (so objectives, chat)

Entities are also required for ward/player position data, and gold/xp/lh graphs.

**Comment by Iparke** [comment]
A few days ago, there was a post from a Dotabuff admin on Reddit. It never made FP, but it said that Dotabuff now has Source 2 parsing. Link to official announcement: http://www.dotabuff.com/blog/2015-08-24-truesight-reborn-now-supporting-source-2

They link the Manta hub: https://github.com/dotabuff/manta. I assume it's ready.

**Comment by howardchung** [comment]
I saw it.  However manta still has a couple of downsides and I think clarity is almost ready so we'll probably wait.

**Comment by pyarmak** [comment]
So seeing as we've just officially moved over to source 2 only matches today I suppose that means that this needs to get done sooner rather than later.

I'd love to give you guys a hand with that if you want it. I've been busy over the summer months (that's why I haven't been active on github) but I'll be free to code again after I write my MCAT this weekend.

I took a quick look at clarity and it looks like it's already up to snuff.

**Comment by howardchung** [comment]
Yeah, we're working on this now.  Clarity's entity interface still seems kind of hacky but we'll see if we can have something working by the end of the day.

**Comment by howardchung** [comment]
tests are just disabled for now.  @albertcui can add s2 replay cases later (and maybe actually verify the output instead of ignoring it)
