### ISSUE TITLE
www.yasp.co is treated as separate domain (login doesn't persist)

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#470]
Should be just an easy config change in domains to forward this subdomain, but we should probably fix this :P

**Comment by albertcui** [comment]
Works now but session isn't shared across subdomains.

**Comment by howardc93** [comment]
I think you should use the "synthetic records" section and do a "subdomain forward"

**Comment by howardchung** [comment]
Could possibly fix by implementing a redirect check in one of the middleware functions in web.js?

**Comment by howardchung** [comment]
http://www.somethinghitme.com/2014/07/25/extracting-the-subdomain-with-nodejs/

We can detect a `www` subdomain, then redirect the user to ROOT_URL?
