### ISSUE TITLE
entire game x/y summary

### ISSUE THREAD

**Issue by nickhh** [yasp-dota/yasp#471]
track x/y for all players for the entire game, not just the first 10 mins. see how expensive this is in terms of the size of the db entry. to display, use a sliding scale to advance through time, plot a user-chosen subset of the players, highlight team fights on the sliding scale, put kill/death markers both physically on the map and temporally on the sliding scale, etc. make it cool. make it awesome.

**Comment by howardchung** [comment]
we have the data to construct this.  The sticking points are:

* Need to design an intuitive and easy-to-use UI
* Need to consider cost of storing this much data per match.

Seems like an enhanced version of http://devilesk.com/dota2/apps/replay/viewer/

**Comment by howardchung** [comment]
I think this is going to be too expensive in terms of storage, unless we massively compress it/expire it.

Reopen if disagree/inclined to work on this
