### ISSUE TITLE
make raw yasp match data downloadable e.g. as csv files

### ISSUE THREAD

**Issue by proaufressor** [yasp-dota/yasp#473]
All stored variables directly connected to matches of (my own) profile that are used by yasp (or that could be interesting ?)
or / and a random match or / and player (pooled) sample from yasp database (even though it will be biased by yasp user characteristics) with n big enough to achieve robust test power even for small n hypotheses e.g. in question top ranked player or maybe the effects of Arcane Boots on Visage.
That would be very comfortable.

**Comment by howardc93** [comment]
we've thought about this (something like making the raw match JSON available), but the concern is it taking up a lot of bandwidth since people may try to use it as an API.

**Comment by proaufressor** [comment]
Maybe only for email verified yasp account and limited for .. dont know a 100.000 db queries a year?

**Comment by howardc93** [comment]
We don't currently have a verification or rate limiting system, so we'd have to build it from scratch.

If you want data now you're probably best off running YASP yourself.

**Comment by howardc93** [comment]
I added this--we can see if usage is acceptable.  If it ends up being abused/too expensive we may need to remove it.
