### ISSUE TITLE
Description shown from hovering over hero abilities is in a different language than items

### ISSUE THREAD

**Issue by KurtRobo** [yasp-dota/yasp#481]
Ability
![capture](https://cloud.githubusercontent.com/assets/6838076/8326917/e3a1b7ec-1aa7-11e5-8c96-562641597ac8.PNG)

Item
![2](https://cloud.githubusercontent.com/assets/6838076/8326920/e759f192-1aa7-11e5-9f8d-31696f614e37.PNG)

**Comment by howardc93** [comment]
thanks for the report.  Looks like one of the Valve endpoints was returning different language data for some reason--reloaded and redeployed.
