### ISSUE TITLE
Incorrect rendering of the Hero Icon in Chat tab when using <font> in a name.

### ISSUE THREAD

**Issue by trfunk** [yasp-dota/yasp#483]
A Hero in Chat tab of a game does not get displayed correctly when the player uses a "<font>" tag in his/her name.

http://yasp.co/matches/1590648352/chat (Wraith King is '< font face ="Ravie">Ali SmOker' and the hero icon is not displayed correctly) [screencapture-yasp-co-matches-1590648352-chat.png](https://cloud.githubusercontent.com/assets/4313364/8396981/352b79c4-1dbc-11e5-932a-49a3eef83141.png)
http://yasp.co/matches/1590777338/chat (Another Game, the Tiny is called '< font face="Ravie">Maksim', his hero icon gets displayed correctly, but the icon of the enemy slark [named "=Flame4120="] does not) [screencapture-yasp-co-matches-1590777338-chat.png](https://cloud.githubusercontent.com/assets/4313364/8396976/1bfe4788-1dbc-11e5-9503-3b08e942ddb2.png)

Tested in IE 11 and Chrome 43

**Comment by howardc93** [comment]
I don't think it's the <font> tag that's causing this, but inconsistency in the name between the chat data and the name data.

When we get that chat data out of the replay, each chat message contains a "prefix" and "message".  We attempt to match up the chat messages to players by comparing the "prefix" value to their name.  For some reason this doesn't always work properly, and in this case I just dump out the prefix.

Source 2 replays might fix this.
