### ISSUE TITLE
automatically update leagues/heroes

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#499]
Leagues update pretty frequently and we probably can't afford to wait for deployments to update the league listing.

Currently we save leagues into constants.leagues, which is loaded into memory at startup.  Therefore we currently require a server restart in order to update leagues.

To avoid this we might need to store leagues in mongodb or redis.

Similarly, heroes can be updated server-side (with a new patch) and we need to pick up these changes and immediately have them reflected in the running application without a restart.  Most importantly, building the parsed data object from a parse stream requires a current list of heroes.

We can then run a background task that occasionally pulls the latest heroes and leagues.

**Comment by howardc93** [comment]
avoiding the issue right now by not displaying league name.

**Comment by howardchung** [comment]
The heroes are now stored locally on each parse node, so those need to be updated too.

**Comment by howardchung** [comment]
with #631 the parser no longer relies on external constants and should be able to parse the latest replays even after a new hero is introduced.

Therefore automatically updating heroes is not as important anymore.

Updating leagues is still neccessary if we want to display any kind of league data at all (whether it's breaking up the professional matches by league or just displaying a league name).

**Comment by howardchung** [comment]
don't seem to need this for what we're doing
