### ISSUE TITLE
Accept bitcoin donations (coinbase)

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#506]
Think we can just set up a coinbase wallet.  If we wanted to link into the merchant API we could also support cheese purchasing via bitcoin

**Comment by howardchung** [comment]
According to @albertcui stripe supports bitcoin payments and has a better subscriptions API.  We may consider switching.  My concern is that paypal has a much larger user base and people are probably much more likely to donate if they dont have to make a new account/supply a credit card number.

**Comment by howardchung** [comment]
probably best option is paypal from most users + subs and coinbase for those who don't want to use paypal

**Comment by albertcui** [comment]
I can add this with the subscription branch.

**Comment by howardchung** [comment]
awesome.  should be pretty easy
