### ISSUE TITLE
Old replays/Dotabank integration

### ISSUE THREAD

**Issue by dumasymptote** [yasp-dota/yasp#518]
This isn't really an issue so much as an idea. I know you can't pull replays from valve that have expired but dotabank does have some of those replays available. Would it be possible to check dotabank on requested matches (only if it is expired) to see if it has been archived in order to grab and parse it?

**Comment by albertcui** [comment]
Great idea. Would have to get their devs on board.

**Comment by howardc93** [comment]
@RJacksonm1 I suppose.

**Comment by howardc93** [comment]
Although to be honest, the probability of Dotabank having a replay is pretty low.  They are storing 46,000 replays as of this writing, but there are over a million matches played per day, so the probability of a given match being available on Dotabank is pretty low.

**Comment by howardc93** [comment]
Closing unless we have an authoritative source of replays (with a high hit rate).  Also, the move to Source 2 will probably mean we drop support for S1 replays.
