### ISSUE TITLE
"This user has not visited recently" warning still shows with cheese

### ISSUE THREAD

**Issue by urda** [yasp-dota/yasp#519]
# Problem

Yasp displays a warning for a player who has not visited recently, even though they have cheese, and that their results are not being parsed (even though they are).

## Expected Outcome

No warning is displayed for the user, since they have cheese and their matches are being parsed regardless.

## Actual Outcome

A warning is displayed for the user,  even though they have cheese and all the matches on their profile are marked as `Parsed`.

## UI Example

![screenshot 2015-07-10 11 13 38](https://cloud.githubusercontent.com/assets/1648492/8625632/e32dcda6-26f4-11e5-9550-de79bbe29fed.png)

## References

- [YASP Link](http://yasp.co/players/9678342)

**Comment by albertcui** [comment]
Someone has experience submitting bugs...

**Comment by urda** [comment]
@albertcui That somebody is a Software Engineer in the real world, who knows how annoying bad bug reports are :smile:

**Comment by albertcui** [comment]
Haha much appreciated!
