### ISSUE TITLE
Buyback data is incorrect

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#525]
hi,
Just had a 80min naga game and noticed that the buyback data in the purchases table is incorrect.
I definitely bought back at least once at 52:23.
http://yasp.co/matches/1628323764/purchases

**Comment by howardc93** [comment]
I see one buyback in the table, how many times do you think you actually bought back?

**Comment by howardc93** [comment]
Ah I just noticed you were skywrath, not naga.  I'll take a look

**Comment by howardc93** [comment]
I watched the replay and it looks like it's just missing from the combat log.  Not much we can do about it on our end.
