### ISSUE TITLE
[Suggestion] Filter matches via lane/role

### ISSUE THREAD

**Issue by DenBla** [yasp-dota/yasp#531]
as title suggests, i think sorting match history via lane/role (i.e. Mid...) would be an excellent addition and a great tool to judge your strongest position in the current meta.

**Comment by howardc93** [comment]
Adding the filter won't be too hard, but isn't it easier just to look at the summary in the Counts tab that already groups and computes winrate for each lane?

**Comment by DenBla** [comment]
Well while it is helpful, it doesn't make it easy to see which heroes you do use (whether unconventional or common mid laners) and your match ups. Unless I'm missing something

**Comment by howardc93** [comment]
True, I guess I'll add it.
