### ISSUE TITLE
Profile > Heroes : Last = '46 years ago'?

### ISSUE THREAD

**Issue by TrentBartlem** [yasp-dota/yasp#532]
I have a new account. When I view my profile page, there's a Heroes table.

If I have never played with/against a hero, the 'Last' column says '46 years ago' instead of 'Never'.

e.g.

http://i.imgur.com/6slQoym.png

**Comment by howardc93** [comment]
Added a statement to check for the zero case.  Thanks!

**Comment by TrentBartlem** [comment]
I just noticed - is there a way to make the win percentage 'NaN' nicer as well, in those situations?

**Comment by howardc93** [comment]
I changed it to show 0.00.
