### ISSUE TITLE
Getting mmr data in json

### ISSUE THREAD

**Issue by AzZureman** [yasp-dota/yasp#535]
Can i get MMR stats of my profile in json?
something like that:
http://yasp.co/players/87594023?json=1&mmr=1
{"colo_mmr":7843,"party_mmr":7825}
Or maybe it will be realised in future?

**Comment by howardc93** [comment]
The data is already there (check under "ratings" key).

Example:
```
{
match_id: 1602764042,
account_id: 87594023,
soloCompetitiveRank: 2271,
competitiveRank: 2250,
time: "2015-07-03T09:51:41.613Z"
},
```

**Comment by AzZureman** [comment]
Yes. but, by this way i must searching last game data in all big json data. is there something to get only mmr data by one query?

**Comment by howardc93** [comment]
We just dump the data right now.  If you're interested in programmatically getting MMR you should probably take a look at our code and do it yourself using node-dota2.
