### ISSUE TITLE
cal-heatmap wide on mobile

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#539]
- [x] heatmaps (on match pages and two small ones on player pages) should be scaled to 100% viewport, and heatmap.js scales values by the current width of the image.
- [x] building map should scale to viewport.  
- [x] Building icons should also scale down to match
- [x] rating graph--scrollable and zoomable sometimes makes the page freeze?
- [x] word clouds--locked to 1000px, should scale to viewport (maximum font size may need to be scaled as well)
- [x] player/match pages--nav tabs should collapse like the navbar does
- [x] curly-cue image on faq/blog pages needs to scale to viewport
- [x]  Fix responsiveness of front page (purchase table too wide)
- [x] tables should collapse to avoid stretching the viewport.  Here are some solutions:
http://elvery.net/demo/responsive-tables/ (semi-fixed by table-responsive?)
- [ ] cal-heatmap--too wide for narrow viewports

**Comment by Aehrraid** [comment]
>  Fix responsiveness of front page
Do you mean the general landing page for everyone or the start page for logged-in users (/players/123)?

**Comment by howardc93** [comment]
The general landing page for new users.  I think the issue is the purchases table is too wide and stretches the page.  I worked around it by setting the scaling to 50% so all pages start off more zoomed out, but that's temporary.

**Comment by howardc93** [comment]
We should find a generic solution for displaying our wide tables on mobile.  Once we have one the front page isseu should fix itself.

**Comment by Aehrraid** [comment]
Ok. If i request the front page with 'no-cache' I mostly acknowledge about 5-6s waiting time for yasp.co/ html only. Afterwards, public files take approx. 2s to load. images and icons from cdn.dota2.com take  1.5s and yasp.co images/wallpaper take 1-2s.
*This is worst case*

**Comment by howardc93** [comment]
We have a separate issue for optimizing load times client side: #77

**Comment by howardc93** [comment]
Fixed the table-responsive class not working, so the index page is responsive.

However Bootstrap's solution is simply to make the tables horizontally scrollable without stretching the viewport.  It works, but we can probably display it better.

**Comment by howardchung** [comment]
merge into #368
