### ISSUE TITLE
Steam bot login not working

### ISSUE THREAD

**Issue by tarriel** [yasp-dota/yasp#540]
When trying to use a bot yasp does not seem to allow it to log in properly, after checking and playing around with the guard adding STEAM_GUARD_CODE=code but gave up as it wasn't logging in getting  { [Error: Logon fail: 63] cause: 'logonFail', eresult: 63 } Which means I need a guard code, Eventually I looked at the steam node module and worked out how to create a "shaSentryfile": sentry file, and load the sentry file and it works.  

It appears you use multiple bots that are comma separated in your names and passwords and previously the sentry files but not now as you removed the sentry files in revision dfbf249, so I was wondering how you guys get this to work now? and what I am doing wrong.  

In a possibly related issue I don't seem to be getting player names either in games, only the player number unless they have logged in.

**Comment by howardc93** [comment]
We disable Steam Guard on our accounts.

I recently disabled background fetching of player names to reduce load.

If you want to turn it back on you'll want to uncomment the block in operations.js/insertMatch that adds all of a match's players (ids anyway) to DB when a game is played, and the updateNames task in worker.js that periodically grabs their names from Steam.

**Comment by tarriel** [comment]
ok, guess that explains it...  Thanks.  Didn't realise you could turn off the steam guard.
