### ISSUE TITLE
potentially missing matches due to privacy setting changes

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#541]
After investigation of a missing matches issue reported via Google Docs:
http://yasp.co/players/64997477/

The issue here is that the missing matches were previously added (via either another user's full history), but the user in question was set to anonymous at the time.  Now they have enabled third party data, but when we get their full history, we don't re-get those matches due to that match_id already appearing in our db.

One solution is to re-add all matches when we process full history.  There are two (minor) problems with this:

* It's heavier load for us and willl lead to slower full history processing when the queue is long
* We could have the inverse problem of overwriting existing users with "anonymous", causing players to have matches disappear from their profiles.  Perhaps this is for the best, since they disabled third party data.

**Comment by howardc93** [comment]
Identified a third problem--this also overwrites existing matches with parse_status: skipped

**Comment by howardchung** [comment]
This was solved by checking the matches returned from Steam API against the matches we have for this player in the DB.  We reinsert any matches that are in the first but not the second.
