### ISSUE TITLE
memory leak on parse server

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#543]
I think parser.js has a memory leak where Java processes aren't being cleaned up.

It should kill the children when it encounters an error while parsing, but apparently this isn't picking up 100% of cases.

Also, the entire server should not be wrapped in a domain so that the parser can crash and restart.

**Comment by howardc93** [comment]
removed the domain.

**Comment by howardc93** [comment]
This is still happening.  I am attempting to isolate the problem.  It does not seem due to too many java processes, but rather node using a ton of memory.  This is weird since Node is not supposed to use more than 1.7GB at maximum.  Perhaps it has to do with running under forever?

**Comment by howardc93** [comment]
trying pm2.  I've installed it using npm, but not globally, so it is located at ./node_modules/pm2/bin/pm2

**Comment by howardc93** [comment]
pm2 exhibits the same issue.

**Comment by howardc93** [comment]
As a nuclear option we can just force a restart on an interval (every 12 hours?)

**Comment by howardc93** [comment]
I think I've fixed this by using cluster module to start a thread for each parsing core.  If an error occurs, I just crash the thread and let master resurrect it.

**Comment by albertcui** [comment]
This issue is still happening on production.

**Comment by howardchung** [comment]
It may have something to do with how I'm attempting to autodeploy.

I just changed up that code a couple days ago.

So it seems like we either have this issue or autodeploy doesn't work :(

**Comment by albertcui** [comment]
Have parser report parser version on hitting "/" ?

**Comment by howardchung** [comment]
Don't think that would help

**Comment by howardchung** [comment]
I am actually not seeing this problem.  We don't seem to increasing the number of processes.

**Comment by albertcui** [comment]
yasp@:~$ ps aux | grep "java -jar" | wc -l
22
yasp@:~$ ps aux | grep yasp | wc -l
69

But reported to go as high as 300

**Comment by albertcui** [comment]
Happening again after change to workParser"

albert@parser2:~$ ps aux | grep yasp | wc -l                                                                             
83

yasp@germangang:~$ ps aux | grep yasp | wc -l
200
