### ISSUE TITLE
parser crashed?

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#545]
hi,
When I request a match I get a 404.

Received request for match 1645966623
Getting basic match data from Steam API...
Received basic match data.
Parsing replay...
404

**Comment by howardc93** [comment]
Looks like a temporary issue.  It worked when I tried it.

**Comment by howardc93** [comment]
As an additional note: 404 means the replay file wasn't found.  This probably happens if you request a parse too soon after a match is played.  I think it also happens if you request an expired replay.
