### ISSUE TITLE
more wards placed than bought?

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#546]
hi,
In the game http://yasp.co/matches/1645966623/ radiant bought 17 observer wards and placed 18. How?

**Comment by howardc93** [comment]
Likely a ward transfer (teammate gave them a ward).

**Comment by howardc93** [comment]
Or, since you're talking about team sum--perhaps a player picked up a ward on the ground?  Not sure of opposing wards can be used.

**Comment by Turmfalke2** [comment]
We thought about that, but the only wards we bought that wasn't placed is still in the inventory of the cm at the end of the game.

**Comment by howardc93** [comment]
So it sounds like you placed two more wards than expected. . . do you know if a teammate ever picked up wards that an opponent dropped?

**Comment by Turmfalke2** [comment]
@howardc93 I think you misunderstood me.
We (Dire) bought 18 Observer wards, 16 of them were placed by cm and one by beastmaster. The last remaining ward is still in cm's inventory at the end of the game.
Radiant however bought 17 observer wards (12 veng, 5 lich), but placed 18 (13 veng, 5 lich).

This means in total considering both teams more observer wards were placed than bought, which shouldn't be possible and indicates to me a parser issue.

**Comment by howardc93** [comment]
Ah, I see.  Ward purchases are counted using the combat log.  

Ward placements (on the heatmap page) are counted by checking for new observer/sentry ward handles on every tick.  The parser maintains a set of the handles it has seen so far.

The combat log also tracks uses, but this is not accurate as of 6.84 due to the ability to use wards from a combined observer/sentry stack.

I will reopen the issue but to debug I think someone is going to have to go through the replay and watch/count carefully while comparing it to the parse output.

**Comment by Turmfalke2** [comment]
how can I get the parser output?

**Comment by howardc93** [comment]
I put the replay file in our testfiles repo to avoid it expiring:
https://github.com/yasp-dota/testfiles/blob/master/1645966623_wards.dem

You will need Maven and Java 1.7+ installed.

1.  Download that
2.  Clone YASP, `cd yasp` to enter the directory.
3.  Build the parser `npm run maven`
4.  Run the replay through the parser: `java -jar parser/target/stats-0.1.0.jar < /path/to/replay.dem > output.json`
5.  `output.json` should contain a bunch of JSON objects, one per line.

If this is too difficult I can run it myself and just put the output on pastebin so you can check it there.

**Comment by Turmfalke2** [comment]
ok, I was missing nodejs.

And I found it. First of all ward_dispenser makes things a lot more difficult, wish we had additional information for when that item gets used.
At around 48:20 in game time vengful spirit bought 3 observer wards, but in the parser output only 2 purchases events show up.
{"time":3318,"type":"purchase","unit":"npc_dota_hero_vengefulspirit","key":"ward_observer"}
{"time":3321,"type":"purchase","unit":"npc_dota_hero_vengefulspirit","key":"ward_observer"}
this is then followed by 3 use events (normal placing of the wards).
{"time":3337,"type":"item_uses","unit":"npc_dota_hero_vengefulspirit","key":"ward_observer"}
{"time":3701,"type":"item_uses","unit":"npc_dota_hero_vengefulspirit","key":"ward_observer"}
{"time":3772,"type":"item_uses","unit":"npc_dota_hero_vengefulspirit","key":"ward_observer"}

**Comment by howardc93** [comment]
Wow, thanks for the detective work!  Yes, that seems to be a replay file/combat log bug then.  We can't really do anything about that, unless we use an alternative method of getting item purchase data.

**Comment by Turmfalke2** [comment]
@howardc93 do you know whether valve is aware of that bug? The combat log sometimes not tracking things it should track feels like a pretty major bug. I assume it is also going to get used in the for the stats page of the new dota 2 stream beta? Maybe we can get it fixed that way.

**Comment by howardc93** [comment]
I don't know if they're aware.  There have been several examples of combat log weirdness, from issues like this to weird buyback gold values, etc.

I imagine the combat log is not the authoritative source for game state (VS did in fact buy and was able to use 3 wards), so fixing it is not a high priority for Valve.  The Dota 2 Watch beta/new Reborn stats probably get their data from a different source.

You could try reporting it to them, but they probably get hundreds of these every day.
