### ISSUE TITLE
Bug appearing on players page (//players/123)

### ISSUE THREAD

**Issue by Aehrraid** [yasp-dota/yasp#547]
TypeError: /root/yasp/views/query.jade:58
   56|           select.form-control(name="lane_role")
   57|             option(value) Any Lane
 > 58|             each val, key in constants.lane_role
   59|               option(value=key, selected=(Number(q["lane_role"])===Number(key)))=val
   60|            
   61|       .col-md-4

uncommenting fixed it. But other lane role-options do not appear though. (cause uncommented..)

**Comment by howardc93** [comment]
You may need to rebuild the constants (npm run constants)
