### ISSUE TITLE
Replay Parsing bug!

### ISSUE THREAD

**Issue by Jemsuper** [yasp-dota/yasp#556]
Hello! I tried to parse the following replay: 1649612998

And i got the following error:
{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read","domainEmitter":{"_connecting":false,"_handle":null,"_readableState":{"highWaterMark":16384,"buffer":[],"length":0,"pipes":null,"pipesCount":0,"flowing":false,"ended":false,"endEmitted":false,"reading":true,"calledRead":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"objectMode":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"oldMode":false,"decoder":null,"encoding":null},"readable":false,"domain":{"domain":null,"_events":{},"_maxListeners":10,"members":[]},"_events":{"finish":[null]},"_maxListeners":10,"_writableState":{"highWaterMark":16384,"objectMode":false,"needDrain":true,"ending":false,"ended":false,"finished":false,"decodeStrings":false,"defaultEncoding":"utf8","length":16384,"writing":true,"sync":false,"bufferProcessing":false,"writelen":4096,"buffer":[{"chunk":

(BUNCH OF NUMBERS WHICH I CAN'T POST BECAUSE GITHUB CRASHES)

1},"domain":{"domain":null,"_events":{},"_maxListeners":10,"members":[]},"domainThrown":false}

**Comment by howardc93** [comment]
I just made a change that prevents dumping the entire error.  Is this a Source 1 or Source 2 game?

**Comment by Jemsuper** [comment]
Source 2

**Comment by howardc93** [comment]
We can't parse Source 2 games at this point.  Sorry about that.
