### ISSUE TITLE
String Formatting Issues - Sentiment Analysis

### ISSUE THREAD

**Issue by ducthanhtran** [yasp-dota/yasp#557]
Hello,
in this [match chat](http://yasp.co/matches/1653328671/chat) Bane says "maybe he'll read", but it seems that there is a formatting/parsing error (in "processParse.js" ?) as the sentiment analysis has found the negative word "hell" as seen on the right.

**Comment by howardc93** [comment]
Words are tokenized using the following function, which is currently outside our source tree.

https://github.com/thisandagain/sentiment/blob/master/lib/index.js#L21

**Comment by howardc93** [comment]
Honestly sentiment analysis is kind of a "fun/throwaway" feature and I'm not super inclined to spend a ton of time optimizing it.  I'd be happy to accept a decent-looking PR that fixes the issue but I don't particularly want to spend time working on it myself.
