### ISSUE TITLE
Match Details - players names

### ISSUE THREAD

**Issue by Akira-Webster** [yasp-dota/yasp#558]
On the performance, purchases, farm, etc pages you do not list the name of the player for that hero. This would be useful as lot times I get to team fights and forget which of my friends were playing what. So I need to go back to the basic tab only to go back to the tab I wanted.

**Comment by howardc93** [comment]
i've thought about this.  However, the problem is that many of our tables are already quite wide and adding this column would make them even wider.  If there's a good solution or idea I can try implementing it.

**Comment by Akira-Webster** [comment]
If adding a new column is out, then I would recommend placing the name under the picture.

**Comment by howardc93** [comment]
How about changing the tooltip to the player's name and making the picture a link to their profile?

Adding the name to the column would also stretch the table a fair bit. (some people have long names!)

**Comment by Akira-Webster** [comment]
Good point the tool tips just say the hero name. The tooltip would work for me. The link to the profile would be nice but not needed.

**Comment by howardc93** [comment]
Deployed.  Hope you like it!

**Comment by RGBKnights** [comment]
I love it so much I bought some Chesse! Keep up the good work.

**Comment by albertcui** [comment]
Thanks for your support!
