### ISSUE TITLE
Match 1648607496 stuck in "Queued".

### ISSUE THREAD

**Issue by sovasin** [yasp-dota/yasp#560]
http://yasp.co/matches/1648607496

I played this match three days ago. I was an active user at the time (matches before it were parsed successfully) but this one has been stuck in the queue for days.

**Comment by howardc93** [comment]
You can manually force a parse by using the Request page:  http://yasp.co/request

I've done it for this match.

**Comment by vramana** [comment]
@howardc93  http://yasp.co/players/48835035 This is one of my friends profile. He has a lot of matches queued up from 3 days before. I tried parsing them through Request page. But I get `Error from parser: 404` . He doesn't play on Reborn client. So, source 2 is out of picture. Do you have any idea what the problem might be?

**Comment by howardc93** [comment]
They look like SEA matches.  SEA is known to have replay availability
issues sometimes.  You can check the client to see if you can download them
here, but if you can't, we can't get them either.
