### ISSUE TITLE
Chat parsing in 1v1 mid matches

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#568]
Any chat in 1v1 solo mid matches is attributed to the player on Radiant.

An example: http://yasp.co/matches/1427053693/chat

**Comment by howardc93** [comment]
There are a lot of issues with 1v1 parsing, partially due to the fact that there can be duplicate heroes in a game.  I'll leave the issue open but this will probably not be a high priority.

**Comment by howardc93** [comment]
Actually it turns out this is just a display bug.  The backing data is correct.  I'll fix this in the template
