### ISSUE TITLE
Match not parsed fast enough.

### ISSUE THREAD

**Issue by Aehrraid** [yasp-dota/yasp#569]
I played several matches (not that much) last week. The status is still "Queued". If I manually enter the ID into the request-form I receive an error
    
    We can only parse public matches where the replay hasn't expired.

Is it possible, that matches aren't parsed fast enough, if the queue is too big even if I log-in frequently/daily?

**Comment by howardc93** [comment]
Verify that the replay is available in client.

**Comment by howardc93** [comment]
People seem to have this confusion that they need to log in frequently.  This doesn't do anything, and just increases load since we re-check full history.

**Comment by albertcui** [comment]
Might be using the phrase login as "check YASP while logged in."

**Comment by Aehrraid** [comment]
Well, I don't only login to let my history be parsed. I just use yasp for what it is used. The confusion may be a result of the messages being displayed (have been displayed) on someones page saying "Log-In to receive the full history" - I cannot remember the text precisely.

Will check the availability in the client. It's possible that it has been Source2 and was marked wrong.

@albertcui agree!

**Comment by howardc93** [comment]
Yeah, I agree we should probably clarify our terminology a bit. . . anyone want to help with that?

**Comment by howardc93** [comment]
I think some people read "log in for full history", so they log in, wait a bit, think nothing's happening, and repeatedly log in.  What's actually happening is they go on the full history queue repeatedly.

**Comment by Aehrraid** [comment]
Yes. This seems to be the case, even if I understood "login" as visit the page loggedin.

What is the correct expected behaviour of the fullhistory-queue? I am not very familiar with this part of the parser-structure.

**Comment by howardc93** [comment]
It's not unexpected behavior.  We just check the last 500 games per hero for a player at the time they log in.  If they log in repeatedly, we queue them again.  No parsing involved, just a lot of API calls.

**Comment by howardc93** [comment]
Source 2 replays should be skipped and not put on the queue at all.  I suspect the replay is unavailable (404 error at the url).

**Comment by howardc93** [comment]
Need a match ID to check availability.

**Comment by Aehrraid** [comment]
In fact there are 3 ones:
http://yasp.co/matches/1653364349
http://yasp.co/matches/1653070223
http://yasp.co/matches/1652974260

**Comment by howardc93** [comment]
At this point, all three are over the 7-day expiration threshold and the replay won't be available.  Hopefully it's not a parser error.
