### ISSUE TITLE
some suggestions to improve user experience and overall design 

### ISSUE THREAD

**Issue by hadihallak** [yasp-dota/yasp#570]
*here are my main points :

* the colored border on the left side of the hero icon is unnecessarily and deleting it would provide a better overall look
* merging K,D,A columns and separating Radiant and Dire teams each to a table will provide better readability and avoids making the user lost in a lot of table cells 
* coloring rows in red and green destructs the eye and gives a sense of true and false to the information in the table
* the map in the bottom of the page takes a lot of scrolling space to reach and therefore moving it to the top will provide better user experience and less scrolling while also opening possibilities for moving the heat maps and hero's positions to this map instead of making it on a separate tab

and since i'm a webdesigner i decided to do some quick edits to the website's css and html and here is what i came up with [my edit](https://i.imgur.com/CyE444S.jpg) , [with reborn minimap](https://i.imgur.com/mLKoGJi.jpg)

ofc i only showed one page .. but i think that all of those points could apply to the whole website in general and won't take much time to code.

i have some other suggestions such as merging the rating and hero columns , adding user's name and profile picture to the top navbar when logged in with maybe his MMR and winrate but for the sake of not making this too long i'll stop here.

**Comment by Aehrraid** [comment]
My opinion to your suggestions as a regular user (it would've helped, if you clarified, which page you mean with your suggestions):
+ coloured border shows the ingame color. I find it ok to show it - even if it is not very helpful at all.
+ I think it would be a good idea to darken/brighten some of the columns on a small measure.
+ red/green again shows the ingame-faction (radiant/dire) which is nice-to-have! We should stay with that.
+ I don't think the map is needed on top of the page, as it isn't that important for the understanding of the map. I could live without it completely. Don't put it upwards!

**Comment by hadihallak** [comment]
while i agree with some of your points but  i have to point out that i'm talking about the overall design and feel of the website and mainly basic tab in the match page

as for your point about red and green showing ingame-faction (radiant/dire) , i know it represents ingame team colors and i didnt suggest removing that .. my suggestion was as you can see in the design i linked is that to move this color to player's name instead of coloring the whole row ...
 coloring the whole row gives the user a sense of right or wrong (bad or good)  when he reads the data in the table (red = bad , green = good) as if the player who has green row did good,other than that the whole coloring everything with green and red dosnt look good at least to me

**Comment by Aehrraid** [comment]
OK, I see your point. For the problem with good/bad: Actually the players from Dire ARE bad in a way ;)

I like the coloring of complete rows. But this may be a thing of taste.

**Comment by howardc93** [comment]
Working on improving match data tables.

WIP link (volatile): http://colab-sbx-244.oit.duke.edu:5000/matches/1665814868/

**Comment by howardc93** [comment]
Notes:
* It's still actually just one table.  I tried separating it out into two tables but ran into a few roadblocks.
  * The code that computes the sums and determines the "winner" would break.
  * Without fixed widths on each column the columns may not line up between the two tables.

**Comment by hadihallak** [comment]
Great work !.. looks a lot better to me now .
as for you 2nd point when i separated the table into 2 tables i've had the same issue with alignment since some player names are longer than others and i solved it by putting a width for this column so that long names will use a linebreak and the width of the column stays the same

but i dont think that's an issue anymore since now it will look like 2 tables and is a lot more readable which is  what matters for the user.
