### ISSUE TITLE
High quality yasp-icon

### ISSUE THREAD

**Issue by Aehrraid** [yasp-dota/yasp#571]
The small yasp-icon which appears in the player-roster on match-details is very pixelish (how do you say that? :D).

I would like to see a better version of it. Is there any YASP-Iconset out there?

**Comment by howardc93** [comment]
@albertcui created the icon himself.  You'll have to ask him about it.  It's the same icon we use for the favicon.

**Comment by Iparke** [comment]
Has this issue been resolved? I can quickly convert the image to .svg (scale-able vector graphics) if somebody wants to provide an exact URL in YASP or path to the image file in the repo. I can't seem to find it myself, but this was 28 days ago, so I am unsure if this just hasn't been closed.

**Comment by albertcui** [comment]
Sorry, [here](https://www.dropbox.com/sh/qrux24l5m7d7cys/AABgu4yxntXKN2uKa0YUSe9fa?dl=0) are the icons. My friend made it... I can ask for the original PSD.

**Comment by Aehrraid** [comment]
Will you integrate them into production?

**Comment by howardchung** [comment]
I am not sure what the action plan is here.

So albert added the original images.  I just picked one to use on the templates to "mark" registered users.  Do we just replace that one with a higher resolution version (which @albertcui should have access to?)

**Comment by Aehrraid** [comment]
Yes, the one on the match overview was the one I was irritated by. The favicon is not so important, I guess.

**Comment by karenkn** [comment]
I created the YASP icon for Albert—has this been resolved? Let me know if there's anything I can do.

**Comment by howardchung** [comment]
I think it's just a matter of swapping the reference to point to a higher resolution version.  @albertcui ?

**Comment by howardchung** [comment]
https://github.com/yasp-dota/yasp/blob/master/public/images/favicon-96x96.png

**Comment by albertcui** [comment]
I was taking care of this issue in the redesign branch.

**Comment by howardchung** [comment]
Can we reapply to master/ui branch @albertcui?

**Comment by howardchung** [comment]
@albertcui are you still interested in doing this?  IMO the icon is fine

**Comment by howardchung** [comment]
@albertcui said he was going to do this last weekend.  He lied.  Moving to next month lol

**Comment by albertcui** [comment]
Added SVG.
