### ISSUE TITLE
match not showing up in player history

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#574]
hi,
Yesterday I played 2 games in unranked (source 1) as tiny, but http://yasp.co/players/157506503/matches only shows one and that one is still queued.
The other match was 1676316267, dotabuff lists both of them so I assume it is not an api issue?
http://www.dotabuff.com/players/157506503

**Comment by howardc93** [comment]
match 1676374199 appears to be available.  This might be a parser crash.  I'll look into it later.

http://yasp.co/matches/1676316267 is available, but doesn't show up on your profile.  I suspect an issue with caching.  I may have restarted the server in between the time that the match was added to DB and the player caches being updated.  This is potentially a serious problem... I'm hoping to be able to drop caching when we upgrade to SSD storage.

**Comment by howardc93** [comment]
To resolve the problem I flushed your player cache, but will leave this issue open until we can figure out why it happened in the first place.

**Comment by Turmfalke2** [comment]
I was able to parse 1676374199 without a crash. At first glance the json file looks fine.

**Comment by howardc93** [comment]
Hmm, it may have just failed a few times in the queue then.  We retry with
a doubling interval so if unsuccessful the first few times it may take a
while to get parsed.

**Comment by howardc93** [comment]
Requesting 1676374199  worked.  

I changed some code in `scanner.js` that could have potentially caused us to miss matches.  If we did miss matches, they shouldn't show up at all, rather than just not showing up on your profile.

Open a new issue/reopen this one if you see missing matches again.
