### ISSUE TITLE
Identical heros leads to incorrect calculations

### ISSUE THREAD

**Issue by tarriel** [yasp-dota/yasp#575]
Where people are playing the same hero eg. 1v1 mid some things are calculated incorrectly take a look at http://yasp.co/matches/1678272927 the overview is most likely correct but the farm and items are attributed to the radiant hero

**Comment by howardc93** [comment]
Yes, this is a limitation of the combat log.  It simply gives a unit as "npc_dota_hero..." but no other information, so we can't tell who it's referring to when there are multiple heroes of the same name in the game.
