### ISSUE TITLE
More abbrs (deffinition for records and their respective numbers)

### ISSUE THREAD

**Issue by RadulescuAlin** [yasp-dota/yasp#577]
The Records and Compare page could use more abbr tags.
Some of the numbers and records are intuitive, but others are rather not.

Examples:
Loss record and it's number (I have no idea what do those mean. I suppose it's the match you lost the hardest, but I don't really understand the number)
Stop (same as above)
Comeback(same)
Throw(same)

Also, I don't see how "pick order" is relevant.

**Comment by howardc93** [comment]
Yeah, we should probably add tooltips at some point for those.

I am using the same set of keys to define display categories for histograms, records, and compare.  That's why things like "pick order" are included even though it's a pretty meaningless record.

**Comment by howardchung** [comment]
rolled into #454
