### ISSUE TITLE
tab-tooltips on match-pages

### ISSUE THREAD

**Issue by Aehrraid** [yasp-dota/yasp#578]
On every match page of match which are not parsed, the tooltip for the parsing-specific tabs is "This data will be available when the replay is parsed.". For matches which cannot be parsed because there is no replay (too old) or source2 was used.

For the first case would suggest a new tooltip like 'This data is not available. The match is too old'. This clarifies why there is no parsing-specific data and specifically why there WILL be no data in the future.

**Comment by howardc93** [comment]
I don't think this is necessary, but we can see what @albertcui and @nickhh think.

**Comment by nickhh** [comment]
If it's an easy fix I think we could do it. More information (almost) never
hurts :P

**Comment by howardc93** [comment]
I just don't like the part where we have to hardcode in a date.

**Comment by Aehrraid** [comment]
> I just don't like the part where we have to hardcode in a date.

Well, it is one date which will never be outdated, because it is over.. I don't think there will be any changes concerning replay versions.

Another idea would be to categorize matches/replays into categories like pre-replay-era, source1-replays, source2-replays. I don't know, if this is necessary, but I can imagine, that there may be changes in functionality between source1- and source2-replays.

**Comment by nickhh** [comment]
I think hard-coding dates like the boundary between pre-replay, s1, and s2
is a good idea.

**Comment by Aehrraid** [comment]
It is - if implemented - still a good idea to externalize and centralize these values into a text-file or database, though.

**Comment by howardc93** [comment]
Yeah this is definitely something that should go in `sources.json`

**Comment by howardchung** [comment]
Technically replays can be parsed at any time, as long as someone has the file.  We don't publicly expose upload-parsing, but it can be done on the backend.  I'd prefer to keep it general and just state that the data will be available when the replay is parsed (even if the replay is no longer available from Valve).
