### ISSUE TITLE
Posistions not working in Firefox

### ISSUE THREAD

**Issue by Jemsuper** [yasp-dota/yasp#579]
http://imgur.com/gq99w8Q

**Comment by howardchung** [comment]
@albertcui or @nickhh want to try tackling this?

**Comment by Turmfalke2** [comment]
Using firefox 37.0.2 - never had this issue.

**Comment by howardchung** [comment]
Can anyone else repro this?

**Comment by Jemsuper** [comment]
I don't seem to get it anymore either. I used to have it on every single match but not anymore

**Comment by howardchung** [comment]
In that case I will close the issue :)
