### ISSUE TITLE
professional games, single player games?

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#581]
hi,
I just had a look through the professional in hope of finding some of the ti games, what I instead found left me a bit confused. What makes a game professional for yasp? From what I can tell these games are always parsed.
I feel like yasp should make sure the games have at least some minimum value before they get parsed
For example here we have a professional game, consisting of one player sitting in the hero selection screen for 53mins.
http://yasp.co/matches/1703682125/

**Comment by howardc93** [comment]
The API returns a field called `leagueid`.  We consider a match to be professional if leagueid>0.  It's not perfect but should capture all the important games (but also includes some "junk").
