### ISSUE TITLE
enable ssl

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#584]
At some point we should switch to using ssl.

https://www.startssl.com/?app=1 can give us a free signed certificate.

**Comment by howardchung** [comment]
Another option, but won't be available until Q4 2015:

https://letsencrypt.org/

**Comment by mbax** [comment]
[WoSign](https://buy.wosign.com/free/) also provides free certificates, and the interface doesn't become non-English until after you have the cert.

**Comment by PeterBooker** [comment]
Namecheap's PositiveSSL certificate seems like a good deal at just under £6 per year: https://www.namecheap.com/security/ssl-certificates/comodo/positivessl.aspx

Disclaimer: I have only used the EssentialSSL Wildcard cert, so I don't have any first hand experience with it.

**Comment by howardchung** [comment]
I'd prefer to wait for free if we can do so.  The nice thing about YASP is that we have no "private" data, so it wouldn't be too bad even if someone's cookie got swiped and they were able to log in as someone else.

**Comment by Aehrraid** [comment]
I would also wait until letsencrypt is online. This sounds really progressive and easy to use.

**Comment by rainje** [comment]
General Availabily for LE should be this month. I got into beta and it's working fine. 90 days certificate but you can renew them really easily and it should be automated later.

**Comment by howardchung** [comment]
public availability looks to be december 3.

**Comment by howardchung** [comment]
I will probably be doing this once LE is publicly available (might need some help from @albertcui to set up nginx, etc.)

**Comment by howardchung** [comment]
so it looks like we actually already support https (https://yasp.co works).  I think this is something that GCE does.  What we don't do is force https (forward all http traffic to https, but this should be easy).

However, any page with Dota images will not have the green lock icon (since images are currently fetched via http from Valve's CDN.  Someone between YASP and the end user could modify those images to show up as something else.  

Weirdly https on the CDN works, but throws an untrusted certificate warning.(https://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_sb.png)

We would probably need to serve them ourselves to achieve full HTTPS.

I don't think we actually need to use LE.

**Comment by howardchung** [comment]
I swapped to using the current protocol for images and it looks like it works:
https://yasp.co/players/88367253

So we just need to force https.  Is this something we should do at the Node or nginx level?

**Comment by howardchung** [comment]
@albertcui try this maybe:
https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL-

**Comment by albertcui** [comment]
Done.
