### ISSUE TITLE
javascript parser (rapier)

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#587]
If anyone wants a bigger, more technical challenge!  You can get down into the nitty-gritty of the replay's binary format and play with fun things like bit shifting!

Work on this is currently happening over on the `source2` branch under `js_parser`.

The clarity and manta projects will likely be useful references, since they're currently on the cutting-edge of figuring out the replay format.  We'd just have to port their code into JavaScript.

Building a parsing library in JS has some advantages:

1.  It can set up the framework for in-browser parsing!  Cool things can probably be done with that.
2.  JavaScript doesn't currently have a Dota 2 replay parsing library, but it's probably one of the most popular and up-and-coming langauges!  Be a pioneer!
3.  It also makes our stack 100% JavaScript!  Consistency is good.

You also get to help name the parser when we finish it! (another Dota item name?)

Parsing all the dems/packets currently takes about 20 seconds.  I think it can be significantly improved by skipping packets without a listener :)

You know, if I'm feeling bored and productive maybe I'll write up a detailed guide to replay parsing and cover all the structures :)

STATUS:
- [x] decide on name :)
- [ ] add package.json
- [ ] move to new repo
- [ ] entities
- [ ] string tables
- [x] combat log
- [x] cgameinfo (epilogue)
- [x] gameevents
- [x] all chat

**Comment by howardchung** [comment]
Pity that bit shifts in JS are slow (since they involve converting from double to int and back again).

**Comment by howardchung** [comment]
Potential names:
mango
tango
dagon
rapier
orchid
butterfly
mjollnir
necronomicon
atos
vyse
radiance
shiva
satanic

**Comment by howardchung** [comment]
Once development is a little farther along we'll want to move it into its own repo and stabilize an API.

So far, it's pretty straightforward.

The user creates a new Parser, which inherits from  eventemitter, and supplying a stream or buffer. 

http://stackoverflow.com/a/8898528

The user listens for events that have the same name as the proto message the data is derived from.  So this would parser.on('CDemoPacket'), parser.on("CUserMessageSayText2"), etc.  They get back the message corresponding to the protobuf message name they requested.

When the user invokes start() (a function we define).  we begin parsing the replay.  The event handlers the user set up are called when we parse a message with that name.

```
var parser = new Parser(streamorbuffer);
parser.on("CUserMessageSayText2", function(msg){
console.log(msg);
});
parser.start();
```

**Comment by howardchung** [comment]
Unfortunately due to the same-origin policy, usage in the browser is limited to parsing replays from the same domain that served the site (or those with a CORS header set).  For us, this means that a user on YASP can only parse a replay that we serve ourselves (which we can't do since proxying replays from Steam over to the client costs us a lot of bandwidth).

It would be cool to have a browser-based parser where either us or the user could supply a URL of a replay and pull/parse it locally in the browser.

I suppose there's still the sticking point of replays from Valve being compressed with bz2.  We'd have to decompress it in the browser as well, which is annoying :P

**Comment by howardchung** [comment]
Parser is refactored into a library and API stabilized!

TODO:
- [ ] decide on name :)
- [ ] add package.json
- [ ] entities
- [ ] string tables
- [ ] combat log
- [ ] cgameinfo (epilogue)
- [ ] gameevents
- [x] all chat

**Comment by howardchung** [comment]
combat log, gameinfo, gameevents working

**Comment by Aehrraid** [comment]
Why not lotusorb?

**Comment by howardchung** [comment]
maybe lotus

**Comment by Aehrraid** [comment]
Simply lotus is difficult. There are several other big Software products with this Name.

**Comment by howardchung** [comment]
Maybe we should pick one of the more distinctive items then

**Comment by Iparke** [comment]
Sacred Relic.

**Comment by howardchung** [comment]
Preferably, one word :)

**Comment by howardchung** [comment]
@albertcui and I like "rapier".

It's a lightweight parser that throws (exceptions) if you use it incorrectly :)

**Comment by howardchung** [comment]
A cool use of rapier, coupled with client side match table rendering, is the ability for users to parse their own private lobby replays in-browser and get back a match report.  It would be simliar to @devilesk 's replay viewer, but with just numbers and tables instead of an animated map.

**Comment by howardchung** [comment]
closing this issue and moving rapier code to own repo

**Comment by Aehrraid** [comment]
Like that name!
