### ISSUE TITLE
sentry and dusts are not tracked as sets

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#591]
hi,
Currently the tooltip for sentries and dust bought(http://yasp.co/matches/1730394899/purchases) ends with "(x2)" which, would imply that to get the real amount of sentries/dusts you would you have to multiple the number by 2. This is not the case, so I suggest just removing the (x2).

**Comment by howardchung** [comment]
Hmm.  I see your point, but I want to make it clear that we've manipulated
the value by x2.

**Comment by howardchung** [comment]
We are just applying a standard *2 to sentries and dusts since they come in stacks of 2.

We are not doing it for observers since they now come in stacks of 1, but this means the reported number of observer purchases for pre 6.84 games is half of what it should be.

**Comment by howardchung** [comment]
This is UI related so @albertcui should make the call :)
