### ISSUE TITLE
npm run dev eats my RAM

### ISSUE THREAD

**Issue by Aehrraid** [yasp-dota/yasp#599]
Hi,

I am working on the code base for several weeks now. After a short break I took, the yasp-server eats all my resources now. If I start 'npm run dev' my free RAM goes from 80% to 0% and forces killing of other relevant processes :( (running on a v-server with 4-8 GB RAM)

Any ideas what the problem is. I only saw this issue https://github.com/yasp-dota/yasp/issues/588.

**Comment by howardchung** [comment]
You mean the issue only occurred after that merge?  I would advise monitoring to see which process is eating memory.

Does it happen immediately or gradually?

**Comment by howardchung** [comment]
my devbox is only 2GB RAM and I have not encountered problems

**Comment by Aehrraid** [comment]
I just pulled the latest version. I takes about 10 sseconds gradually..

**Comment by howardchung** [comment]
Can you identify the process causing the problem?  (with top?)

**Comment by Aehrraid** [comment]
Good idea. I looked at it and first there appeared lots of node processes with <1% mem. After the parser started there appeared at least 10-15 java-processes. This is clarity, I guess.

I remember that the parser didn't work anyways in the beginning. Is it possible that the parser - if it works - simple needs a lot of memory when it's working?

**Comment by howardchung** [comment]
You could check Kue to see if there are a lot of jobs.
 localhost:5000/kue/active

**Comment by Aehrraid** [comment]
There are 1300 parsing jobs in the queue. This appears on /status

**Comment by howardchung** [comment]
you can flush them with redis-cli

redis-cli flushall if you have nothing else you care about in redis

**Comment by Aehrraid** [comment]
I am quite familiar with redis, so I will have a look. Thanks for the hint!

Is it logical that the RAM exceeds if there are many jobs in the queue, though?

**Comment by howardchung** [comment]
Well, a large queue uses RAM (although 1300 is not that many). The parser
should only process as many as once as you have cores.

**Comment by albertcui** [comment]
There seems to be a bug where much more parsing processes run than # of cores.

**Comment by howardchung** [comment]
Are we seeing this on production?

**Comment by howardchung** [comment]
As a workaround if you don't need to run the full stack you can run a specific process with (for web):
`nf -j Procfile.dev start web`

**Comment by howardchung** [comment]
fixed?

**Comment by Aehrraid** [comment]
It is working properly now - even without your workaround. I will tell you if the problem occurs again. Thanks!
