### ISSUE TITLE
Feature Request: Pre-Match Player Reporting

### ISSUE THREAD

**Issue by Iparke** [yasp-dota/yasp#603]
**User Story (happy day):**

The user enters Dota 2 matchmaking. Once the player has been assigned to a game, the user navigates to now.yasp.co and is greeted by a search bar. The user enters their own name in the search bar and hits enter. yasp.co detects that the player is currently in a game. yasp.co serves the user a page with an aggregation of data from all players in the game. The user can see listed values for other players: solo/party mmr, average kda/gpm/xpm, common heroes, common roles, etc. This allows the user to put his/her teammates down even before the game has begun OR track who he/she can count on for some free kill gold during the game. Also allows the user to ban Meepo, making Meepo players useless.

I don't think anybody else has done this yet for Dota. 

Technical reasons why I believe it is possible:
- IIRC, there's a file created locally when a user enters a game. The text file contains the names of all the other players.
- Steam/Dota 2 tells you when users are in a state of "in-queue" or "in game."
- I am able to stalk the enemy teams' profiles while waiting for loaders by clicking on their name in the load bar.

Technical reason why I believe it is not possible:
Nobody has done this yet. Why has nobody done this yet?

**Comment by howardchung** [comment]
There's no public matches live API (although there is one for pro games)

Somebody did something similar where you can paste in data from console output, but that's annoying.

Also our data for randomly selected players is incomplete.  Dotabuff would be a more comprehensive source of randomly selected players.

**Comment by howardchung** [comment]
It MIGHT be possible for players who've added a bot to track mmr.  We'd spoof a spectator request and try to pick up the other players in the game from the data.  Not sure if it would work.

The lack of data issue remains.

**Comment by howardchung** [comment]
I think node-dota2 only simulates a connection to the GC.  I don't think anyone has figured out how to programmatically connect to an actual game server

**Comment by Iparke** [comment]
It's not supported yet.

"Is there a WebAPI for current games in progress?
Not yet! But this is a excellent suggestion."

Ah well.

**Comment by howardchung** [comment]
where is that from?

**Comment by Iparke** [comment]
The FAQ portion of the Web API on the dev forums. It's in the first post towards the bottom.
http://dev.dota2.com/showthread.php?t=47115

**Comment by howardchung** [comment]
Valve has been incredibly bad at working on the API.  I wouldn't expect it
anytime soon :(
