### ISSUE TITLE
Full match history processed bug?

### ISSUE THREAD

**Issue by keisuke89** [yasp-dota/yasp#604]
Was checking out a friend's yasp profile with the "full match history processed" tick, but almost half his games are missing.

http://yasp.co/players/57400013 (408 wins / 377 losses / 3 abandons)
http://www.dotabuff.com/players/57400013 (804 wins / 704 losses / 3 abandons)

**Comment by howardchung** [comment]
Perhaps match sharing was turned off at the time he logged in?  Ask them to
make sure it's on and then log out and back in.

**Comment by howardchung** [comment]
If that doesn't work I will investigate further :)

**Comment by keisuke89** [comment]
He doesn't have match sharing switched off, he played another 2 games today (1 win 1 loss) and his yasp profile is now 409 wins / 378 losses / 3 abandons, while his dotabuff is 805 wins / 705 losses / 3 abandons.

**Comment by howardchung** [comment]
So it looks like new matches are being added fine.  I'll manually force
another full history request for him.

**Comment by howardchung** [comment]
What I meant is that if it was off at the time he first logged in, then the
full history fetch would have failed.

**Comment by howardchung** [comment]
Looks like a caching issue.  The full history was already taken but for some reason the cache was not updated properly.

Record is now 820-731-4
