### ISSUE TITLE
Heat Map issues (browser compatibility, sometimes requires refreshes to load)

### ISSUE THREAD

**Issue by TrentBartlem** [yasp-dota/yasp#605]
The heat map on http://yasp.co/matches/xxxxxxxx/positions works in other browsers, but not Safari.

**Comment by howardchung** [comment]
We don't officially support Safari (at least, I don't have a Safari device to test with).

Maybe @albertcui might want to take a look, but Safari users are a pretty small percentage.

**Comment by eblis** [comment]
This also seems to be buggy on Opera as well. When I first load the page it won't show the heatmap, but if I Ctrl + F5 the page afterwards the heatmap shows just fine.

Maybe it'll work in Safari if you Ctrl (or Cmd ?) + F5 it ?

**Comment by howardchung** [comment]
Yeah I actually get this sometimes on Chrome but I haven't been able to pin
down a cause.  It usually works within a few refreshes.

**Comment by gortiz** [comment]
It doesnt work on Firefox for Android (it seems the heat layer is 4 times
bigger than the map image)

2015-09-10 21:41 GMT+02:00 Howard Chung <notifications@github.com>:

> Yeah I actually get this sometimes on Chrome but I haven't been able to pin
> down a cause. It usually works within a few refreshes.

**Comment by howardchung** [comment]
I don't know how many of these I can repro.  I'd be happy just getting to
work consistently on Chrome.

**Comment by ahockersten** [comment]
I did some testing. I used this url: http://yasp.co/matches/1842378160/positions
Firefox for Android 41.0 on Xperia Z3 Compact: OK
Firefox for Android 41.0 on Nexus 7 2014: OK
Google Chrome for Android on Xperia Z3 Compact 45.0.2454.94: OK

Google Chrome 45.0.2454.101 on (Fedora 22) Linux: OK
Firefox 41.0 on (Fedora 22) Linux: OK

Firefox 39.0 on Windows 10: OK
Firefox 41.0 on Windows 10: OK

**Comment by howardchung** [comment]
Yes, I haven't seen the no heatmap bug for a while.

To get the map to dynamically resize we'd probably have to call the redraw function when we get an "onresize" event.  Could be implemented but not very high priority.

**Comment by ahockersten** [comment]
I don't think listening to the "onresize" event is enough, unfortunately. "onresize" only triggers when the browser window resizes. The map element could be resized as part of normal page load or in response to some other element resizing (this won't happen in the current code I think), and that won't trigger the "onresize" event.

I've managed to reproduce the "no heatmap" bug on Chrome 45 on Linux now, unfortunately. All I have to do is reload the page with "ctrl+r". If I reload by pressing enter in the URL bar it always works, but never with ctrl+r.

**Comment by howardchung** [comment]
Just tried ctrl+r with chrome 45 linux and the heatmap still worked.  Doesn't seem to be 100%

**Comment by gortiz** [comment]
I can confirm it also works on Firefox on Android

2015-10-09 13:55 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by ahockersten** [comment]
@howardchung the reason ctrl+r doesn't work "sometimes" (or all the time on my computer, apparently) turned out to be a race condition. If the map hasn't loaded when the heatmap gets created the heatmap uses the wrong height (this can be seen in the inspector).
