### ISSUE TITLE
instant per-match automatic analysis/advice

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#608]
An idea that might be cool:

After each match is parsed, write logic that can instantly analyze certain metrics based on hero played and performance.  For example, we can look at LH/EFF@10, then inform the player that their performance in that area was lacking for the hero they played.

Things we can look at:
* LH/EFF
* Kill drought (gap in kill times) for a ganking hero
* farming drought (low gold earned delta over an interval) for a farming hero
* Flaming in all chat
* lack of warding/min
* Excessive pinging
* Courier feeding
* low ability accuracy
* items not used but bought
* slow item timing (might have to be specific hero-item pairs)

Might involve having to hardcode some heroes as "supports", or we could use Valve's "support" designations, although those might be out of date.  Alternatively, we could use our data to compute averages for each hero and compare against that.  We'd probably want to compute that on an interval/startup and save to redis or something.

**Comment by howardchung** [comment]
We could run this on each player_match in computePlayerMatch in `compute.js` and cache it.  Then add a new tab called "Analysis" where we give the advice for each player :)

**Comment by WTFKr0** [comment]
Is this data should be personnal ? I mean accessible only by the logged player ?

**Comment by howardchung** [comment]
Nope, all data is public
