### ISSUE TITLE
We use cookies for sessions, ads and analytics.

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#618]
bit of nitpicking, this is from the bottom of each page on the left of the cheese goal.

**Comment by howardchung** [comment]
are you referring to the ads reference that we should remove?

**Comment by Turmfalke2** [comment]
yes

**Comment by howardchung** [comment]
In that case I'll roll this into #614

**Comment by Turmfalke2** [comment]
Oh I somehow didn't saw that issue.. my fault

**Comment by howardchung** [comment]
nah, it was a good catch (I didn't remember the footer until you mentioned it)
