### ISSUE TITLE
Source 2 Game With Coach Parsing/Display Misalignment

### ISSUE THREAD

**Issue by xiij** [yasp-dota/yasp#619]
It appears as though if the radiant team has a coach the parsed data appears to be misaligned on the dire team.

In a match I played yesterday (http://yasp.co/matches/1782087294), the radiant team had a coach. The data on the 'Overview' page appears to be fine (but that's probably because it's only data from the Steam API not from the replay parse). When you transition to later tabs such as 'Performances', you can notice that most of the data for Ember Spirit (Pink / first dire player) is blank, additionally, the data for Windranger (Green Gray / second dire player) appears to be the Ember Spirit's data ('Utilization' under 'Performances' is prime example). This trend continues, however all the data from Clockwerk (Brown / last dire player) is missing.

**Comment by howardchung** [comment]
Yeah, this is probably a bug with how we're reading entities, not simply a display issue.  I'll take a look after work.

**Comment by howardchung** [comment]
Think the PR will fix this, but we probably won't go back and reparse matches.  Once it's deployed you can manually reparse it if you want.
