### ISSUE TITLE
Button on match lists/pages to request a parse

### ISSUE THREAD

**Issue by Brian-McG** [yasp-dota/yasp#621]
This may not be as much of an issue now that track time has been increased but it was in the past.
During university term time I only play on the weekend and may not go onto yasp that weekend. Which results in an untracked. The issue arises when I do want to see the stats of a game but now I am untracked. It may be nice to parse the last day of games you have played when you become re-tracked again.

**Comment by howardchung** [comment]
You can manually request those matches.  I'm not sure if we're going to
implement something that scans for the last week of matches on retrack.

**Comment by Brian-McG** [comment]
Oh yes, true, I forgot about that functionality. What about some button on the match list which can be pressed to request a parse perhaps?

**Comment by howardchung** [comment]
We'd want to funnel users through the captcha flow so we maybe could do a
link that prepopulates the match id in the request form

**Comment by gortiz** [comment]
You could add two things to make the request easier:

   - On the request page, add a the list of recent but not parsed matches
   the logged used has
   - On the overview page of a recent but not parsed match, you can add a
   link that redirects you to the parse request page with the match id placed
   in the request form

Both options look great

2015-09-10 21:37 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
I don't think we want to add to the request page (it would also slow it down due to the time required to fetch matches), but I think we can put a "request parse" button on match pages that links to the request form with the ID pre-filled.

**Comment by Brian-McG** [comment]
:thumbsup:
