### ISSUE TITLE
First blood isn't listed in the objectives for Source 2 matches

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#622]
What it says in the title :)
The first blood objective isn't listed in the objectives page for Source 2 matches.

**Comment by howardchung** [comment]
Possible that the chat event is longer emitted or changed names.  I'll
check later.

**Comment by howardchung** [comment]
Based on this thread:
https://www.reddit.com/r/DotA2/comments/3kfjxq/no_first_blood_banner_in_reborn/

It appears that Source 2 doesn't fire a first blood event.  If they add it back it should auto-fix :)

**Comment by eblis** [comment]
Seems to be working again now :)

**Comment by howardchung** [comment]
Yeah it just looks like Valve added back the event (I didn't change the code)
