### ISSUE TITLE
don't include implied kill streaks in streak counts

### ISSUE THREAD

**Issue by jgrayson676** [yasp-dota/yasp#629]
Currently the kill streak counts also include every lower kill streak that was achieved on the way (for instance if you earned a dominating streak it will also show that you earned a killing spree). While this is true to what actually happens in game, in my opinion it's somewhat confusing and not particularly useful. I suggest that you only show the final kill streak earned before a non-aegis death or game end.

For example a game where a player earned dominating streak then died, mega kill streak then died, and ended the game with a godlike streak currently shows up as:

| Hero | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Queen of Pain | 3 | 3 | 2 | 1 | 1 | 1 | 1 | - |

I would suggest you show it as:

| Hero | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Queen of Pain | - | 1 | 1 | - | - | - | 1 | - |

**Comment by howardchung** [comment]
Technically doable but requires some processing of the combat log data.

We would also need to set a cap of 10 to prevent losing those streaks.

It would also mess up the lifetime aggregations for players.

**Comment by howardchung** [comment]
I suppose what we could do is continue to use the same data for aggregations, but for match display, process the data to filter out only the longest individual streaks.

**Comment by howardchung** [comment]
I think the trick is to iterate through the object backwards (10 to 3) and add 1 to the that killstreak every time the value increases.

I was trying to solve it by iterating forwards and getting nowhere :)

Almost feels like an interview question lol

**Comment by howardchung** [comment]
Code would go right about here:
https://github.com/yasp-dota/yasp/blob/master/compute.js#L180

**Comment by lomash** [comment]
I've never worked with JS, so don't know about the proper syntax. But, could something like this work?

    {
      var current_count = 0;
      var prev_count = 0;
      var temp_kill_streak = {}; // create new array similar to p.kill_streaks and initialize to zero
      for (var key in p.kill_streaks){
        current_count = p.kill_streaks[key];
        if (current_count < prev_count){
          temp_kill_streak[key-1] += 1; // Since current_count will never be less than zero, we don't need to worry about the array index being out of bounds.
        }
        prev_count = current_count;
      }
      
      // Assign values from temp_kill_streak to p.kill_streaks
      for (var key in p.kill_streaks){
        p.kill_streaks[key] = temp_kill_streak[key];
      }
    }

**Comment by howardchung** [comment]
Yeah, something like that might work.  It may be more elegant to just iterate backwards though :)

**Comment by lomash** [comment]
Something like this?

    {
      var temp_kill_streak = {}; // create new array similar to p.kill_streaks and initialize to zero
      var arr_length = p.kill_streaks.length;
      var count = arr_length - 1;
      while(count > 0){
        if (p.kill_streaks[count] < p.kill_streaks[count-1]){
          temp_kill_streak[count-1] += 1;
        }
        count--;
      }
      // Assign values from temp_kill_streak to p.kill_streaks
      for(var key in p.kill_streaks){
      p.kill_streaks[key] = temp_kill_streak[key];
    }

**Comment by howardchung** [comment]
The input is an object, not an array.  I like your second solution though, it could probably be adapted to fit the input.

Example:
```
{"3":3,"4":3,"5":2,"6":1}
```

Caveats:
* The keys may not necessarily be in numerical order, so you may have to sort them.
* I don't think it's possible to "skip" numbers, but you may want to code defensively to handle that case.  Perhaps generate the array your second function expects by sorting the keys in the object and then extracting the values from the object in that key order.
* I think the keys used to go beyond 10 for longer streaks.  However, I think this changed recently to cap at 10.  You may need to handle both cases.

**Comment by howardchung** [comment]
For consistency I'd say we should just stick with what we have currently.
