### ISSUE TITLE
Heroes that buyback and die (dieback) are only counted once

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#637]
When a hero dies, buys back and dies again he's only counted once in the Teamfights score panel.
For example this match http://yasp.co/matches/1790488413/teamfights, teamfight 10, Dazzle.

**Comment by howardchung** [comment]
Yeah, we actually should have the data but display the skull icon for 1+ deaths.

I suppose we could put a little (x2) in the corner or something, but would require some html/css wranging.

I'll give it to @albertcui

**Comment by eblis** [comment]
The score column also says 4-2 when in fact it was 5-2 if you count Dazzle twice..

**Comment by howardchung** [comment]
That can be changed to account all deaths instead of just +1 if the hero died at least once.  However it means that aegis deaths, WK ults, and meepo clone deaths may be multi-counted.

**Comment by howardchung** [comment]
Don't think @albertcui wants to do this.  I'm okay with a PR adding "x2" to death column.

I don't think we are going to change the versus count.
