### ISSUE TITLE
Hero game counter and filter doesn't work properly

### ISSUE THREAD

**Issue by gortiz** [yasp-dota/yasp#646]
I recently create [my profile on YASP](http://yasp.co/players/62276451/) (yeah, i am in the trench xD) and I found some inconsistencies on my profile page. For example, right now, it says that my most played hero is AM with 12 games (which doesnt have many sense) and it also says I played Rubick 10 times, but if I change the filter and select only 6.84c, it says that my most played hero is Rubick with 18 (!!!) games!

**Comment by howardchung** [comment]
Caching issue.  We have some bugs in the cache right now that can lead to weird things happening.  I flushed it and things look better now.

I've got some pull requests out that should help with the problem, but we may not deploy for a couple of weeks.
