### ISSUE TITLE
Add EFF@10 as histogram

### ISSUE THREAD

**Issue by gortiz** [yasp-dota/yasp#647]
I thin EFF@10 is a very interesting metric and I would like to see it on an histogram. Is it possible?

**Comment by howardchung** [comment]
Yeah, should be fairly easy.  I was thinking about adding it earlier today.

**Comment by enche** [comment]
Other early game eff times would be nice too (e.g., EFF@5 & EFF@15).

**Comment by howardchung** [comment]
Technically we could add as many as we want.  (see the patch I added) At some point it's going to be histogram overload though.
