### ISSUE TITLE
Feature: minimap replays

### ISSUE THREAD

**Issue by dancek** [yasp-dota/yasp#657]
Hi!

I started toying with the idea of showing a quick replay of hero positions on a minimap. I thought the `posData` used for generating heatmaps was a time series, but it turned out to be a histogram...

I have something like this in mind (this is just mock data and only one hero):
[![Example video](http://fat.gfycat.com/DetailedZestyIchneumonfly.gif)](http://gfycat.com/DetailedZestyIchneumonfly)

Here's some test code that I used. http://codepen.io/dancek/pen/rOeZNp

Is this at all feasible? The position time series could be quite low resolution both in terms of coordinates and timestep. But obviously this would take up some storage. Say, 8 bits per coordinate every second for all 10 heroes and a 60-minute match: 2 bytes * (60*60) * 10 = 72kB uncompressed. Make that every 5 seconds and it's 14kB.

**Comment by howardchung** [comment]
We do strip out the time data from posData since we were only interested in making a heatmap of the data.  So by storing it as {x:{y:value}} we were able to compress the data quite a bit at the expense of losing the time dimension.

Current uncompressed parsed match data is about 200kb, so even 72kb would be a pretty heavy cost.  

5 seconds feels like too low resolution for an animated map.  Heroes can travel pretty far in 5 seconds (especially those who can blink).

**Comment by dancek** [comment]
I'll try to make some tests with real-life data when I have time. I guess this won't happen unless I can show that you get something usable with low storage requirements.

**Comment by howardchung** [comment]
actually two bytes per second per player isn't too bad.  Average match length is 40 minutes so it ends up being 48kb.

**Comment by howardchung** [comment]
If you want to mess around, check out `parser.js` and the e.x, e.y section to see what we currently do with the data.  You could possibly just create a Buffer and shovel bytes in there with .writeUint8().

To decompress, you'll probably want to look at compute.js#computeMatchData to implement unpacking that data into something more sane :)

**Comment by dancek** [comment]
Good ideas there! I'm not sure when I'll get a chance to investigate further, though.

MongoDB apparently knows how to handle binary data (BinData) internally, and it also has compression out of the box. The data is actually a good candidate for lossy compression--if only I knew of a suitable algorithm that's available as an easy to use library :)

**Comment by howardchung** [comment]
Some discussion about this on reddit that might be interesting (assuming you're not the person who posted, lol):

https://www.reddit.com/r/DotA2/comments/3ltixu/rdota2_broke_yasp_by_getting_everyone_to_check/cv9ax7o

**Comment by dancek** [comment]
No, I'm not active on reddit. This guy looks like he's capable, though, so it might be a good idea to ask for his help. :)

**Comment by howardchung** [comment]
Re: compression--I wouldn't worry too much about it.  MongoDB actually transparently compresses our data using Snappy, which achieves a pretty good ratio with high performance.   Pre-compressing the data would probably add decompression time without too much more benefit.

**Comment by howardchung** [comment]
This is probably going to be too expensive to do at scale (and the next cost-cutting measure is probably to drop the laning heatmap completely and just save the lane position).

Tools already exist if we want to see an animated replay:
http://devilesk.com/dota2/apps/replay/viewer/

**Comment by albertcui** [comment]
We could temporarily store in Redis. Thoughts?

**Comment by howardchung** [comment]
Then the data has limited retention (so it has a limited lifetime, like the
original replay).

This also isn't something we aggregate on so it's value is limited long-term

**Comment by albertcui** [comment]
Yes, but I think people are more likely to look at it on YASP than download
the replay and watch the replay.

**Comment by howardchung** [comment]
Well going off 70k parses a day and 48kb per match we need 3.3gb of RAM per
day of retention.

**Comment by dancek** [comment]
Given the popularity of yasp.co I don't think this is a realistic feature to have.

However, I might* well host a private yasp instance that only tracks my friends, and for that use case the storage would not be an issue. So this ticket should stay closed, but if someone were to implement this as an optional feature, why not.

* ...but with my one-year-old twins, I won't have the time.
