### ISSUE TITLE
Create an aggregated word cloud (one-off blog post?)

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#661]

**Comment by howardchung** [comment]
We actually kind of do this already with the players/all page.  It covers the last 200 matches (up to 2000 player_matches).

However we need to be careful about publicly announcing it since we can't cache players/all anymore with mongocache :(

**Comment by howardchung** [comment]
Looks like we're dropping mongocache so maybe we could announce this.  Is 200 matches too small of a sample size/

**Comment by howardchung** [comment]
size set to 250 matches.  It may be better to do this as a one-off thing (just save the generated image and blog about it)

**Comment by howardchung** [comment]
Best to do this with the data dump (maybe the 500k matches dump).  Nick maybe since he has the data already?

**Comment by howardchung** [comment]
I wrote to code to extract this data. `node dev/wordcount 1000` (where 1000 is the number of matches to count words for).

Over to @albertcui for writing a blogpost/generating a word cloud.

**Comment by howardchung** [comment]
Script no longer works with Cassandra.  If we want to do this we can rewrite the script, or use a data dump (maybe BigQuery)
