### ISSUE TITLE
Show item owner if the owner isn't the player holding the item

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#665]
Not sure if this is possible via the API but it would be nice if the owner of the items was shown if the item in question does not belong to the player holding it.

I've had a match where I've died while trying to build bloodstone after disassembling mana boots and my teammates picked up my items, but in the overview window it looks as though they bought the items instead.

Or if that's not possible maybe just gray out muted items instead, if that's possible ?

**Comment by howardchung** [comment]
API doesn't show this.  Might be possible with replay parsing.

**Comment by howardchung** [comment]
I think this is probably a little too specific for us to do.  If someone wants to implement it we can consider a PR but closing this for now.
