### ISSUE TITLE
Lookup matches with specific items

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#669]
If I want to lookup something like all matches in which I bought a rapier for instance, there is no way to do that currently. 
I can lookup my win rate, average timing, buy rate etc. for that item but not see which games I bought that item in. Could be a good addition.

**Comment by howardchung** [comment]
I can probably add that.  Would you want it to query over the endgame items (available for all matches), or "any game where I bought at least one" (only available for parsed matches?)

**Comment by lomash** [comment]
Probably the parsed ones since I would be interested in the ones I bought, rather than the complete set in which I might have picked up a rapier from the ground.

**Comment by howardchung** [comment]
Okay, but keep in mind that parsed matches cover a much smaller set (since we can't include matches before a user joined)

**Comment by howardchung** [comment]
I suppose this should be a multiple select field, so you can query for one or more items?  Our framework doesn't work so well for OR queries atm

**Comment by howardchung** [comment]
Implemented!
