### ISSUE TITLE
pick order is broken?

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#672]
In the ranked game http://yasp.co/matches/1814647170 radiant picked 1 to 5 and dire 6 to 10?

**Comment by howardchung** [comment]
Yeah, it seems to have gotten messed up since Reborn.

It might now be the order in which the player enters the game (hero select), but not 100% sure.  Someone would have to do the detective work of running the parser on a replay, inspecting the output and trying to match it to what's going on in the actual game.

We could just remove the whole thing--opinions?

**Comment by skyfaller** [comment]
Well, if you could get it working properly, pick order is a very useful stat to have! It would be nice to see if e.g. my strategy of first picking Bloodseeker is better than waiting until the end and counterpicking.

**Comment by howardchung** [comment]
Wrong data might be better than no data, though, so perhaps it's best to drop it until someone comes up with a new reliable way to determine pick order.

**Comment by steve9164** [comment]
Yasp Link: http://yasp.co/matches/1817853012/performances

Actual Pick Order:
1. Mirana
2. Skywrath Mage
3. Earthshaker
4. Tusk
5. Lina
6. Ursa
7. Spirit Breaker
8. Windranger
9. Spectre
10. Slark

Load Order (found watching replay at 0.25 speed):
1. Windranger
2. Mirana
3. Slark
4. Spirit Breaker
5. Tusk
6. Ursa
7. Earthshaker
8. Skywrath Mage
9. Lina
10. Spectre

Yasp "Pick" Order:
1. Windranger
2. Mirana
3. Slark
4. Earthshaker
5. Spirit Breaker
6. Ursa
7. Tusk
8. Skywrath Mage
9. Lina
10. Spectre

Yasp order roughly lines up with the load order, especially the first 3 and last 2, which were spaced further apart (in load time) than the ones in the middle, which are slightly scrambled.

**Comment by howardchung** [comment]
Thanks for the detective work.  How close together were the ones in the middle?

**Comment by steve9164** [comment]
All within a second

**Comment by howardchung** [comment]
Yeah, I'm not surprised the order isn't being detected properly then.

In either case load order isn't a particularly useful stat--anyone object
to just removing it?

**Comment by howardchung** [comment]
I'm currently in the middle of a major rewrite and migration to SQL #582 .

As part of that I'll be getting rid of the pick_order data.
