### ISSUE TITLE
distributed parse client

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#676]
Currently parse workers are completely independent and stateless, acting as servers rather than clients.

They just respond to http GETs that give them a URL and return the JSON parsed data for that match.

This means a couple of weird things:
* yasp-core has no idea how much processing power a given worker has, and just blindly assumes some configurable number (currently 8 parallel parses)
* We can't adjust the number of parallel jobs on the fly without stopping, updating our config, and restarting.  There is an issue in kue for this (https://github.com/Automattic/kue/issues/447) but it hasn't been implemented.

Reversing the parse flow means that we open up an endpoint on yasp-core that RECEIVES parsed data uploaded as POST.

Parse workers get a URL and key (to prevent abuse) set in config and GET from the endpoint, requesting work.  (This may be annoying, I don't think kue supports the ability to "pop" a single job off the queue) yasp-core sends back the URL of the replay file. That job should be marked "active" in kue so we don't reassign it to another parse worker.  The parse worker uses that URL, downloads/parses the file, and POSTS the resulting JSON back to the same endpoint.

yasp-core then marks that job as complete when it receives a POST that contains the data for that match.

We might need to add a timeout for the job if the parse worker never finishes it.

Advantage:
* We can add/remove parsers dynamically without touching yasp-core.
* Potentially could open it up publicly so anyone with a server can contribute parsing power.  We would likely to need to implement some kind of double-checking to prevent abuse, though.  If we made a leaderboard and implemented some kind of scoring system, we might get a lot of interest.
  * Making sure everyone is running the correct, latest version of the parser may be annoying

Disadvantage:
* We have to set config values on each node we want to add.
* How to handle case when queue is drained?  Do we send back a null value for the replay URL, and client tries again in some timeout interval?

**Comment by Medowar** [comment]
You mention that yasp has the number of concurrent Processes hardcoded somewhere. Can you please tell me, where that value is getting defined?

**Comment by howardchung** [comment]
Currently here:
https://github.com/yasp-dota/yasp/blob/master/config.js#L39

It's configurable with a .env file setting though.

**Comment by Medowar** [comment]
Thanks. I did turn down the number from 8 to 4 for my Parsing Server for yasp.co

**Comment by howardchung** [comment]
Actually that may not do much with the current code.  We still send 8 simultaneous requests from the server.  #582 should fix this and I'm hoping to get that out by the end of the month.

**Comment by howardchung** [comment]
Fixed in #685
