### ISSUE TITLE
fix npm install on npm run deploy-parser

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#677]
according to @albertcui npm install doesn't work, which means autodeploy should not be running.

Temporary mitigation is to remove npm install from command, but this means parsers won't automatically get dep updates.

**Comment by Mysrt** [comment]
doesn't seem to work from me either and I get a syntax error from foreman when i try to 'npm run dev'

**Comment by howardchung** [comment]
This issue should only affect npm run deploy-parser (and I'm not sure it actually happens, @albertcui hasn't confirmed).

You're probably having an issue with your setup.  OS, npm, node versions?

**Comment by howardchung** [comment]
As a workaround you can run stuff with just the `node` executable but you lose the nice logging, the auto restart, and the ability to start multiple services with a single command.

**Comment by Mysrt** [comment]
yeah spent a hours last night and i think i have it mostly running.  I'm using an older version of osx, (mountain lion), so a lot of the scripts didnt work for me and the version of node I was using didn't seem compatible with some of the dependencies.  Regardless I think i have it going more or less.  

I've got the sample db loaded up and I can access the matches, etc, in it through the web client.  Having trouble getting parsed matches/running the parser but i haven't tried much yet today.  Pretty much left off there last night.

**Comment by howardchung** [comment]
For information, our dev and production environments are:

OS: Ubuntu 14/15
Node: 0.12 (although we want to upgrade to 4.1.1 soon)
npm: 2+ (have not tested with 3)

**Comment by howardchung** [comment]
Also keep in mind #582 .  We may not do this for another month or two (BIG change), but something to keep in mind if you want to continue working with the latest code :)

**Comment by howardchung** [comment]
Likely one of the parse workers has node 4+ on it, which means it won't build.  As part of #582 we will upgrade all nodes to node 4+.
