### ISSUE TITLE
MM Stats Shows Europe as a Stat

### ISSUE THREAD

**Issue by liboz** [yasp-dota/yasp#678]
http://yasp.co/mmstats

Europe is a category. Should that be Russia?

**Comment by howardchung** [comment]
I think it's actually Luxembourg.

https://github.com/dotabuff/d2vpkr/blob/c5fd001420f887e12af01989e05539f7187abbde/dota/scripts/regions.json#L48

**Comment by liboz** [comment]
Yea, you're right. I had a mind blank and forgot Stockholm is Russia and Lux is Europe West
