### ISSUE TITLE
split histograms/trends into subpages

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#679]
While @Aehrraid 's work has somewhat improved this by not rendering all the charts at once, the fact remains that the page still loads the data for all of them and this can take quite a while to do.  I think we need to split up each histogram/trend into its own subpage.

While this means we can't do the toggle-comparing, I'd really like those pages to load faster (and it's also kind of wasteful to send all the data when the user probably isn't interested in all of the histograms/trends).

**Comment by albertcui** [comment]
This is an argument for moving to a SPA with an API.

**Comment by howardchung** [comment]
not necessarily, we can have the server render a diff page for each chart.

**Comment by albertcui** [comment]
Yes, not necessary, but the implementation would likely be cleaner and
would not require a full page load. Also, comparisons WOULD be possible
with SPA.

**Comment by howardchung** [comment]
True.  It's going to be a pretty heavy move to go full SPA, although I suppose either match or player pages would be a reasonable place to start.

**Comment by howardchung** [comment]
This probably wouldn't be very hard to do with Jade, though.  We can keep everything loaded in memory, but just add a sub-navbar for each category (or even keep the buttons we have now, but make them links instead and get rid of show all).

As for the route it can be like players/:account_id/:page_name/:key_name?

From routes/players we pass the key name we're currently interested in, and Jade template renders only the data for that key.
