### ISSUE TITLE
add timeout to parsers to avoid stuck jobs

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#684]

**Comment by paralin** [comment]
How are you getting around the rate limits on replay fetching?

**Comment by howardchung** [comment]
account limit: you can probably guess
IP limit: by outsourcing salt fetching to the cloud

**Comment by howardchung** [comment]
fixed in https://github.com/yasp-dota/yasp/commit/f592e80a168305f4fc9462eb96d3c4fa4ac63a26

however this is in sql branch and may not go into production for quite a while.  Also debating moving to distributed clients #676  so the timeout may be moot.
