### ISSUE TITLE
"socket hang up" error when trying to parse a replay

### ISSUE THREAD

**Issue by spikernum1** [yasp-dota/yasp#687]
Replay in question:
1827969204

Link:
http://yasp.co/request#1827969204

It is the only replay from recent games that has this issue.

**Comment by howardchung** [comment]
Doesn't look like the replay is available.

You can go to:
http://yasp.co/matches/1827969204?json=1

Find the line that says:
url: "http://replay122.valve.net/570/1827969204_177147849.dem.bz2",

And check the URL to see if you can download the replay.

Or you could try downloading it from the client.

Please reopen if you can confirm that the replay is downloadable.
