### ISSUE TITLE
healing crosstable

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#689]
Not hard to add, but do we have room to add it without information overload?

From google form:
```
Would be really nice to have healing stats in the same way we have damage stats ! For supports :D Thank you for the awesome website.
```

**Comment by howardchung** [comment]
note: we have healed data but not healed_by in the current schema.  So we might have to add that and provide it only for future matches.

**Comment by evaryont** [comment]
> you rarely if ever heal enemies

Oracle messes that up. :disappointed: Though it might be better to sweep that under the rug? :laughing:

**Comment by howardchung** [comment]
The thing is that if we do it like the damage/kill crosstables, the values will almost always be 0/0, unless somebody is playing oracle.

So it only really makes sense to make the two axes a team/the same team, becase healing largely happens between teammates.  If we do this then we should only have one value per cell since the second value should also be in the same table.

**Comment by howardchung** [comment]
Closing this unless somebody pushes for it
