### ISSUE TITLE
heatmaps

### ISSUE THREAD

**Issue by howardc93** [yasp-dota/yasp#69]
http://www.patrick-wied.at/static/heatmapjs/

We'll need to gather the data from the replay.  We can do just hero position at intervals, deaths, or something

**Comment by howardc93** [comment]
Depending on how often we sampe, this could create very large parsed files.

**Comment by howardc93** [comment]
I think a individual heatmap of each hero's position over the game would be too storage-intensive, but we could do a shared one for all heroes.

**Comment by howardc93** [comment]
Could also heatmap things like ward placement

**Comment by stuki** [comment]
Could it maybe be done so that you can request that if certain parameters are fulfilled it stores maybe 10 matches, and completes a heat map for a specific hero/player over all those matches? So that you could maybe compare the warding between a team that is playing defensively and offensively or farming patterns between those two as well? Because I feel that just a generic heatmap doesn't really give you that much

**Comment by howardc93** [comment]
I feel like maps would have to be match specfic.  Aggregation doesn't help much when 10 games could be highly variable (super offensive one game, super defensive another, result is just a fairly even looking map).

**Comment by stuki** [comment]
I was not thinking it would appear in every match, but more as a service in the app that you can invoke if you wonder about how you statistically could do things. And I mean that it would find the matches from all the parsed matches you get
On 10.2.2015 17:49:34, Howard Chung <notifications@github.com> wrote:
I feel like maps would have to be match specfic. Aggregation doesn't help much when 10 games could be highly variable (super offensive one game, super defensive another, result is just a fairly even looking map).
&mdash;

**Comment by howardc93** [comment]
We could probably offer an aggregation feature that produces combined heatmaps, if we have heatmap data parsed for every match.

We're still exploring how storage intensive this kind of data might be though.  It probably depends on how often we take a reading.

**Comment by howardc93** [comment]
Comments from display player lanes issue:

A simpler heatmap.  We sample the user's location in X/Y coordinates every tick, and take a mean or median every 5 minutes.  We store this data in db.

On client side, we box up the map into chunks (top, middle, bottom, radiant jungle, dire jungle), and determine which box the database value falls into.  We do a 5 minute increment timeline showing position in each interval.

https://github.com/skadistats/clarity/issues/18#issuecomment-49137489
