### ISSUE TITLE
missing ability_upgrades data

### ISSUE THREAD

**Issue by jgrayson676** [yasp-dota/yasp#690]
Match [1830789184](http://yasp.co/matches/1830789184) both Slardar and Razor are missing skill build data. [Dotabuff](http://www.dotabuff.com/matches/1830789184) does have this data, so I would think it's not an issue with the data from Valve. Looking at the JSON for that match shows that `ability_upgrades` is undefined for both Slardar and Razor.

**Comment by howardchung** [comment]
Yeah I've seen this a few times.  I've got no idea what causes it since we just insert the data directly into mongodb.  My best guess is that the initial data from API doesn't have it and it gets added later.  Try requesting the match through the form and see if it shows up (may need to dump cache)

**Comment by howardchung** [comment]
hmm, I re-requested and dumped the cache and it's still happening.  I will have to take a further look, although we're kind of freezing code in master due to #582.

**Comment by howardchung** [comment]
I cannot repro this on devbox :(

**Comment by howardchung** [comment]
I tried deleting and re-requesting the match on prod and it's still happening?!

**Comment by howardchung** [comment]
So far:

* The API data is fine
* Requested on devbox, match is fine
* Deleting match from prod and re-requesting causes the same issue with the same players missing ability_upgrades data

**Comment by howardchung** [comment]
CONFIRMED: data is getting messed up in Kue.  We currently save the entire match into Kue job payload, and write it back when we insert parsed_data.  So data is fine after initial insert but wrong after parse.

I just re-requested the match and then spam-checked the match in Mongo.  It was okay (10 players with ability_upgrades) and then went down to 7 after a while.

**Comment by howardchung** [comment]
fix: Just write parsed_data and match_id after a match.  Avoids anything bad happening in Kue (unless the match_id got messed up somehow...)

Repaired match:
http://yasp.co/matches/1830789184

**Comment by howardchung** [comment]
Root cause:

Array.slice returns a SHALLOW copy of objects in a NEW array.  I thought it made a deep copy, and thus cached players were getting manipulated (in order to do aggregations), losing the ability_upgrades data.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
