### ISSUE TITLE
dynamically scale parse power with cloud provider APIs

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#693]
Something that can automatically spin up/down new instances based on our queue size.

Made easier by #676

**Comment by howardchung** [comment]
We should also detect if the queue is growing due to insufficient parse power or other reasons (Steam having issues, etc.)  We don't want to spin up more instances if it's just because we can't download replays (although the additional instances would help deal with the resulting backlog)

**Comment by howardchung** [comment]
We could also attempt to do this based on current match flow rate.

**Comment by Mysrt** [comment]
who is your host? if you're using aws you get a lot of this stuff for free if you configure it correctly.

**Comment by howardchung** [comment]
The cloud instances are flexible and whoever offers the best price.  AWS
can be relatively expensive, so we're not using them at the moment for
parsing instances.

**Comment by howardchung** [comment]
#763 should fix this
