### ISSUE TITLE
Leveled skills don't show up for some players

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#694]
Not sure when this started happening, I've noticed this the last few days. It looks as though the leveled skills don't show up for some players.

Example matches:
http://yasp.co/matches/1835252593 - TB and Kunkka have no leveled skills in the overview page.
http://yasp.co/matches/1835478273 - Lina is missing the skills.
http://yasp.co/matches/1835531980 - Brood missing the skills.

**Comment by howardchung** [comment]
yep, this is #690 .  I just pushed a fix, re-requesting the affected matches will solve the problem.  Please reopen if you see this again (I already did the three listed above)

**Comment by eblis** [comment]
Nice.

Sorry, I had a look before raising the issue and I didn't see anything similar, but I only looked at open issues :)
