### ISSUE TITLE
Radiant bottom T2 tower is too close to the stairs

### ISSUE THREAD

**Issue by eblis** [yasp-dota/yasp#697]
In the Overview page -> Buildings panel, the bottom T2 radiant tower is too close to the stairs, too close to the T3 radiant tower than it is on the actual map.

The picture shows it as being to the left of the patch of trees, whereas the tower is actually to the right of the trees.

Similarly, the top T1 and T2 radiant towers are not aligned with the T3 tower, they're a bit to the left, too close to the leftmost forest.

Also, the radiant T1 mid tower is maybe a pixel too much to the left-side patch of trees ?

Also, the radiant mid barracks aren't properly aligned.

http://yasp.co/matches/1840070956/
http://devilesk.com/dota2/apps/interactivemap2/

**Comment by howardchung** [comment]
values are tweakable here.  You could use browser dev tools to figure out where they should be and submit a patch adjusting the numbers

https://github.com/yasp-dota/yasp/blob/master/public/js/buildMap.js

**Comment by eblis** [comment]
Will do ... but tomorrow, too late now for dev work here :)

**Comment by eblis** [comment]
Sorry, forgot about this until now :(

brmr: [top: 72.5%, left: 20%]
bmmr: [top: 73.5%, left: 21.5%]
t2br: [top: 86%, left: 46%]
t2tr: [top: 52%, left: 11%]
t1tr: [top: 39%, left: 11%]
t1mr: [top: 56%, left: 40%]
