### ISSUE TITLE
Bring back MMR leaderboard

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#701]
Make leader board of top X (100?) active YASP users. This will be useful for users to see the parsed matches of high skilled players.

Add a histogram of MMR.

**Comment by howardchung** [comment]
With Valves new model we could add a background task to get MMR for up to 3.7 million players.

**Comment by howardchung** [comment]
I wrote a script to fetch one-time MMR for all players in db, and a query to get number of players in each bucket of 100 MMR.

So for distribution we just need to generate a nice c3 histogram, and run the script the to fetch MMR data for more players.

**Comment by howardchung** [comment]
Histogram=implemented

Don't know if we're still planning to do a leaderboard.

**Comment by howardchung** [comment]
Data collected for 660k players.  However, most of these data points are not updated regularly (we only fetch MMR after every ranked match for players who have signed in) (73k players).

So if we were going to do a leaderboard we should probably limit it to those with MMR less than 2 weeks old or something.

We also discussed automatically tracking the top 100/1000 players.

**Comment by howardchung** [comment]
Think this is associated with #602 .

I think we can create a "Players" page with two tabs, Pros and Highest MMR.  We list the pro players and the top 500/1000 MMR with links to their profiles.  Optionally enable auto parsing for those players.
