### ISSUE TITLE
Items in inventory are visually collapsed

### ISSUE THREAD

**Issue by evaryont** [yasp-dota/yasp#702]
For instance, my friend when he builds force staff, will always keep it in his 4th item slot.

In example: [Match 1848421474](http://yasp.co/matches/1848421474), he plays the Shadow Shaman. The TP boots are in item slot 1, so that looks correct. However the force staff is in the 4th item slot and the euls is in the 5th item slot.

So, we'd both like some spacers filling in the empty inventory slots. However, I don't know if the inventory slot index is currently tracked?

**Comment by howardchung** [comment]
Actually, it looks like it is.  Each player_match has "item_0", "item_1", etc.  It looks like the value is 0 if there is no item.

Shouldn't be very hard to check if val===0 and put a spacer there.

https://github.com/yasp-dota/yasp/blob/master/views/match/match_index.jade#L61

Anyone want to give it a shot?

**Comment by ahockersten** [comment]
Fix for this in #707

**Comment by howardchung** [comment]
@albertcui says this is WontFix (see #707)
