### ISSUE TITLE
Link to be able to download a replay.

### ISSUE THREAD

**Issue by evaryont** [yasp-dota/yasp#703]
I'm not sure how YASP would go about it. If the URLs are predictable, it be as easy as filling in the match ID into a simple string template. If the URLs aren't predictable, the full URL might have to be stored with the parsed replay.

I'm not suggesting that YASP stores the unparsed replays themselves. So the link would only be valid for, what, 14 to 21 days? But I think it would be nice anyways, and hiding the links on old matches.

**Comment by howardchung** [comment]
We've thought about this already.  How it works:

Each replay url is a mostly predictable string with a few variables:
* cluster.  This is available through the webAPI, and relates to the region in which the game was played.
* match_id.  Obviously, identifies the match.
* replay_salt.  This is a randomly generated value for each match specifically to prevent the replay URL from being trivially guessable.  Valve used to include this data in the API, but removed it a few years ago.  As part of the pipeline, we get the replay salt by emulating a Dota 2 client and requesting a replay download.  We save the resulting match URL into our database, so we do have it (although it will return a 404 if the match is too old).

The concern is that by making an obvious download link, we increase the load on Valve's servers and they might not like that.

The data is actually already available (just not super obvious).  If you append `?json=1` to the match URL and ctrl-F for "replay", you should find the link.

**Comment by frozenspider** [comment]
`?json=1` doesn't seem to be working anymore: https://www.opendota.com/matches/3499441200?json=1 is essentially the same as https://www.opendota.com/matches/3499441200

**Comment by howardchung** [comment]
The data is now on the OpenDota API, see https://docs.opendota.com for
details
