### ISSUE TITLE
Items: Avg Timing does not sort correctly

### ISSUE THREAD

**Issue by GIider** [yasp-dota/yasp#706]
Go here and sort by "Avg Timing": http://yasp.co/players/39088211/items?hero_id=50

The timing is not ascending, for example:

-1:01
-1:19
17:05
...
34:41
3:29
34:50
...
152:42
15:43
0:00

**Comment by howardchung** [comment]
I suspect this is due to it actually being NaN.  I think i fixed it in sql branch but will keep this open until I can confirm

**Comment by howardchung** [comment]
once matches are fully imported I will check this

**Comment by howardchung** [comment]
looks fixed
