### ISSUE TITLE
Test twilio integration against new endpoint to ensure our ssl libraries still work.

### ISSUE THREAD

**Issue by Mysrt** [yasp-dota/yasp#708]
Ahoy!

Security is always top of mind for us at Twilio. That’s why on December 1st we’ll be updating api.twilio.com with a SHA2-signed certificate, a significant improvement in encryption technology.
Though the vast majority of applications will not be impacted in any way, there is a possibility that applications using older SSL client libraries may run into compatibility issues. To verify that your application is compatible with the new certificate, we’ve provided a test API endpoint at api.twilio.com:8443. Please note this endpoint uses a different port from the current default port of 443. Make sure you specify that port in your Twilio SDK.
The validation endpoint will be deprecated on December 1st, 2015 when the new SHA2-signed certificate is deployed to the main Twilio API endpoint (port 443). Please let us know at help@twilio.com if you have any questions. We’re always listening and we’re here to help. 

Cheers, 
Team Twilio

**Comment by Mysrt** [comment]
lol fuck im an idiot

**Comment by howardchung** [comment]
Lol we are planning to do ssl for YASP soon #584
