### ISSUE TITLE
Lone Druid's bear's items produce errors when hovered in match view

### ISSUE THREAD

**Issue by ahockersten** [yasp-dota/yasp#709]
Here's a screenshot:
![screenshot from 2015-10-09 10-05-49](https://cloud.githubusercontent.com/assets/186791/10388824/92c12bb8-6e6d-11e5-8bbf-c45da29c4d01.png)

**Comment by howardchung** [comment]
match link?

**Comment by ahockersten** [comment]
Any match with Lone Druid, AFAICT. Here's one example: http://yasp.co/matches/1839183189
