### ISSUE TITLE
[LSI] no more combat log events

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#711]
With the patch today replay files no longer contain the CMsgSource1LegacyGameEvent.  This is leading to no data for a lot of sections (although other sections are working fine).

Combat log data is probably still available in the replay somewhere. . . investigating.

We COULD try to reparse these games once this is resolved--probably by requeueing all jobs past a certain match_id.

Since this is a fairly high priority we probably need to apply it to master, deploy new code and then merge it into development `sql` branch later.

Help is welcome :)

**Comment by howardchung** [comment]
Investigations:

Testing using https://github.com/yasp-dota/rapier:

There are three combat log related messages in the protobufs:
```
DOTA_UM_CombatLogData = 468;
DOTA_UM_CombatLogShowDeath = 470;
DOTA_UM_CombatLogDataHLTV = 554;
```

I'm attempting to decode this packet with the proto CMsgDOTACombatLogEntry.

First glance output looks sane-ish.

**Comment by howardchung** [comment]
Looks like all the required changes are on clarity side.

**Comment by spheenik** [comment]
I'll have something in a few hours.

**Comment by howardchung** [comment]
fixed in https://github.com/yasp-dota/yasp/commit/ef022ba1066bbcdbefc61e15bd59362c5763c4cc

If autodeploy is working properly the parser should auto-update and no changes for yasp-core side.
