### ISSUE TITLE
new combat log types

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#712]
```
+    "20": "DOTA_COMBATLOG_NEUTRAL_CAMP_STACK",
+    "21": "DOTA_COMBATLOG_PICKUP_RUNE"
```

We are already getting rune data by reading ChatEvents, but neutral camp stacks are new :)

Neither appears to actually show up in replays yet but we should keep checking new replays.

**Comment by howardchung** [comment]
with 6.86:
```
+	DOTA_COMBATLOG_REVEALED_INVISIBLE = 22;
+	DOTA_COMBATLOG_HERO_SAVED = 23;
+	DOTA_COMBATLOG_MANA_RESTORED = 24;
+	DOTA_COMBATLOG_HERO_LEVELUP = 25;
```

**Comment by howardchung** [comment]
in the combat log
```
+	optional bool is_heal_save = 41;
+	optional bool is_ultimate_ability = 42;
+	optional uint32 attacker_hero_level = 43;
+	optional uint32 target_hero_level = 44;
+	optional uint32 xpm = 45;
+	optional uint32 gpm = 46;
+	optional uint32 event_location = 47;
+	optional bool target_is_self = 48;
```

**Comment by howardchung** [comment]
new unit order:
```
+	DOTA_UNIT_ORDER_PATROL = 29;
```

**Comment by howardchung** [comment]
It doesn't seem like Valve has added these new types to replay files :(  Will keep checking (after patches)

**Comment by Subzidion** [comment]
Is there an update on this? Would they say if they added these types to replay files?

**Comment by howardchung** [comment]
I checked a replay yesterday and did not see anything new.  I doubt they would announce it, we just have to keep trying

**Comment by Subzidion** [comment]
How difficult would it be to pull the "Total Camps Stacked" stat from the profile? You could probably pull that from everyone like you do MMR.

**Comment by howardchung** [comment]
It's possible, but I'm not sure how useful of a stat it is in isolation (i.e. not per match).

I've also heard varying things about its accuracy.

**Comment by Crazy-Duck** [comment]
It's not a functionality that's present at the moment, as far as I know. We'd need to nethook the client to find out what proto message is sent to the GC to obtain the player's stats

**Comment by Crazy-Duck** [comment]
This might be the relevant proto message: ClientToGCPlayerStatsRequest. It's the one they use to fetch the player card info and I suspect the same one they use to fetch player profile stats. I'll see if I can make a PR with the implementation in the coming week

**Comment by howardchung** [comment]
It looks like creeps stacked are in the PlayerResource entity.  I submitted a PR adding that data

**Comment by Crazy-Duck** [comment]
@howardchung added it to node-dota2 as well. See [dev](https://github.com/RJacksonm1/node-dota2/pull/322) for the pull

**Comment by howardchung** [comment]
I'll close this issue as there's no definite action to be taken here.

We just need to occasionally check the replays for new combat logs/entity properties occasionally.

Devnote:

You can do this by running the parser service, then using curl to POST a file to it:
`curl --data-binary @filename.dem http://localhost:5600`

Current behavior is to write combat logs with a type number > 19 to stderr of the Java process, which gets printed to the parser.js output.
