### ISSUE TITLE
Improvements to the "request parse" button

### ISSUE THREAD

**Issue by ahockersten** [yasp-dota/yasp#716]
If you go to any parsed match, there's still a "request parse" button. Example: http://yasp.co/matches/1842378160
![screenshot from 2015-10-14 08-55-05](https://cloud.githubusercontent.com/assets/186791/10476870/ca3e9ade-7251-11e5-81f0-c8f35a634eb2.png)

It would be nice if the state of this button reflected actual match parse status. It could have these states:
[Request parse] current button, no changes
[✓Match parsed] green? grayed out? Button disabled, when match has already been parsed)
[O Parsing match] yellow? grayed out? Button disabled, when match is currently being parsed. That 'O' is a spinner btw :)
[X Replay unavailable] red? grayed out? Button disabled. When match is definitely not available (i.e. too old, and/or we have already tried to parse it but failed due to it no longer being available). I haven't checked if the data for determining if this is stored anywhere. If it's not it might not be worth bothering with.

Another possible improvement that could be part of this would be to allow clicks on the button to directly start the parsing, by popping up the captcha inline somehow.

I'm willing to work on a PR for this, assuming you like the idea.

**Comment by howardchung** [comment]
Already parsed matches might want to be reparsed (if we had a bug or if we upgrade the parser)

Checking if a job is already in the queue is kind of annoying.  There's no built-in functionality for it.

**Comment by ahockersten** [comment]
Reparsing matches is an edge case though. You could still reparse the match by going to the request page and entering the match id manually.

A solution could be to change the [match parsed] button to read [reparse match] (or perhaps [request reparse] when hovered. That doesn't work on mobile, of course. 

Do you have any data on how often matches get requests to get reparsed? I know I requested reparses of several matches when I first started using yasp because I didn't understand that they had been parsed already.

**Comment by howardchung** [comment]
No, I don't currently break down those numbers.  Usually we get 600-700 parse requests a day, but don't know how many are reparses.

**Comment by howardchung** [comment]
one easy fix would be to change button appearance if match is already parsed.  maybe just change the color and the text to "REPARSE"
