### ISSUE TITLE
Tooltip shown when hovering Lone Druid's items on the Overview tab shows an error

### ISSUE THREAD

**Issue by bqx** [yasp-dota/yasp#718]
I noticed an error messaging shown instead of the item information when hovering over an LD player's items on the Overview tab.

Example match: http://yasp.co/matches/1868068921/

Shows the following error message in Chrome:
`parserError:SyntaxError: Unexpected end of input`

Looks like there's an error parsing some JSON.

**Comment by howardchung** [comment]
this is https://github.com/yasp-dota/yasp/issues/709

@ahockersten fixed it but we just haven't redeployed yet--I'll do that now
