### ISSUE TITLE
If a player abandons, his hero's skill build stops updating

### ISSUE THREAD

**Issue by brebernjak** [yasp-dota/yasp#720]
Example [here](http://yasp.co/matches/1885793828), Razor left the match.

**Comment by howardchung** [comment]
Looks like this is what the API gives us.  Dotabuff shows the same data: http://www.dotabuff.com/matches/1885793828

Not much we can really do about it.

**Comment by brebernjak** [comment]
Can't you update that once/if you parse the replay?

**Comment by howardchung** [comment]
Possible but not sure.

The data might be in the replay but if it is I am not sure how to get it
(would require investigation)

Secondly if we did figure it out we'd probably put it on another tab since
the first one is reserved for API-only data without parsing.

**Comment by brebernjak** [comment]
It must be somewhere in the replay because you can see the spell levels when watching it in client.
But it does seem it would be too much hassle to implement.

Thanks for the response!
