### ISSUE TITLE
bot match parse misalignment

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#722]
Reported through Google form:
```
When parsing bot matches, yasp assumes that the humans are playing as radiant, and the data parsed only matches correctly for radiant teams. For example, human player 2 playing as dire will have his stats/purchases/kills/spells used/whatever displayed for the bot player2 on the radiant team, and bot player 2 will have his stuff displayed for human player 2..
```

Need a bot match ID to test with

**Comment by Iparke** [comment]
Found these people randomly by searching for "play mostly bots" on Reddit.

This match from 2 days ago, Radiant humans: http://www.dotabuff.com/matches/1888255748
This match from 6 days ago, Dire humans: http://www.dotabuff.com/matches/1879291597

**Comment by howardchung** [comment]
Hmm, based on:
http://yasp.co/matches/1879291597/performances

It seems like the teams are inverted, so the radiant players have parsed data for the other 5 players, and vice versa.

My guess: bot team is set to neither 2 nor 3, so we don't detect it as a real player slot and it gets screwed up that way.  Might just go back to taking the first 10 player slots as the 10 players in game.

**Comment by howardchung** [comment]
Actually it looks like the problem is that the data from the API is inverted.  The human players always come first, even if they are on dire.  Looks like we just have to sort the players by player_slot before we do anything else with them.

**Comment by howardchung** [comment]
Turns out the replay file will also have the human players first, even if they are on dire (this is only a problem with co-op vs bot matches where the humans are dire).  Therefore all the slot ids are inverted.  We fill in the "slot" field for each data point, and index into our array of 10 to populate the parsed data.

However, we blindly assign player_slot by index.  Perhaps we need to have player_slot emitted by the parser and assigned by workParser instead.

**Comment by howardchung** [comment]
Actually it's probably a lot simpler just to have the players array from API sorted prior to sending for parse.
