### ISSUE TITLE
Zoomable graphs

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#725]
'''
A very desirable feature would be for the graphs of lasthits/gold/xp per member to be able to be zoomed in on for a particular time. To get a better idea of how farm during the first 20 minutes was.
'''

Easy, just need to toggle JS option

**Comment by howardchung** [comment]
added, but the problem remains that the x-axis does not rescale.

**Comment by albertcui** [comment]
This was why we did not have zooming in the first place ;p
