### ISSUE TITLE
Detect dota_player_auto_repeat_right_mouse for APM

### ISSUE THREAD

**Issue by ASPePeX** [yasp-dota/yasp#728]
Having "dota_player_auto_repeat_right_mouse" enabled artificially inflates actions per minute, as can be seen on Necro here: http://yasp.co/matches/1900655585/actions
A solution from the top of my head would be to ignore movement actions that don't differ significantly from the previous one.

**Comment by howardchung** [comment]
Here is the content of the message:
https://github.com/SteamDatabase/GameTracking/blob/40d096d14643c8a1c5ae29be3230642c900f40e7/Protobufs/dota/dota_usermessages.proto#L508

So it does appear that we get position data of the order, but I am a little hesitant to start drawing arbitrary boundaries on what constitutes an action.  Some actions might require a lot of small movement adjustments (creep blocking?)

**Comment by ASPePeX** [comment]
True, I didn't think of creep bloking.
Maybe a different aproach would be to identify a sequence of automated clicks by their intervalls (I guess one click per server tick) and only count the first and last one (or something like that). It still won't be exact, but it should be closer to the real APM of the player then counting all the automated clicks.
Also to make it clear on the frontend, you could still display the filtered and unfiltered value.

**Comment by howardchung** [comment]
Going to close this unless someome has a idea for a nice clean implementation that doesn't have too much of a performance impact.
