### ISSUE TITLE
split neutrals into ancient and jungle

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#730]
@jaccarmac might want to work on this

**Comment by howardchung** [comment]
Basically requires looking up the internal names for all ancient creeps (npc_dota_neutral_*) and summing the number of kills on units matching those names.

**Comment by jaccarmac** [comment]
Affirmative. I've been taking too long to get an environment set up, but when I finally get around to it the check should be straightforward.

**Comment by howardchung** [comment]
http://dota2.gamepedia.com/Cheats
list of ancient creeps available.  I can probably do this tomorrow.

We'll probably want to add (includes ancients) to the tooltip for the current neutrals column.
