### ISSUE TITLE
PostgreSQL tuning

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#739]
Maybe @ahockersten or @gortiz can weigh in:

Apparently some of the defaults in postgresql.conf are bad for production systems (too low).

Things I've tweaked:
shared_buffers: 1/4 of system memory
effective_cache_size: 1/2 of system memory

**Comment by mhartkorn** [comment]
Does the current setup allow query monitoring? Maybe some queries are super expensive, take most of the load, and PostgreSQL cannot optimize them.

**Comment by howardchung** [comment]
I have a "long running" query (check sql folder)

**Comment by howardchung** [comment]
Think these are the main settings that need to be tweaked but please comment if there are more that could be useful.
