### ISSUE TITLE
Restrict PostgreSQL access to read-only for web module

### ISSUE THREAD

**Issue by mhartkorn** [yasp-dota/yasp#741]
A tiny security improvement which helps versus malicious intent. Because the database is pretty expensive to build and modifications are not easily detectable, I would suggest to create 2 separate users:

- yasp, for all writing purposes (`GRANT SELECT, INSERT, UPDATE ON DATABASE yasp TO yasp`)
- yaspweb, exclusively for the web module (`GRANT SELECT ON DATABASE yasp TO yaspweb`)

Is there any interest for this?

**Comment by howardchung** [comment]
web needs write access for players logging in.
