### ISSUE TITLE
Party MMR is not tracked and after removing MMR Tracker no readding possible

### ISSUE THREAD

**Issue by TA2k** [yasp-dota/yasp#742]
On my profile the party mmr is not tracked and after removing the YASP mmr tracker from my friend list I cannot readd the mmr tracker.
https://yasp.co/players/121744943/rating

**Comment by howardchung** [comment]
MMR tracking has been changed.  You no longer add a bot to your friend list.  Instead you need to show the MMR in your Dota profile in-game.  You get two slots so you can show both types if you want to.
