### ISSUE TITLE
Interpolate MMR graph if values are missing.

### ISSUE THREAD

**Issue by TA2k** [yasp-dota/yasp#743]
An improvment for the MMR graph would be an interpolation for missing values
Example. https://yasp.co/players/121744943/rating

**Comment by howardchung** [comment]
Possibly could be fixed by going back to a timeseries graph #511 .  Actually thinking we should just do or the other, maybe timeseries makes more sense.

I think the null values in between are causing the line not to be drawn.

**Comment by howardchung** [comment]
Turned out to be just a config option in c3.

**Comment by howardchung** [comment]
Also finally merged in @lemongod 's work on toggleable mmr graphs.  yay for 3 months delay
