### ISSUE TITLE
Death icon on "Teamfights" view doesn't render. 

### ISSUE THREAD

**Issue by bddenhartog** [yasp-dota/yasp#744]
On all of my machines (two different physical machines running both windows and linux), using the latest version of Google Chrome (46.0.2490.80 as of the creation of this issue), the icon used for showing death in teamfights does not render properly. Instead of a skull, I am presented with an error box (shown below).

The cause of this issue is that Chrome, by default, does not support UTF-8 encoding -- you have to enable it in *Settings -> Advanced Settings -> Web Content -> Customize fonts*. It would be better to generate icons like this using SVG, so as to prevent the general user from experiencing the same.

![missing_death_icon](https://cloud.githubusercontent.com/assets/3893293/11040715/9287c84c-86c2-11e5-9fbb-7c8c76c6056b.png)

**Comment by howardchung** [comment]
It seems to work on my Chrome (46.0.2490.80, Linux), but I guess we should try to avoid the issue altogether.

Do you know how to do the svg conversion?

**Comment by bddenhartog** [comment]
I'll have some time later in the week to draft up the SVG objects; I've already forked the repo and will simply submit a PR from my dev branch.

Some notes:
- I *do* see the checkmark under "Joined".
- I do not see the icons that should be in the "Death" and *Buyback* columns (image below)
- Interestingly, the checkmark appears when font customization is set to both Western (Windows-1252) and Unicode (UTF-8); however, neither encoding type displays the death or buyback icons correctly.

![buyback](https://cloud.githubusercontent.com/assets/3893293/11044640/f7e9449e-86d7-11e5-916a-25254d594e50.png)

**Comment by srinath-v** [comment]
I'm using Chrome 46.0.2490.80 m on Windows, and have run into this. Came here to post an issue and saw this.

**Comment by howardchung** [comment]
Is this recent?  Wondering why nobody has reported it before.  I don't remember changing this recently.

**Comment by howardchung** [comment]
Relevant code for quick reference:
https://github.com/yasp-dota/yasp/blob/master/views/match/match_teamfights.jade#L89

**Comment by bddenhartog** [comment]
@howardchung I'm not aware of whether or not it is "recent" -- I've only recently started using Yasp.co, and it's been that way since I started using it (a few weeks ago). It's something that could easily go unnoticed (and often does), but it's not a fatal error -- rather trivial, actually, since not seeing the icons doesn't make the page lose value, as you can still tell who died/bought back by the presence of the question-mark-in-a-box.

**Comment by howardchung** [comment]
@bddenhartog is this still a problem?

**Comment by bddenhartog** [comment]
@howardchung Yes, for users that haven't enabled UTF-8 support. I had some things some up and apologize for the delay. I'll get a PR to you in the next day or so.

**Comment by bguzryanto** [comment]
As yasp uses fontawesome.io, We can utilize fontawesome.io. There are some complementary icons for death, joined, and buyback. Here is the example using fontawesome.io instead of unicode :

![image](https://cloud.githubusercontent.com/assets/198174/13035235/4a2a5b70-d37d-11e5-9ac5-2854c4579605.png)

**Comment by howardchung** [comment]
Okay, thanks!
