### ISSUE TITLE
Skill rating for games missing

### ISSUE THREAD

**Issue by Brian-McG** [yasp-dota/yasp#745]
I have noticed for the past 5 of my games (Match 1929651102 and below), yasp does not list the skill of the game but dotabuff is listing the skill for the game.

If I were to guess as to what the cause is, it is that the match is not yet in the valve skill api match list. Otherwise, maybe the match is already out of that list?

http://yasp.co/players/38190349
vs
http://www.dotabuff.com/players/38190349

**Comment by howardchung** [comment]
Actually, i just turned off the skill update script to try to speed up migration.  I'm not sure if it's helping, but it should be turned back on today after migration completes.
