### ISSUE TITLE
date filter for player pages

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#750]
Requested feature.

Shouldn't be too hard to add (possibly even an entry-level project for a new contributor!)

What options should we offer?  Last week, last month, last 6 months?

**Comment by WTFKr0** [comment]
I think a last 2 or 3 months would be great too

**Comment by gortiz** [comment]
Definitely 2 or 3 months would be great

**Comment by WTFKr0** [comment]
Pull Request : #756
