### ISSUE TITLE
discussion: percentage bars

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#751]
hi,
I noticed that in one of the latest updates (?) most of the numbers on the overview page got a small bar that shows how the above stats compares to the rest of the team. While this might a nice information for some people, I feel like it makes reading the table a lot more difficult. Something about it conflicts with my eye movement. I am aware that this is highly subjective and that currently yasp has no user settings, but might it be able to add an option to hide them?

Also how comes that yasp is able to parse replays that according my client aren't available yet?

**Comment by howardchung** [comment]
I don't think we're going to add options for this, but we can probably reduce the number of bars.  Some columns might not need them, or we could make them thinner, etc.

Not sure about the second question.  The replay is probably available but your client/network connection is having issues?

**Comment by Turmfalke2** [comment]
One suggestion would be to always have full bar in the background.
Which columns do you think really need the bars? Right now I really feel like the page looks better, when it hasn't finished loading and the bars are still missing. Also the bars might not be beneficial to the "pages load slowly" issue. For me there is a notable delay between the page being visible and the bars getting added. When the later happens it resizes the table, which means I have to search again for the information I am looking for.


Think you might be right, seems like the client "caches" the replay is not available information.

**Comment by howardchung** [comment]
Yeah, the bars are generated via client-side JavaScript (so the page content has to load first, then the JS runs).  Most of the slowness we're seeing is due to slow database queries (so not related to this problem).

We could actually just remove them completely from the overview page (but keep them on the other tabs?)

**Comment by Turmfalke2** [comment]
Personally I would welcome anything that is going to reduce the number of bars, although I still don't see why I would need a bar below the number of gems purchased.
I would like to see more feedback from other yasp users.

**Comment by Jemsuper** [comment]
I feel the same as Turmfalke. I like it as a feature, but right now its way too much visual clutter. Makes tables really hard to read. Just look at this: http://puu.sh/lobBO/20d43fda9f.png Is way harder too read than this http://imgur.com/Qi2AjqQ

**Comment by Iparke** [comment]
The first picture looks like the sprinkle factory blew up. :)
I like the idea of reducing the number of bars.

I'm sorry for my lack of contributions. I haven't forsaken the project. I am waiting for both unemployment and graduation at the end of December.

**Comment by howardchung** [comment]
Okay, I will remove it from the match overview page.

I think it helps with some of the tables, like gold/xp breakdown by category.  The overview is just the biggest table and therefore looks cluttered when we add so many bars.

**Comment by howardchung** [comment]
please reopen if there are more concerns about excessive bar usage :)
