### ISSUE TITLE
Add links in counts page

### ISSUE THREAD

**Issue by WTFKr0** [yasp-dota/yasp#753]
Hey !

I like to see and compare counters with my friends.
It would be great to have links to filtered matches.
As example, I would like to click on the Mid stats of Lane role of this page : 
http://yasp.co/players/62640399/counts

and have a link to this : 
http://yasp.co/players/62640399/matches?lane_role=2

Kr0

**Comment by howardchung** [comment]
hmm, might be doable.  might need a library to help construct the URL

**Comment by howardchung** [comment]
A minor problem with this is the region table.  The regions are strings, but each region is associated with multiple cluster numbers.  So it's not straightforward to apply a filter based on region name (since our filters only check for equality right now).

**Comment by WTFKr0** [comment]
Yh the filter must get the clusters associated to region (constants), and compare them to the match's cluster i think

**Comment by howardchung** [comment]
We would need to assign an id to each region (since all params must be numbers).

Then we need to reverse lookup the match's region based on cluster and compare that.

**Comment by WTFKr0** [comment]
Regions seems already get an id with the region parameter :
Extract :
"regions": {
    "unspecified": {
      "region": "0",
    "USWest": {
      "region": "1",
    "USEast": {
      "region": "2",
    "Europe": {
      "region": "3",
    "Korea": {
      "region": "4",
    "Singapore": {
      "region": "5",
    "Dubai": {
      "region": "6",
[...]

**Comment by howardchung** [comment]
We currently translate cluster to region via number to string mapping.  I
suppose we can make it a number to number mapping.

**Comment by WTFKr0** [comment]
I tried something on my dev, adding a region filter.
You can see diff here : https://github.com/yasp-dota/yasp/compare/master...WTFKr0:regionfilter
And test here (if my node is up :laughing: )
Filter Europe : http://dev.yasp.kr0.fr/players/62640399/matches?region=3
Filter USWest : http://dev.yasp.kr0.fr/players/62640399/matches?region=1

**Comment by howardchung** [comment]
Once the region filter is checked in I'll take a look at this
