### ISSUE TITLE
Keep filters when changing tab

### ISSUE THREAD

**Issue by WTFKr0** [yasp-dota/yasp#755]
Hey !

I don't know if it need to be implemented or not, but when I filter all the matches with my teammates with "included_account_id", it will be nice if i can change tab (from histograms to counts for example) without losing the actual filter.
With that, I think we need also a box to see which filter is active and a button to remove actual filter

Kr0

**Comment by howardchung** [comment]
Could possibly append any existing query string to the tab links.

But yes, we would want to have the query box open by default if there is a query, and give a "reset" button
