### ISSUE TITLE
Aggregate data for hero lanes

### ISSUE THREAD

**Issue by WTFKr0** [yasp-dota/yasp#758]
The idea is to get some stats on hero lanes
Example : 
- In my matches, which duo lane give me the most gold at min 15
- In my matches, which trilane give me the most % win

I think this feature would be placed in the aggregator, and don't know how many it can cost to compute

Kr0

**Comment by WTFKr0** [comment]
After looking at queries.js, it seems complicated cause only player_match info of current player are sent to aggregator. For my query, we need to aggregate all the player_match (10) of the match

**Comment by howardchung** [comment]
Yes, you would need to compute this at parse time (see workParser.js processAllPlayers() function), and I'm not even sure the hero_id data is stored there.  This is probably more difficult than it is worth.

Also there are simply way too many combinations.
