### ISSUE TITLE
networth change for alch aghs

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#766]
hi,
I think it would be nice the gold table http://yasp.co/matches/1962034458/farm would show networth changes due to alch gifting an aghs.
In that game the table lists me at 3781 gold and the overview at 9.1k.
Actually even with the 4.2k from the sceptre I would only have 7981. Any idea where the rest of my networth came from?

**Comment by howardchung** [comment]
The gold is actually gold earned, not net worth.  So alch giving an aghs would not affect it (not in the combat log).  The gold table does not include trickle gold, which is probably most of the difference.
