### ISSUE TITLE
move skill to own table

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#767]
Due to the way that we have to retrieve skill (polling all the hero/skill combinations and looking for matches that are returned), we currently have to do a ton of writes to the match table and update player caches a ton (which requires rewriting the entire player cache blob).

We should store match_skill as a separate table with two columns, match_id and skill.  The skill service should write directly to this table, and building player pages should look up skill from this table at load time (rather than storing it in cache).

**Comment by albertcui** [comment]
This is a good idea.

**Comment by howardchung** [comment]
building it now

**Comment by howardchung** [comment]
the only caveat is that we will have to do as many queries to the skill table as a player has matches, even if we are loading from cache.  hopefully those queries are very fast.

**Comment by howardchung** [comment]
turns out the queries are slow if we do a ton of them, but I optimized by only querying for matches older than config.UNTRACK_DAYS since that's the cache expiry and we should have skill data obtained via join for any match older than that.
