### ISSUE TITLE
client-side loading speed improvements

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#77]
- [ ] compress images such as map, wallpaper for faster loading (losslessly?)
- [ ] set browser caching for resources from /public

Also check the homepage for potential speed improvements.

See:
https://developers.google.com/speed/pagespeed/insights/?utm_source=pubinsights&filter_third_party_resources=true&hl=en&url=http%3A%2F%2Fyasp.co%2Fmatches%2F973737782%2F&tab=mobile&priorityGroup=speed

**Comment by howardc93** [comment]
The big one here seems to be compressing our served content.
https://github.com/expressjs/compression

**Comment by howardc93** [comment]
Do we have set goals for what we're actually trying to do with this?  I don't think trying to achieve 100/100 is worth the effort.

**Comment by howardc93** [comment]
on gitter it was reported that the homepage loads about 2.5MB, this should probably be reduced to ensure a fast index page.

**Comment by howardc93** [comment]
Results for index page:
https://developers.google.com/speed/pagespeed/insights/?utm_source=pubinsights&filter_third_party_resources=true&hl=en&url=http%3A%2F%2Fyasp.co&priorityGroup=speed

**Comment by vramana** [comment]
On the profile page, we do around 180 network requests. Out of that, around 110 are requests for getting Hero images. Althought they happen fast, it is too much unnecessary load. On mobile devices, I think this is really expensive. we should only load images on demand. This will cut the no. of requests to half. and we will get a much fast load time.

Is it possible to move the yasp.min.js to the `<body>`?

**Comment by vramana** [comment]
PageSpeed Insight Score for various pages

Page | Mobile Score | Desktop Score
--------|---------------------|------------------
/ | 46 | 46
/player/:id | 41 | 58
/player/:id/matches | 49 | 69
/player/:id/histograms | 57 | 80
/player/:id/records | 56 | 76
/player/:id/records | 56 | 76
/player/:id/records | 56 | 76

**Comment by howardc93** [comment]
I think some calls to yasp.min.js are required inside the content.  We used to put the bundle at the end, but for some reason I can't remember we moved it to the top.  There is probably some code that relies on it being loaded pre-body.

We are just linking to Valve's CDN to serve images for us rather than serving them ourselves.  I think this saves bandwidth.

**Comment by howardc93** [comment]
Re: hero images, this is because we render the entire table first, and then datatables only shows part of it.  I recently changed to server-side rendering in order to try to reduce the amount of times we just dump raw JSON into a JavaScript variable.  Doing the rendering client side also forces us to load the constants (that map hero_ids to images, names, etc.) into every page.

**Comment by vramana** [comment]
The entire table isn't show at the images at once right? So, only download those images that are currently showing. Download more when the user moves to next page. Does it make sense?

**Comment by howardc93** [comment]
Well, the rendered HTML will contain the markup for all the images.
Probably not all of them will be loaded before DataTables kicks in and
hides some of the rows, but I'm not sure if the browser will make the
additional network requests anyway (it might).

**Comment by vramana** [comment]
How about we inline base64 url for images for <=15kb images and direct URL's for the rest? As described here https://github.com/petehunt/webpack-howto#5-stylesheets-and-images

**Comment by howardc93** [comment]
Not quite sure how this would be implemented.

**Comment by vramana** [comment]
I'll try to figure it out. Leave that to me.

Hey, I am seeing 6386 full Histories in queue. Is it normal?

**Comment by howardc93** [comment]
Not really normal.  We got a ton of users from a Reddit post a couple days ago.  We can process about 600 new full histories per day.  Of the 6300 only about 2600 are actually new.  The rest are simply users who have logged in again, and they should complete relatively quickly.

Queue should clear in 4-5 days.

**Comment by vramana** [comment]
Apparently DataURI for images is a bad idea on mobiles according to this [blog post](http://www.mobify.com/blog/css-sprites-vs-data-uris-which-is-faster-on-mobile/). It seems CSS Sprites is the way to go according to the blog above and [this one](https://medium.com/parlay-engineering/emoji-at-scale-render-performance-of-css-sprites-vs-individual-images-f0a0a2dd8039).

**Comment by howardchung** [comment]
Closing.  There are still a few images we could compress.  CloudFlare should take care of caching for us, I think.  We don't want to have the browser cache the js bundle for long since we may need to update that.
