### ISSUE TITLE
This game was 46 years ago

### ISSUE THREAD

**Issue by TA2k** [yasp-dota/yasp#779]
https://yasp.co/matches/2007414681

**Comment by howardchung** [comment]
It looks like Valve messed up the API for a while during 6.86 deployment.  If they fixed it now then you could fix it by re-requesting the match, but we're probably not going to go through and re-add all of the affected matches.

**Comment by TA2k** [comment]
There is no re-requesting possible for this match

**Comment by howardchung** [comment]
You can just use the Request Parse button.  Even if the parse fails we still retrieve data from API first.
