### ISSUE TITLE
Aether lens is missing in the overview

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#782]
hi,
The new item aether lens is missing on the end screen/overview. Both pudge and I had one, as can be seen from the the purchases page.

https://yasp.co/matches/2011586554/

**Comment by howardchung** [comment]
Item ID is:
```
item_3: 232,
```

however Valve's jsfeed has the wrong ID.

We can manually patch it or wait for Valve to update.

**Comment by howardchung** [comment]
Also appears to be a problem with doom's LVL death replacement skill.

Also likely to be fixed when Valve gets around to updating the jsfeed data.

**Comment by eblis** [comment]
Dragon lance is also missing from the overview page (can be seen in the purchases page however).

**Comment by howardchung** [comment]
Yeah all the new items are gonna be in the same boat.  Checking again

**Comment by howardchung** [comment]
still not updated.  I guess if it's still like this by the end of the week I can manually patch the item ids.

**Comment by howardchung** [comment]
I got impatient.  Manually patched

**Comment by eblis** [comment]
Hehe, thanks.
