### ISSUE TITLE
full https

### ISSUE THREAD

**Issue by WTFKr0** [yasp-dota/yasp#786]
Hello,

Will it be interesting to make https request to static cdn.dota when we call https://yasp.co ?
This avoid warning like 'external resources are not in https' in browser
I'm interested in this cause proxy at work don't filter https content :D
For now, yasp.co works but i don't have images

Thanx

**Comment by mhartkorn** [comment]
While `https://cdn.dota2.com` has a theoretically valid certificate, it is not valid for the domain `cdn.dota2.com`. The certificate's Subject Alternative Name field contains only these entries:

    DNS:a248.e.akamai.net, DNS:*.akamaihd.net, DNS:*.akamaihd-staging.net, DNS:*.akamaized.net, DNS:*.akamaized-staging.net

As long as `cdn.dota2.com` does not have its own certificate, it is not usable for secure connections. The only thing that can be done for now is to copy the images to the yasp.co servers.

**Comment by howardchung** [comment]
Yeah, this is annoying.  We could go back to not forcing https.  Syncing the images to our servers increases costs and adds stuff we have to do when the game udpates.

@albertcui ?

**Comment by mhartkorn** [comment]
I don't think that yasp.co really needs HTTPS for now. The login is secured by Valve anyways, so better wait until the CDN gets a valid certificate.

**Comment by albertcui** [comment]
/carry is the only route that really needs https. Though i think since we
run through cloudflare mirroring the images shouldn't be too expensive.

**Comment by howardchung** [comment]
We could probably proxy to the images

**Comment by albertcui** [comment]
I think another adv of us hosting ourselves is that we can set a browser cache on the images. I don't think Valve is doing this (or at least wasn't before).

**Comment by howardchung** [comment]
Also works with proxy?  Just need to send the right header

**Comment by WTFKr0** [comment]
Thanx works as expected
