### ISSUE TITLE
Match Making Stats of Singapore,Brazil and India are always zero

### ISSUE THREAD

**Issue by Energy0124** [yasp-dota/yasp#792]
For some reason the matching making stats of these 3 regions are always 0 according to https://yasp.co/mmstats
Is this a bug or a technical limitation on Valve side? Is it possible to be fixed?
I noticed this problem for quite a long time so I am pretty curious about the reason.

**Comment by howardchung** [comment]
The data we get from the client for those regions seems to be wrong.  I'm not sure why.  We could just remove those regions from the list (or not display if the value is 0).  This is @albertcui 's feature.

**Comment by albertcui** [comment]
We get the list of servers as reported from Valve's constants. I believe the India servers were recently added and now report non zero numbers. So some of the zero servers could indicate future additions.
