### ISSUE TITLE
Some items like Quelling Blade shouldn't be expected to be used in the analysis feautre.

### ISSUE THREAD

**Issue by MeLlamoPablo** [yasp-dota/yasp#793]
Hi! First of all, the new analysis featue is really cool. Good job!

So, in [this game](https://yasp.co/matches/2044337782/analysis) I was the Ember Spirit. YASP tells that I didn't use Quelling Blade at all and marks it as a failure, but some items shouldn't be expected to be used often. In my opinion, those items are the following:

* Iron Branch
* Quelling Blade
* Battlefury
* Moon Shard
* Radiance
* Linken's Sphere

Thanks for your time!

**Comment by howardchung** [comment]
branches should be exempted already.

QB I would argue should be used at least once to optimize pathing.  

I'll add bloodstone to the list as well.
