### ISSUE TITLE
Where to find throttling options

### ISSUE THREAD

**Issue by schadowfox** [yasp-dota/yasp#794]
Where can I set throttling options?

As right now I just get data for 10-20 seconds and then Steam Returns a 503, probably because yasp hits the servers more than 1req/sec

5:28:53 PM scanner.1   |  2016-01-02T16:28:53.062Z - info: getData: http://api.steampowered.com/IDOTA2Match_570/GetMatchHistoryBySequenceNum/V001/?key=My_API_KEY_HERE&start_at_match_seq_num=1804646739
5:28:53 PM skill.1     |  total results: 0, added: 0

5:29:19 PM scanner.1   |  2016-01-02T16:29:19.376Z - info: invalid response, retrying: http://api.steampowered.com/IDOTA2Match_570/GetMatchHistoryBySequenceNum/V001/?key=My_API_KEY_HERE&start_at_match_seq_num=1804648804

**Comment by howardchung** [comment]
You can check `utility.js`  getData method which has a built-in delay.

**Comment by schadowfox** [comment]
Thanks, setting this to a higher value fixed the issue as skill and scanner both hit the api at the same time - I was looking in config.js but didn't find that there.

**Comment by howardchung** [comment]
This could be made into a configurable value if you want to submit a PR for
it and refactor the delay to config.js.
