### ISSUE TITLE
Predicting match outcome based on draft

### ISSUE THREAD

**Issue by chudooder** [yasp-dota/yasp#798]
I downloaded the 500,000-match subset a few days ago and ran some ML on the data. I wanted to see how accurately a model could predict the winner of a match based solely on the heroes picked on Radiant and Dire.

I reorganized all of the matches into a single array; the features was a 224-length array of all the hero IDs in a row, with indices [0, 112) representing Radiant and [112, 224) representing Dire. A 1 in an index indicates that the hero was picked on that team. The target vector is an array of 0 or 1 indicating a Radiant loss or win respectively. I also pruned out matches without 10 human players.

I ran it through a couple of different algorithms with a Linear SVM classifier performing the highest (though not amazingly). The model is trained using a randomly chosen 80% of the dataset and tested on the remaining 20%:
```
             precision    recall  f1-score   support

        0.0       0.58      0.53      0.56     47509
        1.0       0.60      0.66      0.63     52030

avg / total       0.59      0.60      0.59     99539

Confusion Matrix (x = predicted, y = actual)
	  Dire  Radi
Dire: 25183 22326
Radi: 17903 34127
```
The results confirm that Dota is in fact a complex game and the draft is only partially responsible for the outcome of a match; however, I was pleasantly surprised that the model was able to achieve 59% precision, better than randomly guessing.

Unfortunately I don't think have access to MMR or bracket data in the dataset, but I'd like to separate out higher brackets and see if the model performs better when players are able to take advantage of weaknesses in the draft.

The code can be found [at this repository](https://github.com/chudooder/d2oracle). It's kind of messy but hopefully it will be of use if you want to do further research. manual_test.py can be used to predict the winner of arbitrary drafts! Just run the model generation first.

**Comment by howardchung** [comment]
@nickhh may be interested, he's been trying to do ML stuff on Dota data
