### ISSUE TITLE
Make link to repo more prominent on website

### ISSUE THREAD

**Issue by edwinksl** [yasp-dota/yasp#799]
It seems like a good idea to make links to this repo more prominent on the website because the community probably has many people who can/want to contribute. As far as I can tell, I can only get the link to this repo by scrolling all the way to the bottom to the footer section.

**Comment by howardchung** [comment]
@albertcui should weigh in on this.  I'm fine with putting it as a menu item on the main nav bar.

**Comment by edwinksl** [comment]
Yeah, perhaps something like a "Contribute" or "GitHub" menu item at the main nav bar.

**Comment by albertcui** [comment]
I don't think this is necessary. 99.9% of users will not contribute or do not have the ability to contribute. Those who want to can find the repo. (We have 283 stars at this point.)
