### ISSUE TITLE
Shadow razes display the same one

### ISSUE THREAD

**Issue by Jemsuper** [yasp-dota/yasp#801]
Even though the site is able to differentiate between all 3 razes, it only shows the close one for all 3. 
(in skills used) https://yasp.co/matches/2049875930/performances

**Comment by howardchung** [comment]
Need to manually patch the tooltip.  Data is from http://www.dota2.com/jsfeed/abilitydata

**Comment by Derek-Li** [comment]
Under constants.js
    abilities.nevermore_shadowraze2 = abilities.nevermore_shadowraze1;
    abilities.nevermore_shadowraze3 = abilities.nevermore_shadowraze1;

I'm guessing this the spot where it causes Shadow Raze 2/3 to be shown as Shadow Raze 1?

**Comment by howardchung** [comment]
Yes.  The tooltip data does not contain separate entries for the three razes so we wuld need to make copies of shadowraze1, edit them, and point to them.
