### ISSUE TITLE
replace "parse" with better verb

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#803]
Getting complaints about "parse" being an overly technical term for the lay user.

I could just do `ag -i "parse"` on the codebase/views and replace with another term, maybe "analyze"?

Suggestions?

spots:
json/tooltips.json
_posts/_faq_why-different.md
_posts/_faq_why-not-parsed.md
_posts/fullhistory_everyone.md
views/player/player.jade
views/home.jade
views/request.jade
views/carry.jade
views/match/match.jade

**Comment by Derek-Li** [comment]
To be honest, I think 'parse' would be the best suited term, but 'analyze' works well too.

Tier 1: parse, analyze
Tier 2: extract, prune, scan (?)
Tier 3: scan, examine, search

That's my opinion, I don't think we have too huge of a selection to replace 'parse', but I think some of these are decent.

**Comment by howardchung** [comment]
@albertcui says this isn't an issue.  I guess I'll leave it as is for now unles we get more complaints.
