### ISSUE TITLE
Analysis feature 'unused item' with upgradeable items

### ISSUE THREAD

**Issue by Break0utKing** [yasp-dota/yasp#804]
Some items such as Quelling Blade, Magic Stick and Boots of Travel, and their respective upgrades, Iron Talon, Magic Wand and BoT 2 should share their uses. For example I get 0 uses on Quelling Blade (thus decreasing rating) in the games I upgrade to Iron Talon.

**Comment by howardchung** [comment]
Okay, I think we just need to manually define groups and sum together all the keys in each group for determination purposes.

Groups:
Dagon
Necro
BoT
stick/wand
qb/iron talon
shadow amulet/blade/silveredge

**Comment by howardchung** [comment]
merge with #797
