### ISSUE TITLE
Home button links to Profile page

### ISSUE THREAD

**Issue by likered** [yasp-dota/yasp#805]
Clicking the YASP nav button while logged in links you to your Profile page instead of the Home page.

Was it intended for the Home page to be your Profile page? If so, then it feels a bit redundant to have both a Home page & Profile button

**Comment by howardchung** [comment]
A long time ago it linked to home page regardless of login status, but @albertcui didn't like it.  I suppose we COULD get rid of the Profile link when logged in, but since it's been like this for months it's probably not worth the confusion caused to users.

@albertcui can decide.

**Comment by howardchung** [comment]
I think @albertcui decided he thinks it's fine but he can close the issue to confirm
