### ISSUE TITLE
player search by name

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#835]
I built a text index on the personaname field so we can search for players by name.  Is this something we want to implement?  Currently if you search for a random player they are unlikely to have all matches listed (unless they have signed in)

Example query:
```
select * from players where personaname ILIKE '%sniffle%' LIMIT 1000;
```

**Comment by howardchung** [comment]
Note: I opted for the pg_trgm extension rather than bringing in something like ElasticSearch.  We have about 5 million player records, which isn't too bad.

I'm assuming we won't need to search something like player_matches table, which is billions of records.

**Comment by likered** [comment]
Yeah, I think there's no need to bring in Elasticsearch for this yet (will also result in increased disk-space usage with all those saved indices).

The only current way of searching a random player is by finding a match and clicking on the players in the match, right?

Guess it would be nice to include the functionality to search for both players and match ID's

**Comment by howardchung** [comment]
If you know the match is you can plug the ID into the matches URL or use request form.  Right now we have no way of translating a steam personaname to an account ID though.

**Comment by howardchung** [comment]
backend is ready.  @albertcui owns the frontend design/development for this feature.
