### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by teckays** [yasp-dota/yasp#836]
I have the following error when running `sudo npm run build`

```
ERROR in ./~/css-loader!./~/c3/c3.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/teckays/apps/yasp/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/teckays/apps/yasp/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/home/teckays/apps/yasp/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/home/teckays/apps/yasp/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/c3/c3.css 4:14-60
```

there are many other errors like this and all of them have `./~/css-loader!./` directory in common

**Comment by howardchung** [comment]
Don't use sudo for build.  You might need to reclone or chown to fix permissions.

**Comment by teckays** [comment]
@howardchung running without `sudo`throws another error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project stats: Failed to clean project: Failed to delete /home/teckays/apps/yasp/java_parser/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst -> [Help 1]
```

**Comment by howardchung** [comment]
Try manually deleting that file with sudo and then running the build without?

**Comment by teckays** [comment]
@howardchung hmm, same thing. Might be the issue that I'm trying to setup yasp on a remote machine via ssh.?!

**Comment by howardchung** [comment]
That shouldn't be an issue.  Our setup is on Ubuntu 14.04 LTS though--init.sh should work for that platform.

**Comment by teckays** [comment]
I'm on 15.10, could this be the problem?

**Comment by howardchung** [comment]
It might be.  I don't think I've tried building yasp from scratch on 15.10 before

**Comment by likered** [comment]
I've also ran into that error on 15.10 (among others). I migrated to 14.04 LTS and it was fine.

**Comment by teckays** [comment]
hmm, wouldn't like to reinstall the 14.04 version, but looks like I don't really have a choice

**Comment by howardchung** [comment]
You could try running it within a virtual machine with something like Vagrant.

**Comment by teckays** [comment]
@howardchung yes, this is one option, however I think I'm going to downgrade. Made a mistake installing 15.10 so better now to fix this.

**Comment by howardchung** [comment]
Alternatively you can try to figure out why it won't work on 15.10, but probably easier just to go back to the LTS version :)

**Comment by teckays** [comment]
@howardchung yeah I think that going back is a better solution because on production we're going to run  14.04 edition as well so it would make more sense developing on the same environment.

**Comment by teckays** [comment]
@howardchung OK, reinstalled ubuntu and when I reach `npm run build` I get the same errors with `./~/css-loader!./`

**Comment by howardchung** [comment]
Node/npm versions?

**Comment by teckays** [comment]
yeah, I just came back to post the solution. when installing node and npm the node version was way back to `0.12`, that's a shame, upgraded to `4.2` now it works.

**Comment by howardchung** [comment]
Init.sh should install the latest version.

**Comment by teckays** [comment]
@howardchung I think I installed it manually before running `init.sh` that's why.

**Comment by teckays** [comment]
@howardchung sorry maybe wrong thread, but I guess I need the Steam installed on my machine and the login details should be for the account I have the API generate for right?

**Comment by howardchung** [comment]
You do not need Steam installed.  node-dota2/node-steam take care of the communcation.  The login can be for any account, and we recommend making a new account to use with the retriever.
