### ISSUE TITLE
Doom's Infernal Blade still has Lvl? Death icon

### ISSUE THREAD

**Issue by SneakySniper100** [yasp-dota/yasp#837]
I just played a game as doom and realized that the Lvl? Death icon was showing up.

Link to Infernal Blade image for ease. ![Infernal Blade Icon](http://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e2/Infernal_Blade_icon.png?version=c39973945029e4e214f99553b74e591a)

**Comment by howardchung** [comment]
Is this on ability builds, or on performance tab?

We use images from Dota 2 CDN.  Might need to wait for them to update.

**Comment by howardchung** [comment]
A link to the match is question would help me debug

**Comment by SneakySniper100** [comment]
https://yasp.co/matches/2086667423/

**Comment by howardchung** [comment]
unify with #838
