### ISSUE TITLE
New hero ability icons are incorrect

### ISSUE THREAD

**Issue by SneakySniper100** [yasp-dota/yasp#838]
I recently played a game with a Riki and noticed this.

Link to new icon for ease: ![Tricks of the Trade Icon](http://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ed/Tricks_of_the_Trade_icon.png?version=cf2b15c1a0fa35287c917f43b19368dc)

Affected:
doom infernal blade
riki tricks of the trade
faceless void backtrack
death prophet witchcraft

**Comment by howardchung** [comment]
same cause as #837 I suspect.

If this is the ability upgrades section it means the ability_id map to ability name (which is what is used to fetch the image) is incorrect.

**Comment by SneakySniper100** [comment]
The data is correct, the icon isn't.  It looks like its with all the new hero ability icons.

Death Prophet's icon is using the old Witchcraft icon.

I can't confirm
* Faceless Void is probably using the old Backtrack icon
* Lone Druid's Savage Roar is probably using the old Synergy icon

As well as Doom's Infernal Blade using Lvl? Death mentioned in #837

These icons are incorrect anywhere they are shown, including Skill builds, utilization, and Team fights.

**Comment by SneakySniper100** [comment]
Link to match with Riki. https://yasp.co/matches/2086607729

**Comment by howardchung** [comment]
Yep it looks like Dota hasn't updated the images officially:
http://cdn.dota2.com/apps/dota2/images/abilities/doom_bringer_infernal_blade_md.png

**Comment by likered** [comment]
Yeah, we ran into issues where some of the icons were missing (savage roar is missing) or wrong a while back ago.

Has to wait for dota2 cdn to update.

**Comment by howardchung** [comment]
we CAN manually patch in the images but I'm not super inclined to do it since it's kind of duplicated work if Valve ends up fixing it (which they hopefully do soon.  valve time :()

**Comment by howardchung** [comment]
merging with #807
