### ISSUE TITLE
Failed to parse replay. Please make sure the replay is available in client and has not expired

### ISSUE THREAD

**Issue by teckays** [yasp-dota/yasp#840]
I'm getting this error: `Failed to parse replay. Please make sure the replay is available in client and has not expired` when trying to parse a match ID. I'm sure it isn't expired as I'm taking it from dotabuff and this is the last match played. Any clues?

**Comment by howardchung** [comment]
Are you trying to do this on production or on your own development environment?

I'll need the match_id to debug

**Comment by likered** [comment]
I ran into that issue a few times as well; chose my last played game, but it threw that message.

Could it be that one of the microservices isn't running (e.g. parser, requests)?

**Comment by howardchung** [comment]
Development or production?

**Comment by likered** [comment]
Production, has not happened in development

**Comment by howardchung** [comment]
Example match id that doesn't work?

**Comment by likered** [comment]
If I remember correctly, I was trying to parse my Lion match: https://yasp.co/matches/2070192489

I just tried it right now and it seems to work perfectly.

**Comment by howardchung** [comment]
Availability issues happen sometimes when Valve is doing maintenance.  It's
only actionable if it happens consistently.  Sometimes replays also just
aren't downloadable.

**Comment by howardchung** [comment]
@teckays if you have a match id I can check if the replay is available.
