### ISSUE TITLE
multi counted games

### ISSUE THREAD

**Issue by Kartoffelshake** [yasp-dota/yasp#841]
this new dota acc hast 3 games atm, but is 7 1 (undying game counts as 2 and anti mage counts as 5)

**Comment by howardchung** [comment]
Link to profile?

**Comment by Kartoffelshake** [comment]
oh thx forgot it xD
https://yasp.co/players/317292403

**Comment by howardchung** [comment]
I think I fixed this.  See commit for details, but my duplicate check was improper and the validateCache function only checks against the match_ids hash, not the individual aggregations.
