### ISSUE TITLE
Profile MMR does not update accordingly (on time?)

### ISSUE THREAD

**Issue by likered** [yasp-dota/yasp#842]
So I've been taking a look at my profile these few days (while playing a bit of solo ranked games) and I noticed that the Solo MMR value isn't updating to its latest.

So in my case, my yasp profile states that I'm 3990 MMR, but I've actually won another game that should increase my MMR to 4014. The last ranked game I played was 2 days ago, so I'm wondering if it's an issue on valve's end or ours.

My profile is https://yasp.co/players/107173931, if you want some context as to when games were played.

**Comment by likered** [comment]
I've checked my dotabuff profile and it also says 3990. So it could very well be valve's issue.

**Comment by howardchung** [comment]
This is a known issue we can't do anything about.  There is a delay in updating profile card MMR.
