### ISSUE TITLE
Midas efficiency.

### ISSUE THREAD

**Issue by xzoLx** [yasp-dota/yasp#846]
A Hand of Midas efficiency stat could be useful, maybe under the analysis tab.  Has this been shot down already, is the analysis tab not the right place for it, what would the efficiency be based off of, etc.?

**Comment by howardchung** [comment]
In general we just have avoiding doing things that are too specific.

**Comment by howardchung** [comment]
Midas "pays" for itself after 11 uses (190*11 = 2090, more than the 2050 cost).  Would this just be uses/11?

**Comment by howardchung** [comment]
Since we already show number of uses I'll close this unless someone has a more detailed suggestion for a better metric.
