### ISSUE TITLE
Allow projection on matches table

### ISSUE THREAD

**Issue by alexalperov** [yasp-dota/yasp#849]
Currently the Yasp matches tab contains the following columns:
ID, Hero, Result, Mode, Skill, Ended, Duration, KDA

I seem to recall when "GPM" was a part of the columns, however it no longer found there. YASP has a wealth of other statistics including LH@10, lane efficiency, etc. that are shown as a part of each individual game. What's missing is the statistics in context of all of your other games, which is why I am suggesting the addition of these criteria on the matches page. 

Due to the fact that there might be a lot of possible columns allow us to toggle between which we would like to see (kda, gpm, lh@10).

**Comment by howardchung** [comment]
Yeah, this would be nice to have but I don't know how to make a nice UI for
it.

**Comment by alexalperov** [comment]
Just a rough idea:
Add a settings icon to the Match Columns
![image](https://cloud.githubusercontent.com/assets/15504259/12559722/52e2c51c-c35c-11e5-9b39-7fe5e6e704ff.png)

When you click on it:
![image](https://cloud.githubusercontent.com/assets/15504259/12559848/0b44f364-c35d-11e5-82ef-eb8d3a4cb979.png)

Allowing a certain amount of columns to be selected

**Comment by howardchung** [comment]
Actually it looks like DataTables has support for this, so I can take a stab at building it:
https://datatables.net/examples/api/show_hide.html

**Comment by howardchung** [comment]
I just added back LH and GPM to the matches table for now.  However right now adding more fields means our player caches get bigger, so we may need to hold off on adding lots of fields that the user can choose.
