### ISSUE TITLE
Skill builds are partially wrong

### ISSUE THREAD

**Issue by Splamy** [yasp-dota/yasp#854]
Hey, I've noticed in my last match that the skill builds of a few players are wrong.
In this case particularly the Shadow Shaman (ult lvl 15) and Jakiro (ult lvl 5, 9)
![crop](http://puu.sh/mOox9/54738aeb06.png)
Here is the match: https://yasp.co/matches/2113565740
Dotabuff on the other hand only has 1 wrong ^^ http://www.dotabuff.com/matches/2113565740 (jakiro ult 9)

**Comment by howardchung** [comment]
Generally this is due to multiple level ups.  The returned data is actually the order at which skills are leveled, so if you get level 5 and 6 at the same time you can get the ult fifth.  I'm guessing dotabuff has logic to handle 2 at once but not 3 at once.
