### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#857]
Improve community engagement?

Allow us more direct contact with users?

- [x] retire gitter and maybe the google form
- [x] update links on site and in README
- [ ] banner msg
- [ ] blog post
- [ ] reddit thread?

**Comment by dartharaknus** [comment]
I would really love this. I was looking for a chat room for this project.

**Comment by dartharaknus** [comment]
@howardchung Any update on a chat room for the project? I would love to get involved.

**Comment by howardchung** [comment]
We'll probably announce it on Reddit and on the site sometime next week, but feel free to jump in early if you want (we already made the room):

https://discord.gg/0o5SQGbXuWDfZhmR
