### ISSUE TITLE
Skill brackets data not included in the Data Dump?

### ISSUE THREAD

**Issue by 1zb** [yasp-dota/yasp#860]
Hi,

I am trying to do something with the 500k matches data downloaded from academic torrents. But it seems that the skill bracket (normal, high and very high) is not present at the JSON file.

**Comment by howardchung** [comment]
Yeah, we forgot to include it.  @albertcui can decide if he wants to do it, although we only have it starting around May 2015 (when we started collecting it)

**Comment by howardchung** [comment]
merging with #881 .

I don't know if @albertcui is just planning to do December 2015-March 2016 games and not everything all over again.  We should be including skill this time, so you'll have at least 3 months of skill data.

Make your case to @albertcui if you want him to dump the complete skill data (May-December 2015)
