### ISSUE TITLE
Multikills/Killstreaks data change

### ISSUE THREAD

**Issue by dartharaknus** [yasp-dota/yasp#862]
If you look at the following match, there were a lot of double kills but YASP is not showing them. 

Multikills:
https://yasp.co/matches/2131384891/combat

Killstreaks:
https://yasp.co/matches/2132855897/combat

**Comment by howardchung** [comment]
Interesting.  It's possible Valve removed the data from the replay.

**Comment by dartharaknus** [comment]
Maybe, we can construct it on our own since we kill timers.

**Comment by howardchung** [comment]
After checking the replay logs:
```
{"time":1172,"type":"DOTA_COMBATLOG_MULTIKILL","value":0,"attackername":"npc_dota_hero_spirit_breaker","targetname":"npc_dota_hero_spirit_breaker","targetsourcename":"modifier_fountain_aura_buff","attackerhero":false,"targethero":false,"attackerillusion":false,"targetillusion":false,"gold_reason":0,"xp_reason":0}
```

The "value" field previously was the length of the streak.  However it seems to have changed to reflect the length above "minimum" streak (2 for multikills and 3 for streaks).  I'll manually patch in the number.  You guys will have to let me know if it fixes the problem.

**Comment by howardchung** [comment]
@chrisdickson does this look correct?

http://colab-sbx-244.oit.duke.edu:5000/matches/2132855897/combat

**Comment by howardchung** [comment]
@dartharaknus 
Here's your match on the devbox:
http://colab-sbx-244.oit.duke.edu:5000/matches/2131384891/combat

**Comment by dartharaknus** [comment]
I think it looks correct now :smile:
