### ISSUE TITLE
Kill streaks not properly recorded

### ISSUE THREAD

**Issue by ChrisDickson** [yasp-dota/yasp#863]
[In this game](https://yasp.co/matches/2132855897/combat) one of the players (okay, me) got beyond godlike, which isn't recorded. It happens around 32:20 in the replay.

**Comment by howardchung** [comment]
may be related to #862.  I'm going to need to check the replay log output to see if it's a valve issue.  I don't remember changing the code for this recently.

**Comment by howardchung** [comment]
I think same root cause as #862, merging
