### ISSUE TITLE
Pings on map not working 

### ISSUE THREAD

**Issue by Jemsuper** [yasp-dota/yasp#866]
Pings on map always comes back to 0

https://yasp.co/matches/2135221260/actions
https://yasp.co/matches/2132489021/actions
https://yasp.co/matches/2132353575/actions

**Comment by howardchung** [comment]
I think Valve removed this data from the replay, but I can double-check the replay logs.

**Comment by howardchung** [comment]
It appears the data is no longer present.  We can remove the code, or leave it there in case Valve puts it back.

**Comment by howardchung** [comment]
looks like the data might be back, but just displayed wrong

**Comment by howardchung** [comment]
confirmed with one of the matches you linked
