### ISSUE TITLE
Mobile bug with the time in yasp.co (Swedish iPhone)

### ISSUE THREAD

**Issue by TommyLjung** [yasp-dota/yasp#869]
Bug in the "Time since played" column in iPhone on yasp.co.
It is just showing "Invalid date" or "never" instead of the time!
I am adding 3 images to show what I mean. (First one is on the computer showing how it SHOULD look, and the next two is from my iPhone). 
My iPhone is set to Swedish and that might a part of the problem, but I really think you should add something like `CultureInfo.InvariantCulture` to fix this.

On my computer:
![yaspbugg_computer](https://cloud.githubusercontent.com/assets/3416502/12909684/f722699a-cf03-11e5-9277-105c4f8eaf58.jpg)

On my iPhone:
![yaspbugg_iphone1](https://cloud.githubusercontent.com/assets/3416502/12909797/f3b0b586-cf04-11e5-9af9-443ed30c6f4f.PNG)

On my iPhone:
![yaspbugg_iphone2](https://cloud.githubusercontent.com/assets/3416502/12909806/ff653a1e-cf04-11e5-9c41-9af7be6df8cf.PNG)

**Comment by howardchung** [comment]
I can't repro this on my phone, but thanks for catching it.  I think it may have to do with some setting on Moment.js:
http://momentjs.com/docs/#/i18n/

I don't think I ever set anything explicitly so it should be English always, but apparently it can break. . . does anyone else have this problem?

**Comment by TommyLjung** [comment]
I tried on my work-phone just now (Samsung Galaxy S4) and it works like a charm there...
Strange, have to be "iPhone + Sweden settings" specific :(

**Comment by howardchung** [comment]
Maybe it's a Safari thing.  I think it uses a different JS engine.

Can anyone repro with:
Desktop+non-Swedish?
Desktop+swedish?
iOS + non-Swedish?

**Comment by TommyLjung** [comment]
I have checked on Safari on my computer (Windows 7 and non-swedish), and it works there.

**Comment by TommyLjung** [comment]
I have now checked on the same iPhone on Firefox, and everything works fine there.
So it is probably Safaris JS engine and the swedish settings on iPhone that does this, still don't know why tho. :(

![yaspbugg_iphone_firefox](https://cloud.githubusercontent.com/assets/3416502/12975406/9e0404f4-d0bb-11e5-8669-acdfcab64f05.PNG)

**Comment by TommyLjung** [comment]
http://momentjs.com/docs/#/parsing/utc/

"By default, moment parses and displays in local time."

Sweden have have national standard yyyy-mm-dd.
Some other countries (including USA) have mm/dd/yy.
Source: https://en.wikipedia.org/wiki/Date_format_by_country

Can this be the problem?

**Comment by howardchung** [comment]
Probably not.  Otherwise it would affect the other browsers too.

**Comment by TommyLjung** [comment]
http://stackoverflow.com/a/4310986
http://stackoverflow.com/a/31239891

**Comment by TommyLjung** [comment]
moment(_**dateToFormat**_).format('YYYY MM DD');
Could do the trick?!

Source: http://momentjs.com/docs/#/displaying/format/

**Comment by howardchung** [comment]
IIRC the date is parsed from unix timestamp.

**Comment by howardchung** [comment]
Relevant code:
https://github.com/yasp-dota/yasp/blob/1c6b0fb1bb21306a377e8221a36e78af1f5aee21/views/player/player.jade#L135

**Comment by howardchung** [comment]
"data" is passed from DataTables so I suspect the problem is there.

**Comment by TommyLjung** [comment]
And changing:
`return moment.unix(data).fromNow();`

to:
```
moment.locale('en');
return moment.unix(data).fromNow();
```

or...
`return (moment.unix(data).format('YYYY-MM-DD')).fromNow();`

or...
`return moment(moment.unix(data), 'YYYY-MM-DD HH:mm').fromNow();`


Doesn't solve this?

**Comment by howardchung** [comment]
I can test it but since I can't verify the fix locally you'll need to be around to check it.

**Comment by howardchung** [comment]
I don't think the second and third will work since it relies on moment.unix()

**Comment by TommyLjung** [comment]
> I can test it but since I can't verify the fix locally you'll need to be around to check it.

Ofc I can verify it, but is that done on the production site, or do you have a test-site?

**Comment by howardchung** [comment]
Test:
http://colab-sbx-244.oit.duke.edu:5000/players/88367253

**Comment by TommyLjung** [comment]
![yaspbugg_locale en](https://cloud.githubusercontent.com/assets/3416502/13806688/5a4e0d24-eb5d-11e5-9806-05dfd433e274.PNG)
Well... That didn't help... :(

But I looked around now, and the Match-view (For a specific match) displays the "time since ended" right (with the same settings, same iphone, same browser)! See image below to understand what page :)
So what differs the match-view, for example (https://yasp.co/matches/2215444854)
with the Overview and Matches tabs when displaying "Time Since Ended"? (https://yasp.co/players/31645182/).

![yaspbugg_matchtab](https://cloud.githubusercontent.com/assets/3416502/13807013/403ea806-eb5f-11e5-88f0-2a7494fcb58e.PNG)

**Comment by howardchung** [comment]
The table uses datatables, so the rendered HTML is a unix timestamp.  That enables sorting.  DataTables is configured to convert the timestamp into a formatted string.

The match doesn't need sorting, so the text is just rendered server-side.

**Comment by TommyLjung** [comment]
Ok, have you had time to look more into this?

**Comment by howardchung** [comment]
TBH, I haven't really prioritized this since it's limited to safari (and I can't repro it).  I'm happy to accept a fix for it but I don't think I can do it myself.

**Comment by TommyLjung** [comment]
Ok, I will try fix it myself then :)

return moment.unix(data).format('YYYY-MM-DD HH:mm:ss').fromNow();

Could work... But it is hard for me to test my theories :(

Source: http://www.digitoffee.com/programming/get-local-time-utc-using-moment-js/94/

**Comment by howardchung** [comment]
I don't think that will work:

* I think the problem is that moment.unix() is failing to parse correctly.  That's why we see "Invalid date".
* format() creates a string, so calling fromNow() on it will cause an exception since strings don't have that method.

**Comment by TommyLjung** [comment]
Changing:
`return moment.unix(data).fromNow();`
to:
`return moment.unix(data,'YYYY-MM-DD HH:mm').fromNow();`
or:
```
var formatedDate = moment(data', 'YYYY-MM-DD HH:mm').toDate();
return moment.unix(formatedDate).fromNow();
```
Could work.... maybe :)

You have to (in some way) insert a format string to get this to work...
> This is by design. Anything other than the standard ISO formats fall back to the browser's implementation unless you provide a format string.

Source: https://github.com/moment/moment/issues/2340

**Comment by howardchung** [comment]
That's the output function moment().unix(): 
http://momentjs.com/docs/#/displaying/unix-timestamp/

We're having a problem with the parsing function moment.unix()

**Comment by howardchung** [comment]
I can try moment(data, 'X').

**Comment by howardchung** [comment]
http://colab-sbx-244.oit.duke.edu:5000/players/88367253

Is this working?

**Comment by TommyLjung** [comment]
## YES, that did it  @howardchung !
Thanks for the help (even though this probably didn't affect a lot of people) :) :+1: 
Now it works in the Overview, but not in the Heroes section... But I guess you just added it on 1 place to start with?
See pictures below!
![yaspbug_solved](https://cloud.githubusercontent.com/assets/3416502/13985668/5782638c-f0fe-11e5-9142-c3900834abc5.PNG)
![yaspbug_solved2](https://cloud.githubusercontent.com/assets/3416502/13985670/5af19830-f0fe-11e5-9bb4-4ad042a2b560.PNG)

**Comment by howardchung** [comment]
That one might be trickier:

Here's the code:
```
                    if (!Number(data)){
                        return "never";
                    }
                    return moment(data, 'X').fromNow();
```

So it appears that the Number(data) itself is returning false.

**Comment by TommyLjung** [comment]
And `data` is a unix timestamp or a date here?

**Comment by howardchung** [comment]
it should be timestamp.  But something about safari on iphone is causing
the parse to fail.

**Comment by TommyLjung** [comment]
I know you are using MomentJS for this, but could this be something?

http://stackoverflow.com/a/5324266
http://stackoverflow.com/a/3085993

But since I can't debug this right now, I might have run out of options... :(

**Comment by howardchung** [comment]
At this point it's not a problem with the date parsing.  Number(data) itself is returning false.  IDK if it's a problem with "data" or with the Number() implementation.
