### ISSUE TITLE
Requesting parse of game which is not recorded by Steam is giving me a loss

### ISSUE THREAD

**Issue by dartharaknus** [yasp-dota/yasp#870]
My player profile: https://yasp.co/players/112511169/matches

Today I had a very tough game which had a player abandon before first blood and was considered not recorded by steam. And I can confirm it's not recorded from the match list and API result given by steam.

But I wondered what happens if I try to parse it using the request page. This is the match link. https://yasp.co/matches/2141661336

As you can see, we won the match, but if you go to my player profile this match is being credited as a loss.

**Comment by howardchung** [comment]
I think someone else reported this as well.

We pull the data from the GetMatchDetails endpoint, where the match exists.  However the "radiant_win" field is undefined, which means the default is to consider that Dire won.

The match should not count toward win/loss totals or aggregations.
