### ISSUE TITLE
Sum damage crosstables

### ISSUE THREAD

**Issue by liboz** [yasp-dota/yasp#873]
There should be a sum total at the bottom/right side where the total Damage Taken/Done per hero is shown. What I mean is in for example: https://yasp.co/matches/2147794398/combat

Sand King's total damage taken/done to all heroes should be shown on a new column on the far right as 15/23.3 and Huskar's total damage taken/done  should be shown in the first column in a bottom row as 26.9/24.4

**Comment by howardchung** [comment]
Maybe some client side summing.  Need to be a little careful since we have JS that transforms the number into the friendly value (with "k").  We either need to save the real value somewhere we can still treat it as a number or make sure to do the summing before we transform the data.

**Comment by coreymaher** [comment]
I attempted to do this, but it made the table too wide.
See:
![screen shot 2016-04-29 at 10 54 45 pm](https://cloud.githubusercontent.com/assets/100885/14933445/9735fb20-0e5d-11e6-9eb6-a4f7ad18caa8.png)

Any suggestions?

**Comment by howardchung** [comment]
Shrink the text maybe?

**Comment by coreymaher** [comment]
Unfortunately I couldn't get it to fit without making the font significantly smaller and removing the player name.

**Comment by howardchung** [comment]
smaller cell padding maybe

**Comment by coreymaher** [comment]
Here's what it looks like with a smaller font size and less cell padding.
![screen shot 2016-04-30 at 12 24 21 am](https://cloud.githubusercontent.com/assets/100885/14933854/7e41bda4-0e6a-11e6-9f69-e2229b6ab4e0.png)

Here's the original without the totals for reference.
![screen shot 2016-04-30 at 12 36 38 am](https://cloud.githubusercontent.com/assets/100885/14933891/ac6bc7dc-0e6b-11e6-93ba-4d097be65da1.png)

I'm afraid that the smaller font size and padding makes the numbers harder to read especially with longer matches and long player names, but it's up to you guys.

**Comment by howardchung** [comment]
Anyone else have input?  It looks fine to me.

**Comment by coreymaher** [comment]
I've opened pull request #1008 with my changes if you guys think the size is okay.
