### ISSUE TITLE
Sort order of skill is incorrect.

### ISSUE THREAD

**Issue by aoisensi** [yasp-dota/yasp#875]
![](https://i.gyazo.com/bbb729278de0756466ab9b78b4b75d0e.png)

**Comment by howardchung** [comment]
I think it's just alphabetical.  Could define custom sort order, I suppose.

**Comment by likered** [comment]
A normal player will probably be in one skill bracket for the majority of the time, only at a certain time period will the player actually move from one skill bracket to the next (for example, Normal -> High Skill or High Skill -> Very High Skill). So I don't think this will be very applicable most of the time. Of course, you could argue that if you play in a party with a friend(s) who's very high or low in skill will change your skill bracket.

**Comment by howardchung** [comment]
Personally I see quite a bit of fluctuation myself but considering there
are only 4 possible values sorting isn't a huge deal

**Comment by aoisensi** [comment]
:+1:
