### ISSUE TITLE
'Abandoned' flagging

### ISSUE THREAD

**Issue by TrentBartlem** [yasp-dota/yasp#886]
When showing a match, Dotabuff puts a little 'abandoned' note near a player's name if they abandoned it.

Is is possible to do something similar in Yasp?

**Comment by howardchung** [comment]
Yes.  There's a field called "leaver_status".  Pretty easy beginner project if someone wants to try it.  Otherwise I might get to it in the next few weeks.

**Comment by howardchung** [comment]
It would help if you have a match ID of a match where someone abandoned so we can test on it.  Otherwise I suppose we could fake the value...

**Comment by TrentBartlem** [comment]
http://www.dotabuff.com/matches/2155672115

vs

https://yasp.co/matches/2155672115
