### ISSUE TITLE
React single page application

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#889]
We may move toward this in the future.

However, we have already invested a ton of development into our current system (Jade templates, pages rendered server side), and this would probably take weeks if not months (considering neither @albertcui or I am able to spend 6+ hours a day on this anymore).

The main purpose of this would be to get practice using React in a decent-sized application.  I like React because it's simple and unopinionated (unlike something like Angular that brings a lot of things that we probably don't want or need and forces you to do things in a very specific way).

Performance-wise we might see some benefits from not having to reload the whole page every time.  However in practice most of the heavyweight resources (images, JS bundle, etc.) are cached by the browser and not freshly loaded.

Main points we'd have to hit:
- [x] expose everything as APIs we can call to get back JSON that populate boxes on the page
- [x] bring in something like react-router in order to allow the URLs to still work and users to share URLs
- [x] figure out login
- [x] figure out blog routing (moved to github pages)
- [ ] redesign the UI (if we're going to the trouble of rewriting all our templates we may as well overhaul the views with bootstrap 4.0 or material design)
   - [ ] rewrite our CSS, since it's pretty janky right now
- [x] set up some kind of staging subdomain that uses the new UI (beta.yasp.co) so we can run it in parallel with the old UI in production
- [ ] set up api for mmstats/carry routes (@albertcui)
- [ ] figure out google analytics
- [ ] page titles

**Comment by Iparke** [comment]
This may interest you in case you decide to go with material design:
http://www.material-ui.com/#/home

**Comment by bguzryanto** [comment]
react-router support isomorphic app, so we can maintain match, player, etc URLs. Using React + Redux will help a lot on development (Redux might be the winner on the React community).

I prefer using beta.yasp.co rather than (framework specific subdomain). I think yasp's users do not really understand what is react.

**Comment by howardchung** [comment]
Looks fun.  I'll put it in the May milestone, but it'll probably be an ongoing project.

**Comment by howardchung** [comment]
I'll probably start with some kind of base template, and maybe those interested in helping can help build bits of it at a time (maybe convert a couple of tabs to react components)

**Comment by bguzryanto** [comment]
I open to contribute, currently I working on react + redux app for my thesis :)

**Comment by howardchung** [comment]
Thanks, your experience would be helpful.  I've only played with React briefly and never used Redux/React-Router.

**Comment by Shenlok** [comment]
Re: the point on using JSX or not. You mention adding a build step being your concern here. But since you're already running things through webpack, all it would take is to run the client-side JS through webpack's babel loader and you're done. Admittedly this is of course going to add some time to builds, but that's about the only cost, and I doubt it will be too significant compared to the benefits of writing components in JSX (at least in my opinion).

**Comment by howardchung** [comment]
Example I'm adapting:
https://github.com/erikras/react-redux-universal-hot-example

WIP:
http://colab-sbx-244.oit.duke.edu:5000/public/index.html

**Comment by bguzryanto** [comment]
@howardchung  have you checked mern.io boilerplate?

I got invariant error
![screen shot 2016-03-13 at 11 36 32 am](https://cloud.githubusercontent.com/assets/198174/13726938/1ccf637a-e910-11e5-81ca-2eda913d87f8.png)

**Comment by howardchung** [comment]
Yeah the footer is broken.  You can get rid of the content in it

**Comment by howardchung** [comment]
I fixed it

**Comment by kkotwal94** [comment]
I'd like to try to contribute as well :/ am a react guy that uses material ui, reactrouter, I see you guys like using node too, I feel like this boilerplate may suite your taste. https://github.com/choonkending/react-webpack-node

**Comment by howardchung** [comment]
I've never used react-router and am trying to figure out what exactly it does/how it works.

So far with React/Redux I've been able to set up a simple layout with a navbar, container, and footer.  I'm able to fetch the navbar elements from the server via API call (matches/players would use the same workflow).

See `public/js/components/app.jsx` for entry point.

**Comment by howardchung** [comment]
Update:

* I've added react-router to the project
* Development now starts with `npm run webpack-dev-server`.  This starts up the dev server (on port 8080).  It will proxy api requests over to the config.ROOT_URL (which is by default the address of `web`), so you need that running as well.

**Comment by howardchung** [comment]
Progress:
https://github.com/yasp-dota/yasp/commit/c56e477051e86000943bb83eb29277eaa1ae27e6

* I decided to store basic page metadata (navbar/tab items, logged in user, cheese status, etc. in a single "metadata" object in the React/Redux state).  This means fewer separate API calls.
* Created a "content" key to hold the main page data.  The actions will share the same reducer (maybe), whether it is match, player, distributions, picks, etc.
* @albertcui needs to figure out how mmstats/donation endpoints will fit into this.
* I'd like to move away from Poet and to something better suited for SPA.  Poet doesn't work well with React.

**Comment by howardchung** [comment]
WIP: http://colab-sbx-244.oit.duke.edu:8080/

I have stripped out the CSS for now.

**Comment by howardchung** [comment]
Update:
* Able to fetch match data (see Match component).
* Players may be a bit trickier.  The match data comes all at once in one big blob, and can be reused between tabs.  Players get different data back based on on tab.  This is for optimization/performance purposes, since it's more expensive to project/aggregate extra columns.

**Comment by masad-frost** [comment]
If you're planning on rewriting the CSS, might wanna take a look at CSS in JS (inline-styles), Facebook's Vjeux gave a [talk](https://vimeo.com/116209150) about it, here's the [slide deck](https://speakerdeck.com/vjeux/react-css-in-js) too.

You kinda need a library to use it with to make a lot of things easier for, here's a couple comparison tables:

- https://github.com/MicheleBertoli/css-in-js
- https://github.com/FormidableLabs/radium/tree/master/docs/comparison

I personally use [Radium](https://github.com/FormidableLabs/radium/) in production and it's great. I've faced some issues here and there, but usually the workarounds are quite simple and the fixes come quick.

If you're planning on using bootstrap/material, there's not harm it's still ok to use it in [conjunction with inline styling](https://github.com/FormidableLabs/radium/issues/323). 

Appreciate your work.

**Comment by howardchung** [comment]
Current example:
http://hchung.westus.cloudapp.azure.com:5000/matches/2387115636

(note this may not stay static as I swap branches to work on different things)

**Comment by mike-robertson** [comment]
I'm interested in adding to this. Is there a list of todo's regarding this? I also think that separating the container component from the dumb component code could be useful. Structuring things like Navbar > Navbar.container.js, Navbar.jsx, Navbar.css Navbar.spec.jsx might be more maintainable. If you wouldn't mind, I can put together an example and submit a pull request with some changes to the structure/architecture of what you have already. Also, do you have any thoughts on using something like CSS Modules? Not the same as radium, but it is another solution that plays nicely with components.

**Comment by gu3st** [comment]
From experience with doing UI (a different project), having CSS being done in code in the component is extremely nice to use. Radium fills the few "flaws" that the stock React component styling suffers from (namely :hover).

**Comment by bmulcahy** [comment]
Just converted a ampersand view/ Jade template site to use react I can help if needed

**Comment by bmulcahy** [comment]
For CSS you should use styl loader with webpack and babel

**Comment by mike-robertson** [comment]
I am doing some work on making the current react application as it exists under /public/javascript to conform to some better standards and architectures for react applications (as outlined in my other comment) as well as implement linting for the code. I'll put in a pull request once I've done that so people can decide whether that is the direction to go for the react spa.

**Comment by mike-robertson** [comment]
I submitted a PR. I'm pretty new to doing open source stuff so let me know if I messed something up. Let me know general thoughts on whether that seems like the right direction or not.

**Comment by howardchung** [comment]
Please see https://github.com/yasp-dota/ui/issues/3 for updates
