### ISSUE TITLE
Use zsets for counting distributions/picks

### ISSUE THREAD

**Issue by Jemsuper** [yasp-dota/yasp#890]
The most picked solo hero is at 16k games. The second most picked 5 man team is at 7 games. Unless yasp soft parses all games like dotabuff the data from that page has way too much variation to all normal games.

**Comment by howardchung** [comment]
Right now I have it checking the last 50,000 games every hour and recalculating the stats.

I'm actually working on using Redis zsets to improve how we calculate this (so we can do a rolling window over the last week, etc.)

**Comment by howardchung** [comment]
Decided not to do it for distribs/lobby type (last 100,000 games), but modified picks to count those in the last day (usually 1.2-1.5 million matches)

**Comment by Jemsuper** [comment]
That sounds a lot more usefull! Goodjob and thanks!

**Comment by howardchung** [comment]
It won't be rolled out for a while because it's sitting on top of a lot of other changes that I need to verify/test, but hopefully in the next few weeks.

**Comment by howardchung** [comment]
Bit of a change.  In order to avoid having to track a time for each result, which is required to expire old data, we are now doing a single counter that only resets when we manually do it.
