### ISSUE TITLE
Better status page for requesting matches

### ISSUE THREAD

**Issue by paralin** [yasp-dota/yasp#894]
Currently there's a huge backlog of ~1400 matches in the queue to be parsed.

When you submit a match parse request it will just sit at the 100% upload complete screen for hours until the match is parsed.

Maybe implement a better status page for pending matches?

**Comment by howardchung** [comment]
Yeah, I thought about making a "job status page" when you submit a request.  However we don't have a good way of looking up a job's current queue position.

**Comment by howardchung** [comment]
The idea is that there shouldn't really be a queue wait.  If the queue is building there is a systematic problem and we should be doing something about it.  Most recently it's been slow replay downloads from China.
