### ISSUE TITLE
slow china replay download

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#895]
Currently China (perfect world) replays currently download really slowly and can take minutes to finish.  This holds up parsing for the rest of the matches.

We either need to:
* Set a more aggressive timeout on parses
* Put china matches in a separate queue

**Comment by albertcui** [comment]
Voting for china queue.

**Comment by howardchung** [comment]
initial mitigation: clean up parse jobs delayed more than 1 day so we don't build up a backlog of slow parses.

If it keeps happening I'll look at making a separate queue but I don't really want to split the queue.

**Comment by howardchung** [comment]
haven't seen in a while.  Will reopen if it becomes an issue again.
