### ISSUE TITLE
allow filter options on picks

### ISSUE THREAD

**Issue by rossengeorgiev** [yasp-dota/yasp#897]
`Tetrads` and `pentads` are currently dominated by exactly these matches.

Those players aim for 10min matches. I suggest filtering out matches under 15min. That should be sufficient to cut down their influence to a minimum.

**Comment by howardchung** [comment]
merge with #890.

It's possible that expanding the sample will reduce the impact of this (since short matches have less of a presence).

If it's still a problem I might consider the length filter.  However, I want the data to be as representative of what's actually going on in Dota as possible.

**Comment by rossengeorgiev** [comment]
I don't thank expanding the sample will reduce it. The pick these particular heroes for a reason, so you will end up with even more matches. Even after the major, there still be charm farmers. Filtering ultra short matches seems like the best approach. 

> However, I want the data to be as representative of what's actually going on in Dota as possible.

That would be hard due to the diversity of modes, lobby types and regions. I hope `ability draft` is not includes in those stats. It would be nice if you could filter pick combinrations by region, or mode, or ranked/unranked.

**Comment by howardchung** [comment]
I will reopen the issue as allowing filters.  Basically we have to retain a separate set of counts for each filter option.  The memory impact might be too much.

**Comment by howardchung** [comment]
I don't think we can support this.  The current implementation is to just keep counts and clear them whenever the total exceeds 10 million.  In order to do daily/weekly counts we'd need to store them under separate keys and then ZUNIONSTORE them.  This would probably be upwards of 1GB/day, and I'm not sure the performance is acceptable either.
