### ISSUE TITLE
Ability upgrade data expiring?

### ISSUE THREAD

**Issue by waitwhereami** [yasp-dota/yasp#899]
All of my recent matches are displaying the following error message where the ability graph should be displayed:

"ABILITY UPGRADE DATA HAS EXPIRED FOR THIS MATCH. 
USE THE REQUEST FORM TO RELOAD DATA. MORE INFORMATION HERE."

Example match ID: 2169364021

**Comment by waitwhereami** [comment]
Additionally: The ability data displays correctly shortly after the match is played, but vanishes and shows the error after a period of time (haven't had time to nail down the exact cause).

**Comment by albertcui** [comment]
For some reason the "more info" link is wrong. This is the right one:
https://yasp.co/blog/37

This is expected behavior.

**Comment by albertcui** [comment]
Link issue is probably because of adding FAQ blog posts. This is why we
should be able to link directly to blog post names.

**Comment by howardchung** [comment]
Or FAQ posts need to be dated serially. Up to you on the fix

**Comment by waitwhereami** [comment]
Ok, that makes sense. I read the blog post linked, but it didn't make much sense with regard to the issue. This can probably be closed then.

**Comment by albertcui** [comment]
The issue with dating is that since we show them date wise, they'll show up
if people browse the blog. Ideally they don't show up at all. Right now we
just back date them a while back so they don't show up immediately.

**Comment by howardchung** [comment]
True.  We should fix this ASAP since this is high visibility.

**Comment by howardchung** [comment]
@albertcui fixed
