### ISSUE TITLE
Request parse of damage received.

### ISSUE THREAD

**Issue by mm11wils** [yasp-dota/yasp#903]
A useful feature is the biggest hit feature, but the team and I often try to imagine the sources of the damage our hero has received and where the biggest source of damage is coming from. So perhaps we could have a feature that shows the amount of damage taken and have it split between what damaged us.

Eg. If a bristleback is focused - it would be nice to see how much damage he was able to soak up for the team.

**Comment by howardchung** [comment]
Like inflictors but for received?

If you're just interested in the hero the damage is coming from the damage crosstable already shows that.

**Comment by mm11wils** [comment]
Like inflictors but for received.

**Comment by howardchung** [comment]
Heroes only or all sources?

**Comment by mm11wils** [comment]
Heroes only.

**Comment by howardchung** [comment]
Okay, this can be done.  If someone wants to try taking it on it shouldn't be too difficult.  I'm more motivated to work on the React SPA atm rather than doing this, but maybe if I get bored.

**Comment by likered** [comment]
Wouldn't it be cool to have this for the Teamfights page too?

And also have some sort of time-log for when auto-attacks/skills are used so we can see who's being focused during that teamfight. Will be useful for people to find out: "Oh I made a mistake of targeting a low-priority target in the teamfight, hence we lost that teamfight"

**Comment by howardchung** [comment]
Yeah but since we need to store this data for every fight we may not be
able to afford it.  Donations haven't been great lately.

Logging every spell cast would be even more expensive.

**Comment by howardchung** [comment]
So one thing of concern is that you generally don't have more than 5 or so sources of damage, but you'll probably be hit by 20+ different damage sources throughout a game.  The table might look messy/cramped if we try to cram it into another column.

**Comment by howardchung** [comment]
This should be doable with current data (doesn't require a parser modification).

I'm thinking about creating a new "damage" tab for the inflicted/received data and showing it there.

**Comment by howardchung** [comment]
nvm this requires a parser-level edit (not strictly the Java parser), but we need to expand the damage event, reverse it and create a new field for damage_inflictor_received.

With the current data we only know how much damage was dealt with each inflictor for each hero, but not to whom, so we can't just reverse it to build received damage sources for all players.

I will stick my progress so far (just the template edit, really) into a branch and maybe revisit this later.

**Comment by mm11wils** [comment]
Keep up the good work Howard! <3

**Comment by howardchung** [comment]
I will take another stab at this after the Cassandra migration completes.  I don't want to make any schema changes during the migration.

**Comment by howardchung** [comment]
Actually schema change doesn't seem to bad.  I'll see if I can implement this later tonight.

**Comment by howardchung** [comment]
@albertcui do you want to review and release this next weekend?  or later in june?
