### ISSUE TITLE
Which value of damage is correct?

### ISSUE THREAD

**Issue by aqb66967euaqacom** [yasp-dota/yasp#904]
For example
2185290756 - id match
Hero - witch doctor

OVERVIEW > HD (Amount of damage dealt to heroes) = 29.4

PERFORMANCE > UTILIZATION > Damage Inflictors (Damage dealt to heroes by skills/abilities)= 14.8+10.9+6.2+6.0+2.3+0.7+0.6+0.5=42.0

![2016-02-29_120927](https://cloud.githubusercontent.com/assets/17542430/13390128/72466a20-dedd-11e5-9419-be697363c984.png)
![2016-02-29_120910](https://cloud.githubusercontent.com/assets/17542430/13390129/724704bc-dedd-11e5-8f39-9bb99924f494.png)

**Comment by howardchung** [comment]
First is from Steam WebAPI.

Second is from combat log.

For some reason the WebAPI value tends to be lower.  I am not sure why, but I'm inclined to think that the combat log is more accurate.
