### ISSUE TITLE
Picks: above/below the average?

### ISSUE THREAD

**Issue by TrentBartlem** [yasp-dota/yasp#908]
(This only makes sense for dyads or triads)

So, the 10th most common dyad right now is Pudge / Slark with a pick rate of 2.73%.

Given the monad data, would it be possible to state whether this is expected given the pick rates of Pudge and Slark, or whether this is something that is unusual? I.e. if there's a Pudge on the team, do people pick Slark instead of another hero or vice versa, and thus make that combo more common than you'd expect to see based on monad pick rates?

I think this should show some insight - for instance, for dyads, the most common pairs with Omni are:

* Omniknight / Invoker (1.62%) - but Invoker has >30% pick rate anyway.
* Pudge / Omniknight (1.38%) - but Pudge has >30% pick rate anyway.
* **Omniknight / Outworld Devourer** (1.36%) - OD's pick rate is 15%.

OD is 14th-most popular yet the duo is picked a lot more often than Omni/LC (who is 3rd most popular and thus what you'd expect to see above OD just based on LC's massive 25% pick rate), so having a column to show that this is noteworthy would be good.

**Comment by howardchung** [comment]
Yeah, this has been requested.  Would the mean of the single pick rates be accurate, or does it need to be weighted somehow?

same question for winrates.

**Comment by TrentBartlem** [comment]
Actual Invoker = 31.81%
Actual LC = 25.73%
Actual Invoker/LC = 4.38%

So, more like pickRateA x pickRateB / 2 (half the time they will be picked on opposite sides)

That calculates to: 4.09%. I'm still dubious about how I arrived at that figure, so I'd appreciate someone who knows statistics chiming in :)

**Comment by howardchung** [comment]
Looks good for picks.  How about the win rate?

**Comment by TrentBartlem** [comment]
That's more likely to be a straight average of the two.

**Comment by howardchung** [comment]
implemented
http://colab-sbx-244.oit.duke.edu:5000/picks/3

**Comment by TrentBartlem** [comment]
Nice. Is it possible to hide those columns for Monads, since they're not really useful?

The left-aligned bar chart doesn't really work for +/- values - is it possible to have positive values be in green from the centre of the div to the right edge, and negative values be in red from the centre back to the left edge?

**Comment by howardchung** [comment]
Could hide them but it's also good to be consistent across the pages.

Yeah I know the bars don't work well for negative values.  It would require some custom code to handle that though.  A simpler alternative is just not to have bars for that column.
