### ISSUE TITLE
Recaptcha timeout and replay files

### ISSUE THREAD

**Issue by iSamuraii** [yasp-dota/yasp#909]
Hello, I found a little issue, with a crappy internet connection (~99% of the Italian ones) if I try to upload the replay of a long match (at least one hour it seems) takes so much time that the recaptcha challenge expires, the uploaded file is discarded and you need to reupload it, repeating the same problem; TLDR, you can't parse a match without changing network.
Is it possibile to do something about it? The best thing for me probably will be to find a better connection (sadly it isn't so easy, months that I fight with my ISP) but the problem still remains, can you do the challenge after the upload of the replay? Best regards ;).

**Comment by howardchung** [comment]
yeah, I don't know how best to deal with this.  maybe we should just disable recaptcha for uploads

**Comment by howardchung** [comment]
disabled verification for uploads
