### ISSUE TITLE
Courier upgrade delay is counted for subsequent couriers

### ISSUE THREAD

**Issue by GIider** [yasp-dota/yasp#911]
If you buy a 2nd courier and upgrade it, the yasp analysis will rate your upgrade delay on the second one.

A example match can be found here: https://yasp.co/matches/2203500046/analysis
Void buys a second courier 37 minutes in and upgrades it, receiving an F in courier upgrade delay (2067 seconds vs 20).

I think yasp should ignore courier upgrades after the first.

**Comment by WTFKr0** [comment]
Similar to #813

**Comment by howardchung** [comment]
duplicate of #813
