### ISSUE TITLE
HTTP 500 on my profile page

### ISSUE THREAD

**Issue by shinshenjs** [yasp-dota/yasp#914]
Not sure if this is the correct place to report this issue but I couldn't find anywhere else to do so.

My profile page at https://yasp.co/players/118598960 is stuck on HTTP 500 Internal Server Error permanently. Initially I though it was just a temporary server issue. I can't remember since when it started but it should be weeks/months at this point.

**Comment by howardchung** [comment]
additional repro:
https://yasp.co/players/114459625
https://yasp.co/players/78166115

**Comment by howardchung** [comment]
should be fixed via making all cassandra fields text
