### ISSUE TITLE
Match show up very slowly

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#916]
It takes a really long time for the matches to show up in the list, usually 30+ minutes. I think the matches showing faster is more important than parsing them for additional statistics because most players won't read them for most matches.
Can you disable the automatic parsing or make an on/off switch setting?

**Comment by howardchung** [comment]
This isn't a parsing problem but due to the API responding slowly.  It
might be exacerbated by the complete match history report we're doing now
though.

**Comment by Vali19n** [comment]
I see. Close the issue.
