### ISSUE TITLE
Trends - KDA calculation is broken

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#918]
I think the only variable that is changed in the calculation process is the number of matches because the result only gets smaller and by somewhat similar amounts (with a few exceptions).
https://yasp.co/players/257861991/trends/kda

**Comment by howardchung** [comment]
hmm it does look weird.  It doesn't seem to be a problem with the other fields though.

**Comment by howardchung** [comment]
Okay, I think I know what's happening: the data is getting overwritten when we parse the match.

**Comment by howardchung** [comment]
We do the calculations here prior to cache insertion:
https://github.com/yasp-dota/yasp/blob/master/compute.js#L94

However if the match is parsed we don't have the kills, etc. so it just comes back as 0.

**Comment by howardchung** [comment]
okay I think it should be fixed for future matches.  However we'll need to dump the cassandra cache to correct existing data.  Since that slows down loads for everyone we probably won't do it right now.

**Comment by Vali19n** [comment]
Thank you for the fast response and fix.
