### ISSUE TITLE
Excluded players filter

### ISSUE THREAD

**Issue by onelivesleft** [yasp-dota/yasp#921]
It would be good to have an additional match filter under synergies: The Players Did Not Include.  This would allow you to view your solo queue matches.  

Additionally, some way to exclude all players who appear on your Peers tab would be helpful (like a button next to the filter to auto-add them).  This would also be handy to have for the Players Included filter too.

**Comment by howardchung** [comment]
Did not include might not be too hard (just needs a new field in the UI + filter in filter.js)

**Comment by howardchung** [comment]
Loading friends: We may want to make this an API call since it can be potentially slow to do synchronously.
