### ISSUE TITLE
Estimate MMR : base on matches currently filtered

### ISSUE THREAD

**Issue by onelivesleft** [yasp-dota/yasp#922]
As it stands the estimate is heavily warped by party play.  Making it ignore matches which include any Peers would help, but a better solution might be to have an estimate displayed based on the matches that are currently filtered.  This would allow players to gauge the MMR of their solo games as well as with specific groups of friends, dictated by whatever filters they have applied.

**Comment by howardchung** [comment]
Can consider it.  For performance reasons we probably want to send the list of match IDs to the server to avoid having to re-filter.

**Comment by howardchung** [comment]
After thinking about it I think this will probably fragment the result too much.
