### ISSUE TITLE
Compute average MMR and percentile for matches

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#923]
Wouldn't it be more interesting and/or helpful to have the players' skill level based on the other players like the IQ is calculated? Also, for this you should calculate the average(the exact integer, not the range) every week or so to keep it updated and store the mmr in a match, not the skill range, because the average may change and updating the skill for every match won't be a great thing.

The system should work like this: 
- store average mmr of the players in the match(10 players) as a match property(match.avg/skill/mmr)
- when someone sees that match in the matches/overview tab, compare the match average with the average of everyone(10000000 players)

Example of skill ranges in case the average is 3k:
    below average(100 to 35% below)
    low average(35 to 25% below)
    average(25% below and 25% above 3k) = 50% of the players
    high average(25 to 35% above)
    above average(35 to 100% average)

Something like this: https://qph.is.quoracdn.net/main-qimg-a5a6f1c8861ec17a6d5d3727aa1b693a?convert_to_webp=true

PS: I know that you only have data for the players that both have their mmr set as public and have an yasp account. I still think this may be a good idea.

EDIT:
This will work only for ranked matches. For normal matches you can either keep the current system or try to talk to Valve into giving you acces to the private mmr or use my system idea by making an average based on the other players in the match if they calibrated.

**Comment by howardchung** [comment]
Users don't need to have an account.  I think we can do this though.

**Comment by Vali19n** [comment]
I've edited my post.

**Comment by howardchung** [comment]
Question to answer:

* Do we need to persist the match average rating?  Or would it be fine to keep it for a retention period (say a week?)
* In either case the matches we benchmark it against will definitely need some kind of retention.  I don't think we can feed a million matches per day into Redis without cleaning it up at some point.
* That means that even if we retained the match average rating data, we would have to compare it against matches played recently (say, the last week or so).  Is it accurate to compare an old average (say, a year old) rating with the spread of matches played recently?

**Comment by Vali19n** [comment]
What I meant for comparing in the skill calculation process is the average mmr of the players (https://yasp.co/distributions) with the average mmr of the matches the user views on his or someone's profile(overview and matches), not with the other matches of that user.

For the retaining period I'm thinking about the last 20 or so matches played in the last week because some people can play more than 20 matches/week and it will take even more space.
For the matches that get their skill/mmr property removed, there should be an automatic recalculation of that property when the user views a match on his or someone's profile(overview and matches). This data should be retained for a day or less.

**Comment by howardchung** [comment]
I don't know if it will be accurate to compare an averaged match MMR with the player distribution.  Aren't those two different things?

**Comment by Vali19n** [comment]
I meant comparing the average match mmr with the average distribution mmr. Why wouldn't it be accurate?

**Comment by howardchung** [comment]
I guess the problem wouls be with the ends of the distribution.  The players in the top and bottom will likely be beyond the range possible in averages. So the match with the highest MMR average would not be the 100th percentile, but somewhat lower.  It might be more accurate to compare matches to matches.

**Comment by Vali19n** [comment]
If you think your method is better, do it your way.
