### ISSUE TITLE
Why is the paypal button hosted on 'braintreegateway'?

### ISSUE THREAD

**Issue by DavidVentura** [yasp-dota/yasp#928]
I have NoScript on and could not see the paypal button. Why is this image/script hosted on a third party server?

**Comment by albertcui** [comment]
Braintree is a PayPal company. Their API is much better than PayPal's. See
https://www.braintreepayments.com/

**Comment by albertcui** [comment]
To more directly answer the question, payment processors host their own
assets. The Stripe and Braintree scripts all come from their own servers as
a security measure.
