### ISSUE TITLE
Error Cloud9 create

### ISSUE THREAD

**Issue by Soetiz** [yasp-dota/yasp#932]
Hi, I get this error when i try do create Yasp on cloud9;
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.4.0/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'create' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'precreate', 'create', 'postcreate' ]
5 info precreate yasp@6.0.0
6 info create yasp@6.0.0
7 verbose unsafe-perm in lifecycle true
8 info yasp@6.0.0 Failed to exec create script
9 verbose stack Error: yasp@6.0.0 create: `bash sql/create.sh`
9 verbose stack Exit status 2
9 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid yasp@6.0.0
11 verbose cwd /home/ubuntu/workspace
12 error Linux 4.2.0-c9
13 error argv "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/npm" "run" "create"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error yasp@6.0.0 create: `bash sql/create.sh`
17 error Exit status 2
18 error Failed at the yasp@6.0.0 create script 'bash sql/create.sh'.
18 error This is most likely a problem with the yasp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     bash sql/create.sh
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs yasp
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls yasp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Any thing anyone have seen before and can help me with ?

**Comment by howardchung** [comment]
I think postgres 9.5 needs to be installed.  Can you try following the postgres install instructions?

**Comment by howardchung** [comment]
I think this was fixed (quotes in the node version)
