### ISSUE TITLE
"npm run build" Failure

### ISSUE THREAD

**Issue by alasher** [yasp-dota/yasp#933]
First of all, I'm very happy with what Yasp has done for the Dota community, and I'm trying to set up an environment to begin contributing to such a great project. 

I cannot use "npm run build", it looks like it fails during the "npm install" phase. To recreate: clone master, and run "npm run build" on main directory. I am using Node v5.9.0 and npm v3.7.3, and used brew to make sure these are up-to-date.

Here is a screenshot of me cloning the repo, and running "npm run build".
![yasp_err1](https://cloud.githubusercontent.com/assets/6944190/13965950/bb9caf34-f046-11e5-9184-ef4e86a7cf12.png)

I do mostly C++ work and am new to using Node/NPM, so it's possible that this is a simple error on my behalf. However, my thought was that if all I did was exactly follow the directions, something had to be wrong: either an error in the package or the actual directions. I thought that was enough to warrant an issue on Github.

If necessary, I can follow up with my npm-debug.log file.

**Comment by howardchung** [comment]
Yeah, will need more logs to see where it failed.  Looks like you're using a Mac.  Any Mac users seen this before?

**Comment by alasher** [comment]
Yes, using OS X 10.11.4. Here's my npm-debug.log file: [npm-debug.log.txt](https://github.com/yasp-dota/yasp/files/184878/npm-debug.log.txt). If more log files are necessary, just let me know which.

**Comment by howardchung** [comment]
Hmm the log isn't telling me very much.  Try running the commands separately (like just npm install)

**Comment by alasher** [comment]
Yeah, that's how I narrowed down it was just npm install. Just doing that only gives the first error: npm ERR! cb() never called!

I have Ubuntu 14 at home, I'll play around with getting it running there and compare. If anything, from this I can help make and test a more stable OS X build script.

**Comment by howardchung** [comment]
It should work on Ubuntu 14 (that's what we use for development).

The community maintains some directions for non-ubuntu in the wiki.
https://github.com/yasp-dota/yasp/wiki/Installation-for-other-platforms

It might be out of date though.  I see it still refers to mongodb

**Comment by waitwhereami** [comment]
+1. I have tried building yasp on c9.io using the readme instructions and had the same error.

**Comment by howardchung** [comment]
Tried again and found some issues with Java (so parser won't build).  The script is trying to add-apt-repository to get Java 8, but cloud9 doesn't allow us to do that apparently.

Solutions:
* Build with Java 7
* Don't use hosted c9 (we actually use c9 with the ssh option, which is basically bring-your-own-machine with the c9 UI)

**Comment by howardchung** [comment]
Okay, I've fixed the java install for c9 and it should work now.

This doesn't have anything to do with the cb() issue reported here, though, so I'll leave this open until someone can repro/figure out what's wrong.

**Comment by howardchung** [comment]
Likely outdated.  If you have issues with the new Docker-based dev env please let me know
