### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by Jefftopia** [yasp-dota/yasp#938]
Not so much a problem as a question...How do you manage accounts for pulling replays? My understanding is that there's a cap of 100/account/day. Do you have scripts that create accounts and login with one, or do you manually create them and store somewhere? Last, I haven't had any luck logging in via node-steam without 2fa tokens, but I didn't see use of 2fa in your scripture. What do you do instead?

**Comment by howardchung** [comment]
Nothing fancy--we just have a big spreadsheet with accounts and put them in config.  By default Steam Guard is off so we don't need need 2FA

**Comment by Jefftopia** [comment]
@howardchung Thanks for the info! Didn't notice steam guard is off by default.
