### ISSUE TITLE
peers not counting all matches

### ISSUE THREAD

**Issue by jonihc** [yasp-dota/yasp#940]
this may already been pointed out but I have played aloooot of games with a friend of mine and the peers tab says I only played 11, and the last one was a year ago... probably before source2?

**Comment by howardchung** [comment]
Couple of possible reasons:
* The friend is anonymous
* The games are an "unbalanced" mode like ARDM, AD, etc.

**Comment by jonihc** [comment]
Guess you're right
my frind is registered here also. I play with her since 2013. I would say 90% fo the games were in All Pick (normal MM).
and I am sure (its a fact) I played with her very recenty and not (8 mounths ago).
Another weird thing is that her profile shows games from 8 months ago, and older. same as Dotabuff, thought she registered there too.

and she has match data exposed in dota options. weird.
might be another osfrog thing.
thnks anyway.

**Comment by howardchung** [comment]
"Registered" (signing in) doesnt affect anonymity.  There is an option called "expose public match data" that needs to be enabled.
