### ISSUE TITLE
ESTIMATE MMR Always showing N/A

### ISSUE THREAD

**Issue by quenelledota** [yasp-dota/yasp#941]
My Estimate MMR is always showing N/A today, yesterday it did blurt out an estimate =  4783. played a couple games today and its been all N/A for the whole day.

Account: https://yasp.co/players/329281056

**Comment by howardchung** [comment]
It is based on the last 10 games.  So if the data was from the oldest games it could have moved out of the window.  You'll have wait until you play another game with people with public rating data.

**Comment by leovarmak** [comment]
In the confidence level it is showing as +/- 1289. And normal estimation is 1633. So does this mean my mmr is around 1289 or 1633 based on the recent games ?

**Comment by howardchung** [comment]
it means the average MMR of the recent matches you've played is 1633, and that the standard deviation is around 640 (which is pretty high).  This can happen if you play a mix of ranked/unranked and have a high rating discrepancy there, or if you play with a variety of friends with different skill levels.

**Comment by leovarmak** [comment]
@howardchung Cool !
Btw this guy is my Friend [yellapupurvi](https://yasp.co/players/251941269) . There were a lot of matches played in that account including 3 tbd matches. Now why does Yasp show not data ? We did that expose matchmaking data in the game client

**Comment by howardchung** [comment]
When was the setting enabled?  Old matches will not show up (from before the setting was enabled) unless I manually run a scan for them.

**Comment by leovarmak** [comment]
We enabled the setting like a week back. He hasn't played a game since then. Is running a manual scan a pain ? if not can you run it ? If its time consuming never mind
Thanks !

**Comment by howardchung** [comment]
Nah, it only takes like 5 minutes, I'll do it now.

**Comment by leovarmak** [comment]
@howardchung It takes time for the MMR estimate to update for that account ? or it isn't possible for that account

**Comment by howardchung** [comment]
It is computed using new games, so your friend will have to play some new
ones.
