### ISSUE TITLE
RangeError: Maximum call stack size exceeded scanner.js

### ISSUE THREAD

**Issue by schadowfox** [yasp-dota/yasp#942]
With the latest copy of yasp I get the following error from scanner.js

> 12:00:09 PM scanner.1 |  [nodemon] 1.9.1
12:00:09 PM scanner.1 |  [nodemon] reading config /home/yasp/yasp.new/nodemon.json
12:00:09 PM scanner.1 |  [nodemon] to restart at any time, enter `rs`
12:00:09 PM scanner.1 |  [nodemon] ignoring: /home/yasp/yasp.new/.git/**/* .nyc_output .sass-cache bower_components coverage /home/yasp/yasp.new/node_modules/**/* /home/yasp/yasp.new/public/**/* /home/yasp/yasp.new/views/**/* /home/yasp/ya…
12:00:09 PM scanner.1 |  [nodemon] watching: *.*
12:00:09 PM scanner.1 |  [nodemon] watching extensions: js,json
12:00:09 PM scanner.1 |  [nodemon] starting `node scanner.js`
12:00:09 PM scanner.1 |  [nodemon] child pid: 25802
12:00:09 PM scanner.1 |  [nodemon] watching 217 files
12:00:09 PM scanner.1 |  connecting postgresql://yasp:yasp@localhost/yasp
12:00:09 PM scanner.1 |  connecting redis://127.0.0.1:6379/0
12:00:09 PM scanner.1 |  rebuilding sets
12:00:09 PM scanner.1 |  [SCANNER] listening at http://:::5500
12:00:09 PM scanner.1 |  saving sets to redis
12:00:09 PM scanner.1 |  set build complete
12:00:09 PM scanner.1 |  2016-03-27T10:00:09.680Z - info: getData: http://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001/?key=<SNIP>
12:00:12 PM scanner.1 |  2016-03-27T10:00:12.131Z - info: getData: http://api.steampowered.com/IDOTA2Match_570/GetMatchHistoryBySequenceNum/V001/?key=<SNIP>&start_at_match_seq_num=1975313491
12:00:15 PM scanner.1 |  2016-03-27T10:00:15.150Z - info: [API] seq_num:1975313491, matches:100
12:00:15 PM scanner.1 |  /home/yasp/yasp.new/node_modules/async/dist/async.js:769
12:00:15 PM scanner.1 |              return i < len ? { value: coll[key], key: key } : null;
12:00:15 PM scanner.1 |                               ^
12:00:15 PM scanner.1 |  RangeError: Maximum call stack size exceeded
12:00:15 PM scanner.1 |      at next (/home/yasp/yasp.new/node_modules/async/dist/async.js:769:30)
12:00:15 PM scanner.1 |      at replenish (/home/yasp/yasp.new/node_modules/async/dist/async.js:799:32)
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:818:15
12:00:15 PM scanner.1 |      at _parallel (/home/yasp/yasp.new/node_modules/async/dist/async.js:3325:9)
12:00:15 PM scanner.1 |      at parallelLimit (/home/yasp/yasp.new/node_modules/async/dist/async.js:3339:16)
12:00:15 PM scanner.1 |      at Object.parallel (/home/yasp/yasp.new/node_modules/async/dist/async.js:828:20)
12:00:15 PM scanner.1 |      at async.each.insertMatch.type (/home/yasp/yasp.new/scanner.js:144:27)
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:2874:20
12:00:15 PM scanner.1 |      at replenish (/home/yasp/yasp.new/node_modules/async/dist/async.js:808:21)
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:818:15
12:00:15 PM scanner.1 |      at eachLimit (/home/yasp/yasp.new/node_modules/async/dist/async.js:2879:35)
12:00:15 PM scanner.1 |      at Object.<anonymous> (/home/yasp/yasp.new/node_modules/async/dist/async.js:828:20)
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/scanner.js:142:23
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:2874:20
12:00:15 PM scanner.1 |      at replenish (/home/yasp/yasp.new/node_modules/async/dist/async.js:808:21)
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:814:29
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:776:16
12:00:15 PM scanner.1 |      at close (/home/yasp/yasp.new/scanner.js:188:32)
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/scanner.js:178:25
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:310:25
12:00:15 PM scanner.1 |      at replenish (/home/yasp/yasp.new/node_modules/async/dist/async.js:803:29)
12:00:15 PM scanner.1 |      at /home/yasp/yasp.new/node_modules/async/dist/async.js:814:29
12:00:15 PM scanner.1 |  [nodemon] app crashed - waiting for file changes before starting...

I'm not sure what's causing this, maybe someone got an idea?

**Comment by howardchung** [comment]
@albertcui saw this too.  I'm not sure what he did to resolve it.  Try reinstalling node modules.

**Comment by schadowfox** [comment]
I tried rebuilding all node_modules but the error persists.

**Comment by howardchung** [comment]
You can try downgrading async to 1.5.2.  It seems to be working fine in production though.

**Comment by schadowfox** [comment]
I just did that and it seems to work with 1.5.2 just fine.

**Comment by howardchung** [comment]
nodejs is the same as node.  what matter is the version of the executable when you do node --version.

For reference prod is running on 5.8.0 so perhaps you can try that

**Comment by schadowfox** [comment]
updated to 5.8.0 async.js still throwing the RangeError
tried 5.9.1 same issue

**Comment by howardchung** [comment]
@albertcui how did you fix this

**Comment by howardchung** [comment]
I asked @albertcui and he said he just ignored, didn't actually fix it.  I can downgrade async to 1.5.2.
