### ISSUE TITLE
Problem with wrong region shown

### ISSUE THREAD

**Issue by PhenomZombie** [yasp-dota/yasp#944]
There is an issue when the region of the server is not shown correctly.
As an example the match (https://yasp.co/matches/2260895240/actions) was hosted on russian valve secured server, but there is "Stockholm" is shown as a region.
Same problem here (https://yasp.co/matches/2258908814) and in other dozen of matches.

**Comment by howardchung** [comment]
I'm pretty sure the Russia server is hosted in Stockholm.

**Comment by PhenomZombie** [comment]
It is not "region" so, it is "server location". I can agree that valve servers are located in Denmark, but they are hold for russian region.
