### ISSUE TITLE
feature request: aggregate captain's draft stats

### ISSUE THREAD

**Issue by nickhh** [yasp-dota/yasp#947]
for example, what percentage of captain's draft team comps contain 1 carry 1 mid 1/2 supports etc, 5 carries, etc, and the winrate there of. possibly also compare this to aggregate data over all draft types (are captains on average better at picking "good" team comp / winning than 5 people choosing all one at a time and for themselves?)

**Comment by howardchung** [comment]
You can try using the "valve buckets" for hero roles from the heropedia;
https://github.com/yasp-dota/yasp/blob/master/json/heropediadata.json

**Comment by howardchung** [comment]
Merging with #855
