### ISSUE TITLE
Improve code organization and style

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#951]
- [x] improve code organization - we have too many files, and too many top level files.
- [x] we should probably establish/adhere to an agreed code and code organization style.

**Comment by howardchung** [comment]
Style (I typically use c9 autoformat):
* Braces: own line
* Semicolons: yes
* Indentation: 2 spaces

**Comment by albertcui** [comment]
Directory:

I think the only things that should be top level are the services that run directly - web, skill, profiler etc. Everything else should be in a sub directory. Arguably, we could put the services in a "service" directory.

**Comment by howardchung** [comment]
Created style guide wiki page.  Feel free to contribute (@albertcui and I can be the final arbiters).

https://github.com/yasp-dota/yasp/wiki/Style-Guide
