### ISSUE TITLE
Monthly top x donors

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#955]
In an attempt to improve donations, we can give higher prestige to being a top donor.

We can store a list of the top X in redis in a sorted set, keyed by account ID. The question is, what do we do about loading player information? Will this significantly impact load speeds if we're querying Postgres for X player objects per page load?

**Comment by howardchung** [comment]
There will definitely be some slowdown.

If we go React it may not be as much of a problem because you can load it asynchronously.

**Comment by howardchung** [comment]
I don't think we're doing this anymore.  Reopen if I'm wrong.
