### ISSUE TITLE
MKB mini-stun incorrect performance chart

### ISSUE THREAD

**Issue by robuhde** [yasp-dota/yasp#960]
If you look here: https://yasp.co/matches/2279611508/performances

Viper has -0.16 seconds of stuns. This is from picking up MKB I assume. Just noticed it. Not sure is this value should have a floor or if it was left open to negatives for a reason. 

yasp is the best ;)

**Comment by howardchung** [comment]
Unfortunately this is data directly from the replay and not computed by us.  We can only report what the file has.
