### ISSUE TITLE
Images are displaying at their unscaled sizes

### ISSUE THREAD

**Issue by ramatype** [yasp-dota/yasp#961]
Refreshed my YASP page today and got [this](http://i.imgur.com/wUoBVNe.png) and [this](http://i.imgur.com/ftAlZyu.png). It looks like the CSS is no longer getting applied to them. The YASP logo isn't getting width: 25px from it's class=user. The hero images aren't getting the height: 24px from class=img-sm. [Here's an imgur link to the whole album.](http://imgur.com/a/k9Q9x)

**Comment by AetherV** [comment]
Can confirm. Also have this problem on my account. Both on Firefox and Chrome.
More Images: http://imgur.com/a/oItIL

**Comment by albertcui** [comment]
Should be fixed. Thanks! Sorry about that.

**Comment by howardchung** [comment]
My bad, I tried to clean up the resumablejs dependency since we're not using it.  I'm not sure why the build passed.
