### ISSUE TITLE
Healing and Buffs not counted as "TeamFight Participation" 

### ISSUE THREAD

**Issue by Shadowys** [yasp-dota/yasp#963]
https://yasp.co/matches/2283762902/teamfights#1

For this match, omniknight used his heal, repel and ult, and was raised 2 levels, but no teamfight participation was attributed to him as he did no damage.

As of [spring cleaning](http://www.dota2.com/springcleaning/), Assists now get counted whenever you place a buff on a hero that kills an enemy hero.

I can't check the logs for the exact timing, but does Yasp count this internally or using Dota2's own calculations?

**Comment by howardchung** [comment]
Internally.

See:
https://github.com/yasp-dota/yasp/blob/master/compute.js#L581
(determine whether a player participated).

Unfortunately it's not super straightforward to count things besides damage.

We construct the teamfight objects here:
https://github.com/yasp-dota/yasp/blob/master/processors/processTeamfights.js

You can see that we're not tracking things like assists/heals.

* We could say that if a hero's xp_delta over the teamfight period was greater than some threshold count it as participation.  However, it could be thrown off if the hero gained xp from some other source (Roshan, farming, etc.)

**Comment by Shadowys** [comment]
Would it be better to also track buffs? I.e. tracking if a buff/debuff is added to a hero that participated in the teamfight. For example, AA could participate in a teamfight just by adding a debuff through his ult

**Comment by howardchung** [comment]
Technically possible but potentially very expensive to implement storage-wise since modifier names can be long and there are going to be lots of them per teamfight. The teamfights feature is already pretty storage intensive (~30-40KB/match).
