### ISSUE TITLE
Make use of matchmakingStatsRequest for GC stats

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#97]
Implement live-graph feature this way.

**Comment by howardc93** [comment]
Are we still planning to do something with this?  There are existing services that already do this (also yasp main can no longer access this call)

**Comment by howardc93** [comment]
We can use sockets to update in real-time

**Comment by howardc93** [comment]
probably best to delegate this call to a retriever, and have yasp main just report the results.

**Comment by howardc93** [comment]
low priority

**Comment by howardchung** [comment]
Well, it looks like @RJacksonm1 has retired https://rjackson.me/tools/mmstats/ with the shift to Reborn.

Perhaps it's worth doing this after all to replace it :)

**Comment by RJacksonm1** [comment]
Feel free to do so.  Fixing mmstats is on my todo list, but it might be a while until I get around to it.
