### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#972]
The yasp and profile tab redirect the user to the same page. I think you should remove the yasp tab.

Also, I made an [image](https://beta.postimg.org/image/5hrjaq2u4/) with the tabs rearranged and with the yasp tab replaced with the logo. You could make the logo redirect the user to a page. As you can see, I placed the profile and website related tabs to the right and the ones related to the dota comunity to the left.

Transparent icon background: #968

**Comment by howardchung** [comment]
@albertcui ?

**Comment by Vali19n** [comment]
More ideas came to my mind, so I'll post here because I don't want to annoy you by opening a lot of related issues. Here we go:

- The yellow box represents an ajax container. Every tab from the profile(overview, matches etc) changes the content inside the container, so that the website doesn't reload the entire page.

- On the "overview" page only 10 matches/heroes are shown and the user can click on the arrows (or scroll) to see other matches/heroes. The matches/heroes lists scroll individually. Advantage: the page will only have to load the latest 10 matches, resulting in faster loading of the page. The same principle can be applied to the "matches" tab. The box between the arrows shows the page number and the red line represents the scroll bar for the heroes list.

- I moved the profile name, mmr, winrate to the "overview" tab content. This change frees some space by removing the profile details from the content of unrelated tabs(e.g.:  trends, wardmap).

- I removed the "Last played" column in the heroes list("overview" tab) to create some space.

- I moved the "apply a filter" button because it was taking too much vertical space. Also, I made it smaller because it drew too much attention even if it is not used very often(in my case at least).

- Changed the icon's background to the website background. Related: #968 (icon background)

- The mmr estimate has a very high value after the "+-" sign. Can you make it smaller?

![image](https://cloud.githubusercontent.com/assets/13157676/14587169/8a7bd644-04b6-11e6-9ed0-f465522d24c3.png)

**Comment by howardchung** [comment]
* AJAX: We're actually in the (very slow) process of rewriting the entire frontend as a React SPA: https://github.com/yasp-dota/yasp/issues/889

* With the current server-side rendered model we need to gather all the matches to count things like W/L and heroes played anyway, so it doesn't really optimize to load just 10 matches.

* I think profile name at least has to be on all tabs to show what player is currently being displayed.

* Last played: Could remove from overview

* I'll see if I can move the filter button

* Estimate: Not sure what you mean by high value.  If you mean the uncertainty that's dependent on the matches played by the user.

* I think we need to display K, D, A separately.  Might be possible to squeeze into one column but will break the sorting.

* Honestly I am not sure if we are going to make any major changes to the current layout if we are going to be rewriting the whole thing anyway.  You should definitely give us your feedback on that when we have something semi-presentable, though.

**Comment by Vali19n** [comment]
- Estimate: yes, the uncertainity value.
- Profile name: rename "Profile" tab to profile name.
- Match/hero list: I think the aesthetic part alone could be worth it.
- KDA: It will be able to sort using the entire kda value. You could change this only on the overview tab.

**Comment by howardchung** [comment]
I made some tweaks.  Pull requests welcome if you want to do more.

**Comment by Vali19n** [comment]
I don't know a lot of js(I finished the tutorials for js and jquery on codecademy) and I'm not used to projects with more than 300 lines of code, but maybe I'll manage to help with code sometime.

**Comment by howardchung** [comment]
Most of the changes you're suggesting will be in the views, which are currently using Jade.  The React SPA will be in all JavaScript though.

**Comment by howardchung** [comment]
Don't think there is anything precisely actionable here, but we may consider some of these points when developing the SPA.
