### ISSUE TITLE
Russian characters in chat displayed as "?????" on newly parsed games

### ISSUE THREAD

**Issue by K900** [yasp-dota/yasp#973]
Seems to have started a day ago, not exactly sure when.
Last game for me that has correct chat: https://yasp.co/matches/2299668998/chat
Following game has ???? instead: https://yasp.co/matches/2300995208/chat

**Comment by howardchung** [comment]
This might be a problem with alpine linux not containing the locale support.  I'll see if there's a fix.  Otherwise we could go back to the old ubuntu image

**Comment by howardchung** [comment]
Looks like a problem with the glibc version used by the Java install.  Updated the image--it should be fully deployed within 24 hours.  You'll have to reparse any affected games manually.
