### ISSUE TITLE
Discrepancy between Hero Damage and Damage Done/Taken

### ISSUE THREAD

**Issue by rp2knight** [yasp-dota/yasp#975]
Looking at https://yasp.co/matches/2302620801/, there is a large discrepancy between the hero damage on the overview and computing the numbers by hand from the damage done/taken table on https://yasp.co/matches/2302620801/combat.  Looking at medusa for example gives roughly 95k hero damage dealt from the damage done/taken table, compared to the 43.4k damage done from the overview.

**Comment by howardchung** [comment]
Similar issue is https://github.com/yasp-dota/yasp/issues/904

Basically the data from the WebAPI seems to be lower than reported in the combat log.  I think the combat log data is more accurate (someone would have to match up the observed damage with the combat log by watching the replay to confirm it is correct).
