### ISSUE TITLE
delete anonymous_account_id

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#976]
May be able to get some speedup.  However we may need a lot of free space since the update will rewrite each affected row.

- [x] deploy change to stop writing anonymous account ids
- [x] `UPDATE player_matches SET account_id = NULL WHERE account_id = 4294967295;`
- [ ] `create index concurrently on player_matches(account_id) where account_id IS NOT NULL;`
- [ ] `DROP INDEX concurrently player_matches_account_id_idx;`

**Comment by howardchung** [comment]
@gortiz: I estimate about 66% of the 12 billion player_matches rows have the anonymous account id (2^32-1).  Would we benefit a lot by storing NULL in this row instead and utilizing a partial index?

**Comment by K900** [comment]
All anonymous players are displayed as ID 4294967295 right now, which links to a 404 page. Is that supposed to be happening in production?

**Comment by howardchung** [comment]
Yeah, they'll show up as that until the delete transaction goes through
(may take a week or so)

**Comment by howardchung** [comment]
Skipping the last two in favor of testing Cassandra migration.
