### ISSUE TITLE
Issue with quickstart guide, specifically node/npm

### ISSUE THREAD

**Issue by Toddish** [yasp-dota/yasp#978]
I'm going through the quickstart guide, and I'm getting stuck at:

> Get a terminal into the running container: sudo docker exec -it yasp bash

Which errors, saying the container isn't running.

After debugging, I basically can't run the ```node deploy.js``` command.

I've tried on node 0.10, 0.12, 4, 5, npm 1, 2, 3 and I can't get all the dependencies installed.

0.12 gives me the best chance it seems, but I end up with ```Cannot find module './lib/Yaml'``` when running ```node deploy.js```.

On my latest try I was using:

- Ubuntu 14.04.4, provisioned by puppet (not sure if that matters).
- Node v0.12.13
- npm 2.15.0

Hopefully the issue is something easy, or an obvious step that's missed out as it's expected anyway (I'm new to docker). All I really wanted to do was download and parse replays, but thought I'd get everything running first before going through it.

**Comment by howardchung** [comment]
What happened when you tried to start the container?
`sudo docker run -v $(pwd):/usr/src/yasp -di --name yasp --net=host yasp/yasp:latest`

What's the output of `sudo docker ps -a`?

**Comment by Toddish** [comment]
When I run the run command, I get back the container ref.

When I run the list command, I get:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
5965da8e9e37        yasp/yasp:latest    "node deploy.js"         6 seconds ago       Exited (1) 5 seconds ago                       yasp
79f2b938afa1        redis:latest        "/entrypoint.sh redis"   7 hours ago         Exited (0) 6 hours ago                         redis
c290b22f36df        postgres:latest     "/docker-entrypoint.s"   7 hours ago         Exited (0) 6 hours ago                         postgres
```

Where redit/postgress are running (I halted my machine a bit ago), but yasp is always Exited.

**Comment by howardchung** [comment]
Check the logs with sudo docker logs -f yasp

**Comment by Toddish** [comment]
Destroyed the box and went through the guide again so it's all fresh without any of my messing about.

Running the log command, I get:

```shell
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
module.js:341
    throw err;
    ^

Error: Cannot find module 'pm2'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/src/yasp/deploy.js:6:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

I'm going to try the guide on a fresh VPS, either tonight or tomorrow, and see what that gives me. Chances are it's my vagrant/puppet setup.

**Comment by howardchung** [comment]
First two lines are just a warning, not an error.  

I think you need to run `npm run build` in the container since mapping the host directory into the container loses the docker build.

Either that or there needs to be an existing build outside the container.

**Comment by Toddish** [comment]
I've just tried on a fresh Digital Ocean Ubuntu 14 droplet, and got the exact same error, so it's not the vagrant setup.

This might be a dumb question, but how can I run npm run build in the container if the container exits right away?

And I'm not sure how to build it outside the container, do you just mean install npm and run npm build?

Does the quickstart guide work for you on Ubuntu?

Rest assured, some cheese will be coming your way!

**Comment by howardchung** [comment]
I'll need to make a code fix.  It works for me locally because I have a
build outside the container (which gets mapped inside). If you're starting
from scratch then it doesn't work because no build means no pm2 installed.

Thanks for finding it

**Comment by howardchung** [comment]
OK, I've updated the Dockerfile to remove the dependency on pm2.

Remove your old container:
`sudo docker rm -fv yasp`

Pull new image:
`sudo docker pull yasp/yasp:latest`

I also added a step to the README to build inside the container with `npm run build`.

Then start over with creating a new container.  Let me know if there are any further issues.

**Comment by Toddish** [comment]
Tried it again with a fresh box, and it loaded up the terminal fine.

Massive thanks for the help!
