### ISSUE TITLE
KDA isn't calculated properly

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#980]
I found a bug in the kda calculation process. There was a match when I played medusa(https://yasp.co/matches/2303332264) and my score was 7-1-22, but in the "records" tab, my kda value is 14(14.5) instead of 29. I think the function that calculates the kda adds a death even if I don't have 0 deaths.

**Comment by howardchung** [comment]
Not a bug.  This is intended to avoid divide by 0 errors.  Also I think it's more accurate as a "kills to lives used" ratio.

**Comment by Vali19n** [comment]
You mean that you don't count assits too?
I think using you should add 1 death only if the death count is 0. In that match I already have one death, so there was no division by 0.

**Comment by howardchung** [comment]
The formula is (K+A/(D+1)).

**Comment by howardchung** [comment]
You can think of your initial spawn as a death+life cycle.

**Comment by Vali19n** [comment]
Now I understand.
