### ISSUE TITLE
Highest mmr

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#982]
If you still want to display the highest mmr of the player, you can make it visible as a tooltip that activates on mouseover, similar to what you did to the uncertainty rate for the MMR estimate.

**Comment by howardchung** [comment]
This would require a separate API endpoint to fetch just this value.  I'm not sure if it's worth it for a single data point.

**Comment by Vali19n** [comment]
Isn't this possible by storing the current mmr and change it whenever it passes the latest highest value? (player_id.highest_solo_mmr and player_id.highest_party_mmr)

**Comment by howardchung** [comment]
I'd like to avoid get then set if possible, and I don't think Redis has a built in setmax command

**Comment by Vali19n** [comment]
Okay.
