### ISSUE TITLE
Dewards on the Vision map

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#983]
Currently, the Vision map only shows the location of the placed observer and sentry wards but it doesn't show which particular wards were countered/destroyed.

Having this data helps the player his warding/dewarding skills.

**Comment by howardchung** [comment]
Dewards are tricky because we don't have a good way of identifying the reason a ward entity disappears.

**Comment by gortiz** [comment]
Shouldn't be the time it survive a good way of identifying? ie if an
observer ward lives 420 +- delta secs, then it expired, in other case it
was destroyed by someone. It might not be 100% precise, but useful enough

2016-04-22 1:02 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
Figuring out who destroyed it is kind of annoying.  I don't think if there's a better way than guessing based on spatial locality.

**Comment by gortiz** [comment]
But... if you know when the ward was placed and when the ward "died"... can
you infer whether it was killed or expired base on the time it lived? I
know someone can kill the ward on the same second it should expire, but it
seems an acceptable error.

I think @lomash does not requires to know who destroyed the ward but
whether a ward was destroyed or it simply expires

2016-04-22 9:22 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by lomash** [comment]
What I initially thought was that when you hover over the number of dewards for a player, it shows you the wards that the player dewarded on the map. But since that might be difficult to determine, here's what we can do instead.

Like @gortiz said, it should be possible to know what wards were dewarded(doesn't matter by who or when), then these wards can be shown on the map with an X indicating they were killed before the expiry time.

This allows you to have a general idea of which of your/their wards were countered.

**Comment by howardchung** [comment]
merge with #502
