### ISSUE TITLE
Match Overview Table Formatting

### ISSUE THREAD

**Issue by onelivesleft** [yasp-dota/yasp#987]
Simple, minor layout bug (imho).  This table alternates light grey and dark grey to delineate rows.  The bottom player row as well as the two rows below it (showing Radiant and Dire) are all dark grey; Radiant and Dire should be light grey instead, to help legibility. Dire could toggle to dark grey, potentially, though I think having them both the same would be best.

Current:
![current](https://cloud.githubusercontent.com/assets/17881109/14770482/8573a92e-0a6a-11e6-8ce2-f4e1b08426a5.png)

Proposed:
![proposed](https://cloud.githubusercontent.com/assets/17881109/14770489/a906a580-0a6a-11e6-8fc9-11722b55ce63.png)

EDIT: same issue on Performances, Purchases, Farm, Combat... basically anywhere there is a summary row for the teams.

**Comment by howardchung** [comment]
Anyone know how to fix this?

**Comment by onelivesleft** [comment]
This CSS would do it:

tfoot tr {
    background-color: #3d3d3d;
}

**Comment by howardchung** [comment]
Submit a PR?  @albertcui will review it

**Comment by onelivesleft** [comment]
OK, have done so.  First time doing so, so I hope it's done right.

**Comment by howardchung** [comment]
I don't see it yet.  Don't worry about doing it wrong, we can help you through the process :)

**Comment by onelivesleft** [comment]
I think I had merged the pull request with my own fork or something?  Think I've done it right now.
