### ISSUE TITLE
Display mean MMR instead of totals in match overview table

### ISSUE THREAD

**Issue by rossengeorgiev** [yasp-dota/yasp#990]
Currently the last 2 rows show the totals of each team, however that doesn't make sense for MMR column. I think it should show mean MMR for the each team instead.

**Comment by howardchung** [comment]
Could be done.  The current code just sums all columns in the table.  Would need to add some custom code to decide whether to take the average.

**Comment by howardchung** [comment]
Client side, please reopen in https://github.com/yasp-dota/ui
