### ISSUE TITLE
Search fails on short queries

### ISSUE THREAD

**Issue by darrenburns** [yasp-dota/yasp#991]
Search doesn't work when the input is very short. It won't work at all for me for two character queries, and only some three character queries work.

Does a GIN index exist on the players.personaname column?

Assuming I'm looking at the correct piece of code ([from here](https://github.com/yasp-dota/yasp/blob/master/queries.js#L946)):

```
                db.raw(`
                    SELECT account_id, personaname, avatarfull, similarity(personaname, ?)
                    FROM players WHERE personaname ILIKE ?
                    ORDER BY similarity DESC LIMIT 100
                    `, [query, "%" + query + "%"])
```

Have you ensured that including ILIKE in the query gives performance improvements compared to leaving it out, or compared to using the [similarity operator](http://www.postgresql.org/docs/9.1/static/pgtrgm.html) (%)? If you are pre Postgres 9.1 then ILIKE will be a significant bottleneck in this case.

**Comment by howardchung** [comment]
Doesn't work meaning timing out?

I think we are using the similarity operator currently with ILIKE (that's why the query is surrounded with "%").

We are on postgres 9.5

**Comment by darrenburns** [comment]
Yes, timing out. The thing you're using in ILIKE isn't the similarity operator. I mean it might be better to write the query so that it uses the % operator as seen below.

```
SELECT t, similarity(t, 'word') AS sml
  FROM test_trgm
  WHERE t % 'word'   -- Include only rows where similarity of words > threshold
  ORDER BY sml DESC, t;
```
If a GIN index doesn't exist on that column, then search is always going to be much slower than possible regardless of whether ILIKE is used or not.

**Comment by howardchung** [comment]
we have a GIN index on the personaname field.  We might have to try running some test queries manually against the production DB to see if this works.

**Comment by howardchung** [comment]
Looks like the timeout is due to too many results.  Something like the following may work (get the first 1000 results then limit to 100
```
SELECT * FROM 
(SELECT account_id, similarity(personaname, 'a') AS sml
  FROM players
  WHERE personaname % 'a'
LIMIT 1000
) search
  ORDER BY sml DESC
LIMIT 100;
```

**Comment by howardchung** [comment]
Committed.  It's going on the big PR that I think we'll be merging this weekend.  Hope there are no fires :)
