### ISSUE TITLE
i pull the new version but cant search player

### ISSUE THREAD

**Issue by nt47** [yasp-dota/yasp#993]
http://103.41.132.60:5000/

**Comment by nt47** [comment]
click tab-carry  also get error

**Comment by howardchung** [comment]
Looks like a problem with the permissions on the players table.  You can try setting the owner to user `yasp` in postgres

**Comment by nt47** [comment]
LOOKS LIKE WE COULDN'T FIND ANYTHING!

**Comment by nt47** [comment]
how can i get more ppl info ?
 make some spiders ? then save into database?

**Comment by howardchung** [comment]
As I said before, you can add some matches via scanner or request, then run the `profiler` service to load player data.
