### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by nt47** [yasp-dota/yasp#995]
● web                                [                              ] 0 %
[0] [fork_mode]                        [|||||||||||||                 ] 170.398 MB  
 ● scanner                            [||||||||||||||||||||||||||||||] 100 %] [fork_mode]                        [|||||                         ] 66.383 MB  
 ● profiler                           [                              ] 0 %
[2] [fork_mode]                        [||||                          ] 52.531 MB  
 ● redis                              [                              ] 0 %
[3] [fork_mode]                        [||||||||||||||||||            ] 22.855 MB 

2G2CPU keep working 1hours
 then server die  mb need 4G4CPU or 8G4CPU server?
and how to make it scan my steamid by inputing ?

**Comment by howardchung** [comment]
2GB should be fine.  You can sign in through steam and run the `worker` service to add your account to the tracked players set.

**Comment by nt47** [comment]
redis always crash
and eating ram

**Comment by howardchung** [comment]
you might need more RAM then.

**Comment by nt47** [comment]
how many servers does yasp.co use ?
all=4CPU 8GB ?
i think need some scanner servers

**Comment by howardchung** [comment]
It's highly distributed.  However scanner is running with a bunch of other services on a 7.5GB, 2 core VM.

**Comment by nt47** [comment]
core server run redis.js ?
i want to simulate yasp.co 
can u help me ?
cuz i want show player full data in playing game

**Comment by howardchung** [comment]
redis.js is not a service by itself.  It's an interface for the others to use to access a Redis server (which runs independently of YASP).

You need to pick and choose what services you want to run.  If you just want replay parsing I recommend `web`, `retriever`, `parser`, and `requests`.  Then you can just use the request form to parse whatever matches you want by ID.

For this I would say that 4GB is plenty.

Is there a reason you can't use the publicly hosted service at https://yasp.co?

**Comment by nt47** [comment]
if u can private api for me return json 
like 
XXXXXXX/api/GetMMR/
XXXXXXX/api/GetWinrate/
restful API----my client can getdata
i even dont build servers  
payment is also fine

**Comment by howardchung** [comment]
You can use the unofficial API.

Example:
https://yasp.co/api/players/88367253

It is not completely stable yet and we may break it without warning.

**Comment by nt47** [comment]
awesome!
but can u add CN servers?
cuz GFW make speed too slow
i have to use vpn

**Comment by howardchung** [comment]
Unfortunately I don't think we have plans to do that (GCE doesn't offer china servers as far as I know).  Also I don't think we can afford to spin up any more servers.

**Comment by nt47** [comment]
nwm~ i can use hk server bridge json info then send to client ,just dont ban my server  ip plz
and all info is fine now  
and how about adding apm data in
https://yasp.co/api/players/88367253 ~~~

**Comment by howardchung** [comment]
Might happen eventually. No plan to do that in the near future though.
