### ISSUE TITLE
How to download the replay ?

### ISSUE THREAD

**Issue by jacobxy** [yasp-dota/yasp#996]
When I study the method of downloading the replay,  I find that the url contain the key named "cluster" which I can get from the detail of matchinfo, but I can't get the next key named "replay_salt" . So, can you tell me How to get the replayer_salt  and give me a example to download a replay from valve ! Thanks !

**Comment by howardchung** [comment]
You need to use a library such as node-dota2 to emulate a client and make a match details request (which will contain the replay salt).  `retriever.js` is an implementation of this.
