### ISSUE TITLE
Benchmark's percentile based on match duration

### ISSUE THREAD

**Issue by vhpanisa** [yasp-dota/yasp#997]
Taking [this game](https://yasp.co/matches/2320312196/benchmarks) as example.

PA have 5 kills and 2 deaths. The early game usually is mostly farm for the core hero. As this game ended too soon, 5 kills is only above 31% of the PA matches. But, this probably is taking into account ALL matches, right? I think a more accurate percentile would be measuring against matches with similar duration, maybe with a 5 min deviation for more or less.

**Comment by mxDixon** [comment]
This is how match performance in overwatch is measured per character. It's a reasonable suggestion.

**Comment by howardchung** [comment]
We have "per minute" benchmarks for kills already
