### ISSUE TITLE
Fix off by one error in MMR distribution

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#998]
IIRC saw this on Reddit.  We currently bucket users down to the nearest 100, but the percentile considers users equal or less than the next 100 up.

**Comment by rossengeorgiev** [comment]
Technically both are correct. Currently 0 MMR is in 0.08th percentile, but it's at 0th percentile. Imo the latter is more easily understood. So, 0% of the population is below for 0 MMR, and 0.08% for 100 MMR etc. Off by one.

Another nitpick, 1 MMR is the lowest possible MMR, while 0 is used for not calibrated.

**Comment by howardchung** [comment]
We exclude 0 MMR from the query so it should be okay.
