### ISSUE TITLE
EFF@10 shouldn't count passive gold

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#999]
Since the passive gold is always given to the player, having it in the computation doesn't offer anything useful and can be misleading at times.
E.g. https://yasp.co/matches/2291764192/performances

Player 3 never spawned in the game and still has an EFF@10 of 22.87 which might be just due to the tick gold. Meanwhile, everyone else started getting more passive gold after the abandon, which put the value over 100.

**Comment by howardchung** [comment]
I think it's still best to show it as the actual amount of gold obtained.  I realize there are corner cases but users can interpret the data with context.
